
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_os_ContextProxy_H
#define android_os_ContextProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace os {
class ContextProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/content/Context";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    ContextProxy() {}
    ContextProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    ContextProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static ContextProxy fromLocalRef(jobject localRef) {
        ContextProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr auto ACCESSIBILITY_SERVICE = u8"accessibility";
    static constexpr auto ACCOUNT_SERVICE = u8"account";
    static constexpr auto ACTIVITY_SERVICE = u8"activity";
    static constexpr auto ALARM_SERVICE = u8"alarm";
    static constexpr auto APPWIDGET_SERVICE = u8"appwidget";
    static constexpr auto APP_OPS_SERVICE = u8"appops";
    static constexpr auto APP_SEARCH_SERVICE = u8"app_search";
    static constexpr auto AUDIO_SERVICE = u8"audio";
    static constexpr auto BATTERY_SERVICE = u8"batterymanager";
    static constexpr jint BIND_ABOVE_CLIENT = 8;
    static constexpr jint BIND_ADJUST_WITH_ACTIVITY = 128;
    static constexpr jint BIND_ALLOW_ACTIVITY_STARTS = 512;
    static constexpr jint BIND_ALLOW_OOM_MANAGEMENT = 16;
    static constexpr jint BIND_AUTO_CREATE = 1;
    static constexpr jint BIND_DEBUG_UNBIND = 2;
    static constexpr jint BIND_EXTERNAL_SERVICE = -2147483648;
    static constexpr jlong BIND_EXTERNAL_SERVICE_LONG = 4611686018427387904;
    static constexpr jint BIND_IMPORTANT = 64;
    static constexpr jint BIND_INCLUDE_CAPABILITIES = 4096;
    static constexpr jint BIND_NOT_FOREGROUND = 4;
    static constexpr jint BIND_NOT_PERCEPTIBLE = 256;
    static constexpr jint BIND_PACKAGE_ISOLATED_PROCESS = 16384;
    static constexpr jint BIND_SHARED_ISOLATED_PROCESS = 8192;
    static constexpr jint BIND_WAIVE_PRIORITY = 32;
    static constexpr auto BIOMETRIC_SERVICE = u8"biometric";
    static constexpr auto BLOB_STORE_SERVICE = u8"blob_store";
    static constexpr auto BLUETOOTH_SERVICE = u8"bluetooth";
    static constexpr auto BUGREPORT_SERVICE = u8"bugreport";
    static constexpr auto CAMERA_SERVICE = u8"camera";
    static constexpr auto CAPTIONING_SERVICE = u8"captioning";
    static constexpr auto CARRIER_CONFIG_SERVICE = u8"carrier_config";
    static constexpr auto CLIPBOARD_SERVICE = u8"clipboard";
    static constexpr auto COMPANION_DEVICE_SERVICE = u8"companiondevice";
    static constexpr auto CONNECTIVITY_DIAGNOSTICS_SERVICE = u8"connectivity_diagnostics";
    static constexpr auto CONNECTIVITY_SERVICE = u8"connectivity";
    static constexpr auto CONSUMER_IR_SERVICE = u8"consumer_ir";
    static constexpr auto CONTACT_KEYS_SERVICE = u8"contact_keys";
    static constexpr jint CONTEXT_IGNORE_SECURITY = 2;
    static constexpr jint CONTEXT_INCLUDE_CODE = 1;
    static constexpr jint CONTEXT_RESTRICTED = 4;
    static constexpr auto CREDENTIAL_SERVICE = u8"credential";
    static constexpr auto CROSS_PROFILE_APPS_SERVICE = u8"crossprofileapps";
    static constexpr jint DEVICE_ID_DEFAULT = 0;
    static constexpr jint DEVICE_ID_INVALID = -1;
    static constexpr auto DEVICE_LOCK_SERVICE = u8"device_lock";
    static constexpr auto DEVICE_POLICY_SERVICE = u8"device_policy";
    static constexpr auto DISPLAY_HASH_SERVICE = u8"display_hash";
    static constexpr auto DISPLAY_SERVICE = u8"display";
    static constexpr auto DOMAIN_VERIFICATION_SERVICE = u8"domain_verification";
    static constexpr auto DOWNLOAD_SERVICE = u8"download";
    static constexpr auto DROPBOX_SERVICE = u8"dropbox";
    static constexpr auto EUICC_SERVICE = u8"euicc";
    static constexpr auto FILE_INTEGRITY_SERVICE = u8"file_integrity";
    static constexpr auto FINGERPRINT_SERVICE = u8"fingerprint";
    static constexpr auto GAME_SERVICE = u8"game";
    static constexpr auto GRAMMATICAL_INFLECTION_SERVICE = u8"grammatical_inflection";
    static constexpr auto HARDWARE_PROPERTIES_SERVICE = u8"hardware_properties";
    static constexpr auto HEALTHCONNECT_SERVICE = u8"healthconnect";
    static constexpr auto INPUT_METHOD_SERVICE = u8"input_method";
    static constexpr auto INPUT_SERVICE = u8"input";
    static constexpr auto IPSEC_SERVICE = u8"ipsec";
    static constexpr auto JOB_SCHEDULER_SERVICE = u8"jobscheduler";
    static constexpr auto KEYGUARD_SERVICE = u8"keyguard";
    static constexpr auto LAUNCHER_APPS_SERVICE = u8"launcherapps";
    static constexpr auto LAYOUT_INFLATER_SERVICE = u8"layout_inflater";
    static constexpr auto LOCALE_SERVICE = u8"locale";
    static constexpr auto LOCATION_SERVICE = u8"location";
    static constexpr auto MEDIA_COMMUNICATION_SERVICE = u8"media_communication";
    static constexpr auto MEDIA_METRICS_SERVICE = u8"media_metrics";
    static constexpr auto MEDIA_PROJECTION_SERVICE = u8"media_projection";
    static constexpr auto MEDIA_ROUTER_SERVICE = u8"media_router";
    static constexpr auto MEDIA_SESSION_SERVICE = u8"media_session";
    static constexpr auto MIDI_SERVICE = u8"midi";
    static constexpr jint MODE_APPEND = 32768;
    static constexpr jint MODE_ENABLE_WRITE_AHEAD_LOGGING = 8;
    static constexpr jint MODE_MULTI_PROCESS = 4;
    static constexpr jint MODE_NO_LOCALIZED_COLLATORS = 16;
    static constexpr jint MODE_PRIVATE = 0;
    static constexpr jint MODE_WORLD_READABLE = 1;
    static constexpr jint MODE_WORLD_WRITEABLE = 2;
    static constexpr auto NETWORK_STATS_SERVICE = u8"netstats";
    static constexpr auto NFC_SERVICE = u8"nfc";
    static constexpr auto NOTIFICATION_SERVICE = u8"notification";
    static constexpr auto NSD_SERVICE = u8"servicediscovery";
    static constexpr auto OVERLAY_SERVICE = u8"overlay";
    static constexpr auto PEOPLE_SERVICE = u8"people";
    static constexpr auto PERFORMANCE_HINT_SERVICE = u8"performance_hint";
    static constexpr auto PERSISTENT_DATA_BLOCK_SERVICE = u8"persistent_data_block";
    static constexpr auto POWER_SERVICE = u8"power";
    static constexpr auto PRINT_SERVICE = u8"print";
    static constexpr auto PROFILING_SERVICE = u8"profiling";
    static constexpr jint RECEIVER_EXPORTED = 2;
    static constexpr jint RECEIVER_NOT_EXPORTED = 4;
    static constexpr jint RECEIVER_VISIBLE_TO_INSTANT_APPS = 1;
    static constexpr auto RESTRICTIONS_SERVICE = u8"restrictions";
    static constexpr auto ROLE_SERVICE = u8"role";
    static constexpr auto SEARCH_SERVICE = u8"search";
    static constexpr auto SECURITY_STATE_SERVICE = u8"security_state";
    static constexpr auto SENSOR_SERVICE = u8"sensor";
    static constexpr auto SHORTCUT_SERVICE = u8"shortcut";
    static constexpr auto STATUS_BAR_SERVICE = u8"statusbar";
    static constexpr auto STORAGE_SERVICE = u8"storage";
    static constexpr auto STORAGE_STATS_SERVICE = u8"storagestats";
    static constexpr auto SYSTEM_HEALTH_SERVICE = u8"systemhealth";
    static constexpr auto TELECOM_SERVICE = u8"telecom";
    static constexpr auto TELEPHONY_IMS_SERVICE = u8"telephony_ims";
    static constexpr auto TELEPHONY_SERVICE = u8"phone";
    static constexpr auto TELEPHONY_SUBSCRIPTION_SERVICE = u8"telephony_subscription_service";
    static constexpr auto TEXT_CLASSIFICATION_SERVICE = u8"textclassification";
    static constexpr auto TEXT_SERVICES_MANAGER_SERVICE = u8"textservices";
    static constexpr auto TV_INPUT_SERVICE = u8"tv_input";
    static constexpr auto TV_INTERACTIVE_APP_SERVICE = u8"tv_interactive_app";
    static constexpr auto UI_MODE_SERVICE = u8"uimode";
    static constexpr auto USAGE_STATS_SERVICE = u8"usagestats";
    static constexpr auto USB_SERVICE = u8"usb";
    static constexpr auto USER_SERVICE = u8"user";
    static constexpr auto VIBRATOR_MANAGER_SERVICE = u8"vibrator_manager";
    static constexpr auto VIBRATOR_SERVICE = u8"vibrator";
    static constexpr auto VIRTUAL_DEVICE_SERVICE = u8"virtualdevice";
    static constexpr auto VPN_MANAGEMENT_SERVICE = u8"vpn_management";
    static constexpr auto WALLPAPER_SERVICE = u8"wallpaper";
    static constexpr auto WIFI_AWARE_SERVICE = u8"wifiaware";
    static constexpr auto WIFI_P2P_SERVICE = u8"wifip2p";
    static constexpr auto WIFI_RTT_RANGING_SERVICE = u8"wifirtt";
    static constexpr auto WIFI_SERVICE = u8"wifi";
    static constexpr auto WINDOW_SERVICE = u8"window";


    // construct: public Context()
    static ContextProxy newInstance() {
        ContextProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "()V");
        return ret;
    }

    // method: public abstract android.content.res.AssetManager getAssets()
    auto getAssets() const {
        return m_jniObject.callMethod<jobject>(
                        "getAssets",
                        "()Landroid/content/res/AssetManager;");
    }


    // method: public abstract android.content.res.Resources getResources()
    auto getResources() const {
        return m_jniObject.callMethod<jobject>(
                        "getResources",
                        "()Landroid/content/res/Resources;");
    }


    // method: public abstract android.content.pm.PackageManager getPackageManager()
    auto getPackageManager() const {
        return m_jniObject.callMethod<jobject>(
                        "getPackageManager",
                        "()Landroid/content/pm/PackageManager;");
    }


    // method: public abstract android.content.ContentResolver getContentResolver()
    auto getContentResolver() const {
        return m_jniObject.callMethod<jobject>(
                        "getContentResolver",
                        "()Landroid/content/ContentResolver;");
    }


    // method: public abstract android.os.Looper getMainLooper()
    auto getMainLooper() const {
        return m_jniObject.callMethod<jobject>(
                        "getMainLooper",
                        "()Landroid/os/Looper;");
    }


    // method: public java.util.concurrent.Executor getMainExecutor()
    auto getMainExecutor() const {
        return m_jniObject.callMethod<jobject>(
                        "getMainExecutor",
                        "()Ljava/util/concurrent/Executor;");
    }


    // method: public abstract android.content.Context getApplicationContext()
    auto getApplicationContext() const {
        return m_jniObject.callMethod<jobject>(
                        "getApplicationContext",
                        "()Landroid/content/Context;");
    }


    // method: public void registerComponentCallbacks(android.content.ComponentCallbacks callback)
    auto registerComponentCallbacks(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "registerComponentCallbacks",
                        "(Landroid/content/ComponentCallbacks;)V", callback);
    }


    // method: public void unregisterComponentCallbacks(android.content.ComponentCallbacks callback)
    auto unregisterComponentCallbacks(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "unregisterComponentCallbacks",
                        "(Landroid/content/ComponentCallbacks;)V", callback);
    }


    // method: public final java.lang.CharSequence getText(int resId)
    auto getText(jint resId) const {
        return m_jniObject.callMethod<jobject>(
                        "getText",
                        "(I)Ljava/lang/CharSequence;", resId);
    }


    // method: public final java.lang.String getString(int resId)
    auto getString(jint resId) const {
        return m_jniObject.callMethod<jstring>(
                        "getString",
                        "(I)Ljava/lang/String;", resId);
    }


    // method: public final java.lang.String getString(int resId, java.lang.Object[] formatArgs)
    auto getString(jint resId, jobjectArray formatArgs) const {
        return m_jniObject.callMethod<jstring>(
                        "getString",
                        "(I[Ljava/lang/Object;)Ljava/lang/String;", resId, formatArgs);
    }


    // method: public final int getColor(int id)
    auto getColor(jint id) const {
        return m_jniObject.callMethod<jint>(
                        "getColor",
                        "(I)I", id);
    }


    // method: public final android.graphics.drawable.Drawable getDrawable(int id)
    auto getDrawable(jint id) const {
        return m_jniObject.callMethod<jobject>(
                        "getDrawable",
                        "(I)Landroid/graphics/drawable/Drawable;", id);
    }


    // method: public final android.content.res.ColorStateList getColorStateList(int id)
    auto getColorStateList(jint id) const {
        return m_jniObject.callMethod<jobject>(
                        "getColorStateList",
                        "(I)Landroid/content/res/ColorStateList;", id);
    }


    // method: public abstract void setTheme(int arg0)
    auto setTheme(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "setTheme",
                        "(I)V", arg0);
    }


    // method: public abstract android.content.res.Resources.Theme getTheme()
    auto getTheme() const {
        return m_jniObject.callMethod<jobject>(
                        "getTheme",
                        "()Landroid/content/res/Resources$Theme;");
    }


    // method: public final android.content.res.TypedArray obtainStyledAttributes(int[] attrs)
    auto obtainStyledAttributes(jintArray attrs) const {
        return m_jniObject.callMethod<jobject>(
                        "obtainStyledAttributes",
                        "([I)Landroid/content/res/TypedArray;", attrs);
    }


    // method: public final android.content.res.TypedArray obtainStyledAttributes(int resid, int[] attrs)
    auto obtainStyledAttributes(jint resid, jintArray attrs) const {
        return m_jniObject.callMethod<jobject>(
                        "obtainStyledAttributes",
                        "(I[I)Landroid/content/res/TypedArray;", resid, attrs);
    }


    // method: public final android.content.res.TypedArray obtainStyledAttributes(android.util.AttributeSet set, int[] attrs)
    auto obtainStyledAttributes(jobject set, jintArray attrs) const {
        return m_jniObject.callMethod<jobject>(
                        "obtainStyledAttributes",
                        "(Landroid/util/AttributeSet;[I)Landroid/content/res/TypedArray;", set, attrs);
    }


    // method: public final android.content.res.TypedArray obtainStyledAttributes(android.util.AttributeSet set, int[] attrs, int defStyleAttr, int defStyleRes)
    auto obtainStyledAttributes(jobject set, jintArray attrs, jint defStyleAttr, jint defStyleRes) const {
        return m_jniObject.callMethod<jobject>(
                        "obtainStyledAttributes",
                        "(Landroid/util/AttributeSet;[III)Landroid/content/res/TypedArray;", set, attrs, defStyleAttr, defStyleRes);
    }


    // method: public abstract java.lang.ClassLoader getClassLoader()
    auto getClassLoader() const {
        return m_jniObject.callMethod<jobject>(
                        "getClassLoader",
                        "()Ljava/lang/ClassLoader;");
    }


    // method: public abstract java.lang.String getPackageName()
    auto getPackageName() const {
        return m_jniObject.callMethod<jstring>(
                        "getPackageName",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String getOpPackageName()
    auto getOpPackageName() const {
        return m_jniObject.callMethod<jstring>(
                        "getOpPackageName",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String getAttributionTag()
    auto getAttributionTag() const {
        return m_jniObject.callMethod<jstring>(
                        "getAttributionTag",
                        "()Ljava/lang/String;");
    }


    // method: public android.content.AttributionSource getAttributionSource()
    auto getAttributionSource() const {
        return m_jniObject.callMethod<jobject>(
                        "getAttributionSource",
                        "()Landroid/content/AttributionSource;");
    }


    // method: public android.content.ContextParams getParams()
    auto getParams() const {
        return m_jniObject.callMethod<jobject>(
                        "getParams",
                        "()Landroid/content/ContextParams;");
    }


    // method: public abstract android.content.pm.ApplicationInfo getApplicationInfo()
    auto getApplicationInfo() const {
        return m_jniObject.callMethod<jobject>(
                        "getApplicationInfo",
                        "()Landroid/content/pm/ApplicationInfo;");
    }


    // method: public abstract java.lang.String getPackageResourcePath()
    auto getPackageResourcePath() const {
        return m_jniObject.callMethod<jstring>(
                        "getPackageResourcePath",
                        "()Ljava/lang/String;");
    }


    // method: public abstract java.lang.String getPackageCodePath()
    auto getPackageCodePath() const {
        return m_jniObject.callMethod<jstring>(
                        "getPackageCodePath",
                        "()Ljava/lang/String;");
    }


    // method: public abstract android.content.SharedPreferences getSharedPreferences(java.lang.String arg0, int arg1)
    auto getSharedPreferences(jstring arg0, jint arg1) const {
        return m_jniObject.callMethod<jobject>(
                        "getSharedPreferences",
                        "(Ljava/lang/String;I)Landroid/content/SharedPreferences;", arg0, arg1);
    }


    // method: public abstract boolean moveSharedPreferencesFrom(android.content.Context arg0, java.lang.String arg1)
    auto moveSharedPreferencesFrom(jobject arg0, jstring arg1) const {
        return m_jniObject.callMethod<jboolean>(
                        "moveSharedPreferencesFrom",
                        "(Landroid/content/Context;Ljava/lang/String;)Z", arg0, arg1);
    }


    // method: public abstract boolean deleteSharedPreferences(java.lang.String arg0)
    auto deleteSharedPreferences(jstring arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "deleteSharedPreferences",
                        "(Ljava/lang/String;)Z", arg0);
    }


    // method: public abstract java.io.FileInputStream openFileInput(java.lang.String arg0)
    auto openFileInput(jstring arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "openFileInput",
                        "(Ljava/lang/String;)Ljava/io/FileInputStream;", arg0);
    }


    // method: public abstract java.io.FileOutputStream openFileOutput(java.lang.String arg0, int arg1)
    auto openFileOutput(jstring arg0, jint arg1) const {
        return m_jniObject.callMethod<jobject>(
                        "openFileOutput",
                        "(Ljava/lang/String;I)Ljava/io/FileOutputStream;", arg0, arg1);
    }


    // method: public abstract boolean deleteFile(java.lang.String arg0)
    auto deleteFile(jstring arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "deleteFile",
                        "(Ljava/lang/String;)Z", arg0);
    }


    // method: public abstract java.io.File getFileStreamPath(java.lang.String arg0)
    auto getFileStreamPath(jstring arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "getFileStreamPath",
                        "(Ljava/lang/String;)Ljava/io/File;", arg0);
    }


    // method: public abstract java.io.File getDataDir()
    auto getDataDir() const {
        return m_jniObject.callMethod<jobject>(
                        "getDataDir",
                        "()Ljava/io/File;");
    }


    // method: public abstract java.io.File getFilesDir()
    auto getFilesDir() const {
        return m_jniObject.callMethod<jobject>(
                        "getFilesDir",
                        "()Ljava/io/File;");
    }


    // method: public abstract java.io.File getNoBackupFilesDir()
    auto getNoBackupFilesDir() const {
        return m_jniObject.callMethod<jobject>(
                        "getNoBackupFilesDir",
                        "()Ljava/io/File;");
    }


    // method: public abstract java.io.File getExternalFilesDir(java.lang.String arg0)
    auto getExternalFilesDir(jstring arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "getExternalFilesDir",
                        "(Ljava/lang/String;)Ljava/io/File;", arg0);
    }


    // method: public abstract java.io.File[] getExternalFilesDirs(java.lang.String arg0)
    auto getExternalFilesDirs(jstring arg0) const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getExternalFilesDirs",
                        "(Ljava/lang/String;)[Ljava/io/File;", arg0);
    }


    // method: public abstract java.io.File getObbDir()
    auto getObbDir() const {
        return m_jniObject.callMethod<jobject>(
                        "getObbDir",
                        "()Ljava/io/File;");
    }


    // method: public abstract java.io.File[] getObbDirs()
    auto getObbDirs() const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getObbDirs",
                        "()[Ljava/io/File;");
    }


    // method: public abstract java.io.File getCacheDir()
    auto getCacheDir() const {
        return m_jniObject.callMethod<jobject>(
                        "getCacheDir",
                        "()Ljava/io/File;");
    }


    // method: public abstract java.io.File getCodeCacheDir()
    auto getCodeCacheDir() const {
        return m_jniObject.callMethod<jobject>(
                        "getCodeCacheDir",
                        "()Ljava/io/File;");
    }


    // method: public abstract java.io.File getExternalCacheDir()
    auto getExternalCacheDir() const {
        return m_jniObject.callMethod<jobject>(
                        "getExternalCacheDir",
                        "()Ljava/io/File;");
    }


    // method: public abstract java.io.File[] getExternalCacheDirs()
    auto getExternalCacheDirs() const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getExternalCacheDirs",
                        "()[Ljava/io/File;");
    }


    // method: public abstract java.io.File[] getExternalMediaDirs()
    auto getExternalMediaDirs() const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getExternalMediaDirs",
                        "()[Ljava/io/File;");
    }


    // method: public abstract java.lang.String[] fileList()
    auto fileList() const {
        return m_jniObject.callMethod<jobjectArray>(
                        "fileList",
                        "()[Ljava/lang/String;");
    }


    // method: public abstract java.io.File getDir(java.lang.String arg0, int arg1)
    auto getDir(jstring arg0, jint arg1) const {
        return m_jniObject.callMethod<jobject>(
                        "getDir",
                        "(Ljava/lang/String;I)Ljava/io/File;", arg0, arg1);
    }


    // method: public abstract android.database.sqlite.SQLiteDatabase openOrCreateDatabase(java.lang.String arg0, int arg1, android.database.sqlite.SQLiteDatabase.CursorFactory arg2)
    auto openOrCreateDatabase(jstring arg0, jint arg1, jobject arg2) const {
        return m_jniObject.callMethod<jobject>(
                        "openOrCreateDatabase",
                        "(Ljava/lang/String;ILandroid/database/sqlite/SQLiteDatabase$CursorFactory;)Landroid/database/sqlite/SQLiteDatabase;", arg0, arg1, arg2);
    }


    // method: public abstract android.database.sqlite.SQLiteDatabase openOrCreateDatabase(java.lang.String arg0, int arg1, android.database.sqlite.SQLiteDatabase.CursorFactory arg2, android.database.DatabaseErrorHandler arg3)
    auto openOrCreateDatabase(jstring arg0, jint arg1, jobject arg2, jobject arg3) const {
        return m_jniObject.callMethod<jobject>(
                        "openOrCreateDatabase",
                        "(Ljava/lang/String;ILandroid/database/sqlite/SQLiteDatabase$CursorFactory;Landroid/database/DatabaseErrorHandler;)Landroid/database/sqlite/SQLiteDatabase;", arg0, arg1, arg2, arg3);
    }


    // method: public abstract boolean moveDatabaseFrom(android.content.Context arg0, java.lang.String arg1)
    auto moveDatabaseFrom(jobject arg0, jstring arg1) const {
        return m_jniObject.callMethod<jboolean>(
                        "moveDatabaseFrom",
                        "(Landroid/content/Context;Ljava/lang/String;)Z", arg0, arg1);
    }


    // method: public abstract boolean deleteDatabase(java.lang.String arg0)
    auto deleteDatabase(jstring arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "deleteDatabase",
                        "(Ljava/lang/String;)Z", arg0);
    }


    // method: public abstract java.io.File getDatabasePath(java.lang.String arg0)
    auto getDatabasePath(jstring arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "getDatabasePath",
                        "(Ljava/lang/String;)Ljava/io/File;", arg0);
    }


    // method: public abstract java.lang.String[] databaseList()
    auto databaseList() const {
        return m_jniObject.callMethod<jobjectArray>(
                        "databaseList",
                        "()[Ljava/lang/String;");
    }


    // method: public abstract android.graphics.drawable.Drawable getWallpaper()
    auto getWallpaper() const {
        return m_jniObject.callMethod<jobject>(
                        "getWallpaper",
                        "()Landroid/graphics/drawable/Drawable;");
    }


    // method: public abstract android.graphics.drawable.Drawable peekWallpaper()
    auto peekWallpaper() const {
        return m_jniObject.callMethod<jobject>(
                        "peekWallpaper",
                        "()Landroid/graphics/drawable/Drawable;");
    }


    // method: public abstract int getWallpaperDesiredMinimumWidth()
    auto getWallpaperDesiredMinimumWidth() const {
        return m_jniObject.callMethod<jint>(
                        "getWallpaperDesiredMinimumWidth",
                        "()I");
    }


    // method: public abstract int getWallpaperDesiredMinimumHeight()
    auto getWallpaperDesiredMinimumHeight() const {
        return m_jniObject.callMethod<jint>(
                        "getWallpaperDesiredMinimumHeight",
                        "()I");
    }


    // method: public abstract void setWallpaper(android.graphics.Bitmap arg0)
    auto setWallpaper__Landroid_graphics_Bitmap_2(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "setWallpaper",
                        "(Landroid/graphics/Bitmap;)V", arg0);
    }


    // method: public abstract void setWallpaper(java.io.InputStream arg0)
    auto setWallpaper__Ljava_io_InputStream_2(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "setWallpaper",
                        "(Ljava/io/InputStream;)V", arg0);
    }


    // method: public abstract void clearWallpaper()
    auto clearWallpaper() const {
        m_jniObject.callMethod<void>(
                        "clearWallpaper",
                        "()V");
    }


    // method: public abstract void startActivity(android.content.Intent arg0)
    auto startActivity(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "startActivity",
                        "(Landroid/content/Intent;)V", arg0);
    }


    // method: public abstract void startActivity(android.content.Intent arg0, android.os.Bundle arg1)
    auto startActivity(jobject arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "startActivity",
                        "(Landroid/content/Intent;Landroid/os/Bundle;)V", arg0, arg1);
    }


    // method: public abstract void startActivities(android.content.Intent[] arg0)
    auto startActivities(jobjectArray arg0) const {
        m_jniObject.callMethod<void>(
                        "startActivities",
                        "([Landroid/content/Intent;)V", arg0);
    }


    // method: public abstract void startActivities(android.content.Intent[] arg0, android.os.Bundle arg1)
    auto startActivities(jobjectArray arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "startActivities",
                        "([Landroid/content/Intent;Landroid/os/Bundle;)V", arg0, arg1);
    }


    // method: public abstract void startIntentSender(android.content.IntentSender arg0, android.content.Intent arg1, int arg2, int arg3, int arg4)
    auto startIntentSender(jobject arg0, jobject arg1, jint arg2, jint arg3, jint arg4) const {
        m_jniObject.callMethod<void>(
                        "startIntentSender",
                        "(Landroid/content/IntentSender;Landroid/content/Intent;III)V", arg0, arg1, arg2, arg3, arg4);
    }


    // method: public abstract void startIntentSender(android.content.IntentSender arg0, android.content.Intent arg1, int arg2, int arg3, int arg4, android.os.Bundle arg5)
    auto startIntentSender(jobject arg0, jobject arg1, jint arg2, jint arg3, jint arg4, jobject arg5) const {
        m_jniObject.callMethod<void>(
                        "startIntentSender",
                        "(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", arg0, arg1, arg2, arg3, arg4, arg5);
    }


    // method: public abstract void sendBroadcast(android.content.Intent arg0)
    auto sendBroadcast(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "sendBroadcast",
                        "(Landroid/content/Intent;)V", arg0);
    }


    // method: public abstract void sendBroadcast(android.content.Intent arg0, java.lang.String arg1)
    auto sendBroadcast(jobject arg0, jstring arg1) const {
        m_jniObject.callMethod<void>(
                        "sendBroadcast",
                        "(Landroid/content/Intent;Ljava/lang/String;)V", arg0, arg1);
    }


    // method: public void sendBroadcast(android.content.Intent intent, java.lang.String receiverPermission, android.os.Bundle options)
    auto sendBroadcast(jobject intent, jstring receiverPermission, jobject options) const {
        m_jniObject.callMethod<void>(
                        "sendBroadcast",
                        "(Landroid/content/Intent;Ljava/lang/String;Landroid/os/Bundle;)V", intent, receiverPermission, options);
    }


    // method: public void sendBroadcastWithMultiplePermissions(android.content.Intent intent, java.lang.String[] receiverPermissions)
    auto sendBroadcastWithMultiplePermissions(jobject intent, jobjectArray receiverPermissions) const {
        m_jniObject.callMethod<void>(
                        "sendBroadcastWithMultiplePermissions",
                        "(Landroid/content/Intent;[Ljava/lang/String;)V", intent, receiverPermissions);
    }


    // method: public abstract void sendOrderedBroadcast(android.content.Intent arg0, java.lang.String arg1)
    auto sendOrderedBroadcast(jobject arg0, jstring arg1) const {
        m_jniObject.callMethod<void>(
                        "sendOrderedBroadcast",
                        "(Landroid/content/Intent;Ljava/lang/String;)V", arg0, arg1);
    }


    // method: public void sendOrderedBroadcast(android.content.Intent intent, java.lang.String receiverPermission, android.os.Bundle options)
    auto sendOrderedBroadcast(jobject intent, jstring receiverPermission, jobject options) const {
        m_jniObject.callMethod<void>(
                        "sendOrderedBroadcast",
                        "(Landroid/content/Intent;Ljava/lang/String;Landroid/os/Bundle;)V", intent, receiverPermission, options);
    }


    // method: public abstract void sendOrderedBroadcast(android.content.Intent arg0, java.lang.String arg1, android.content.BroadcastReceiver arg2, android.os.Handler arg3, int arg4, java.lang.String arg5, android.os.Bundle arg6)
    auto sendOrderedBroadcast(jobject arg0, jstring arg1, jobject arg2, jobject arg3, jint arg4, jstring arg5, jobject arg6) const {
        m_jniObject.callMethod<void>(
                        "sendOrderedBroadcast",
                        "(Landroid/content/Intent;Ljava/lang/String;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V", arg0, arg1, arg2, arg3, arg4, arg5, arg6);
    }


    // method: public void sendOrderedBroadcast(android.content.Intent intent, java.lang.String receiverPermission, android.os.Bundle options, android.content.BroadcastReceiver resultReceiver, android.os.Handler scheduler, int initialCode, java.lang.String initialData, android.os.Bundle initialExtras)
    auto sendOrderedBroadcast(jobject intent, jstring receiverPermission, jobject options, jobject resultReceiver, jobject scheduler, jint initialCode, jstring initialData, jobject initialExtras) const {
        m_jniObject.callMethod<void>(
                        "sendOrderedBroadcast",
                        "(Landroid/content/Intent;Ljava/lang/String;Landroid/os/Bundle;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V", intent, receiverPermission, options, resultReceiver, scheduler, initialCode, initialData, initialExtras);
    }


    // method: public void sendOrderedBroadcast(android.content.Intent intent, java.lang.String receiverPermission, java.lang.String receiverAppOp, android.content.BroadcastReceiver resultReceiver, android.os.Handler scheduler, int initialCode, java.lang.String initialData, android.os.Bundle initialExtras)
    auto sendOrderedBroadcast(jobject intent, jstring receiverPermission, jstring receiverAppOp, jobject resultReceiver, jobject scheduler, jint initialCode, jstring initialData, jobject initialExtras) const {
        m_jniObject.callMethod<void>(
                        "sendOrderedBroadcast",
                        "(Landroid/content/Intent;Ljava/lang/String;Ljava/lang/String;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V", intent, receiverPermission, receiverAppOp, resultReceiver, scheduler, initialCode, initialData, initialExtras);
    }


    // method: public abstract void sendBroadcastAsUser(android.content.Intent arg0, android.os.UserHandle arg1)
    auto sendBroadcastAsUser(jobject arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "sendBroadcastAsUser",
                        "(Landroid/content/Intent;Landroid/os/UserHandle;)V", arg0, arg1);
    }


    // method: public abstract void sendBroadcastAsUser(android.content.Intent arg0, android.os.UserHandle arg1, java.lang.String arg2)
    auto sendBroadcastAsUser(jobject arg0, jobject arg1, jstring arg2) const {
        m_jniObject.callMethod<void>(
                        "sendBroadcastAsUser",
                        "(Landroid/content/Intent;Landroid/os/UserHandle;Ljava/lang/String;)V", arg0, arg1, arg2);
    }


    // method: public abstract void sendOrderedBroadcastAsUser(android.content.Intent arg0, android.os.UserHandle arg1, java.lang.String arg2, android.content.BroadcastReceiver arg3, android.os.Handler arg4, int arg5, java.lang.String arg6, android.os.Bundle arg7)
    auto sendOrderedBroadcastAsUser(jobject arg0, jobject arg1, jstring arg2, jobject arg3, jobject arg4, jint arg5, jstring arg6, jobject arg7) const {
        m_jniObject.callMethod<void>(
                        "sendOrderedBroadcastAsUser",
                        "(Landroid/content/Intent;Landroid/os/UserHandle;Ljava/lang/String;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7);
    }


    // method: public abstract void sendStickyBroadcast(android.content.Intent arg0)
    auto sendStickyBroadcast(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "sendStickyBroadcast",
                        "(Landroid/content/Intent;)V", arg0);
    }


    // method: public void sendStickyBroadcast(android.content.Intent intent, android.os.Bundle options)
    auto sendStickyBroadcast(jobject intent, jobject options) const {
        m_jniObject.callMethod<void>(
                        "sendStickyBroadcast",
                        "(Landroid/content/Intent;Landroid/os/Bundle;)V", intent, options);
    }


    // method: public abstract void sendStickyOrderedBroadcast(android.content.Intent arg0, android.content.BroadcastReceiver arg1, android.os.Handler arg2, int arg3, java.lang.String arg4, android.os.Bundle arg5)
    auto sendStickyOrderedBroadcast(jobject arg0, jobject arg1, jobject arg2, jint arg3, jstring arg4, jobject arg5) const {
        m_jniObject.callMethod<void>(
                        "sendStickyOrderedBroadcast",
                        "(Landroid/content/Intent;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V", arg0, arg1, arg2, arg3, arg4, arg5);
    }


    // method: public abstract void removeStickyBroadcast(android.content.Intent arg0)
    auto removeStickyBroadcast(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "removeStickyBroadcast",
                        "(Landroid/content/Intent;)V", arg0);
    }


    // method: public abstract void sendStickyBroadcastAsUser(android.content.Intent arg0, android.os.UserHandle arg1)
    auto sendStickyBroadcastAsUser(jobject arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "sendStickyBroadcastAsUser",
                        "(Landroid/content/Intent;Landroid/os/UserHandle;)V", arg0, arg1);
    }


    // method: public abstract void sendStickyOrderedBroadcastAsUser(android.content.Intent arg0, android.os.UserHandle arg1, android.content.BroadcastReceiver arg2, android.os.Handler arg3, int arg4, java.lang.String arg5, android.os.Bundle arg6)
    auto sendStickyOrderedBroadcastAsUser(jobject arg0, jobject arg1, jobject arg2, jobject arg3, jint arg4, jstring arg5, jobject arg6) const {
        m_jniObject.callMethod<void>(
                        "sendStickyOrderedBroadcastAsUser",
                        "(Landroid/content/Intent;Landroid/os/UserHandle;Landroid/content/BroadcastReceiver;Landroid/os/Handler;ILjava/lang/String;Landroid/os/Bundle;)V", arg0, arg1, arg2, arg3, arg4, arg5, arg6);
    }


    // method: public abstract void removeStickyBroadcastAsUser(android.content.Intent arg0, android.os.UserHandle arg1)
    auto removeStickyBroadcastAsUser(jobject arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "removeStickyBroadcastAsUser",
                        "(Landroid/content/Intent;Landroid/os/UserHandle;)V", arg0, arg1);
    }


    // method: public abstract android.content.Intent registerReceiver(android.content.BroadcastReceiver arg0, android.content.IntentFilter arg1)
    auto registerReceiver(jobject arg0, jobject arg1) const {
        return m_jniObject.callMethod<jobject>(
                        "registerReceiver",
                        "(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;)Landroid/content/Intent;", arg0, arg1);
    }


    // method: public abstract android.content.Intent registerReceiver(android.content.BroadcastReceiver arg0, android.content.IntentFilter arg1, int arg2)
    auto registerReceiver(jobject arg0, jobject arg1, jint arg2) const {
        return m_jniObject.callMethod<jobject>(
                        "registerReceiver",
                        "(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;I)Landroid/content/Intent;", arg0, arg1, arg2);
    }


    // method: public abstract android.content.Intent registerReceiver(android.content.BroadcastReceiver arg0, android.content.IntentFilter arg1, java.lang.String arg2, android.os.Handler arg3)
    auto registerReceiver(jobject arg0, jobject arg1, jstring arg2, jobject arg3) const {
        return m_jniObject.callMethod<jobject>(
                        "registerReceiver",
                        "(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;Ljava/lang/String;Landroid/os/Handler;)Landroid/content/Intent;", arg0, arg1, arg2, arg3);
    }


    // method: public abstract android.content.Intent registerReceiver(android.content.BroadcastReceiver arg0, android.content.IntentFilter arg1, java.lang.String arg2, android.os.Handler arg3, int arg4)
    auto registerReceiver(jobject arg0, jobject arg1, jstring arg2, jobject arg3, jint arg4) const {
        return m_jniObject.callMethod<jobject>(
                        "registerReceiver",
                        "(Landroid/content/BroadcastReceiver;Landroid/content/IntentFilter;Ljava/lang/String;Landroid/os/Handler;I)Landroid/content/Intent;", arg0, arg1, arg2, arg3, arg4);
    }


    // method: public abstract void unregisterReceiver(android.content.BroadcastReceiver arg0)
    auto unregisterReceiver(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "unregisterReceiver",
                        "(Landroid/content/BroadcastReceiver;)V", arg0);
    }


    // method: public abstract android.content.ComponentName startService(android.content.Intent arg0)
    auto startService(jobject arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "startService",
                        "(Landroid/content/Intent;)Landroid/content/ComponentName;", arg0);
    }


    // method: public abstract android.content.ComponentName startForegroundService(android.content.Intent arg0)
    auto startForegroundService(jobject arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "startForegroundService",
                        "(Landroid/content/Intent;)Landroid/content/ComponentName;", arg0);
    }


    // method: public abstract boolean stopService(android.content.Intent arg0)
    auto stopService(jobject arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "stopService",
                        "(Landroid/content/Intent;)Z", arg0);
    }


    // method: public abstract boolean bindService(android.content.Intent arg0, android.content.ServiceConnection arg1, int arg2)
    auto bindService(jobject arg0, jobject arg1, jint arg2) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindService",
                        "(Landroid/content/Intent;Landroid/content/ServiceConnection;I)Z", arg0, arg1, arg2);
    }


    // method: public boolean bindService(android.content.Intent service, android.content.ServiceConnection conn, android.content.Context.BindServiceFlags flags)
    auto bindService(jobject service, jobject conn, jobject flags) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindService",
                        "(Landroid/content/Intent;Landroid/content/ServiceConnection;Landroid/content/Context$BindServiceFlags;)Z", service, conn, flags);
    }


    // method: public boolean bindService(android.content.Intent service, int flags, java.util.concurrent.Executor executor, android.content.ServiceConnection conn)
    auto bindService(jobject service, jint flags, jobject executor, jobject conn) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindService",
                        "(Landroid/content/Intent;ILjava/util/concurrent/Executor;Landroid/content/ServiceConnection;)Z", service, flags, executor, conn);
    }


    // method: public boolean bindService(android.content.Intent service, android.content.Context.BindServiceFlags flags, java.util.concurrent.Executor executor, android.content.ServiceConnection conn)
    auto bindService(jobject service, jobject flags, jobject executor, jobject conn) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindService",
                        "(Landroid/content/Intent;Landroid/content/Context$BindServiceFlags;Ljava/util/concurrent/Executor;Landroid/content/ServiceConnection;)Z", service, flags, executor, conn);
    }


    // method: public boolean bindIsolatedService(android.content.Intent service, int flags, java.lang.String instanceName, java.util.concurrent.Executor executor, android.content.ServiceConnection conn)
    auto bindIsolatedService(jobject service, jint flags, jstring instanceName, jobject executor, jobject conn) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindIsolatedService",
                        "(Landroid/content/Intent;ILjava/lang/String;Ljava/util/concurrent/Executor;Landroid/content/ServiceConnection;)Z", service, flags, instanceName, executor, conn);
    }


    // method: public boolean bindIsolatedService(android.content.Intent service, android.content.Context.BindServiceFlags flags, java.lang.String instanceName, java.util.concurrent.Executor executor, android.content.ServiceConnection conn)
    auto bindIsolatedService(jobject service, jobject flags, jstring instanceName, jobject executor, jobject conn) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindIsolatedService",
                        "(Landroid/content/Intent;Landroid/content/Context$BindServiceFlags;Ljava/lang/String;Ljava/util/concurrent/Executor;Landroid/content/ServiceConnection;)Z", service, flags, instanceName, executor, conn);
    }


    // method: public boolean bindServiceAsUser(android.content.Intent service, android.content.ServiceConnection conn, int flags, android.os.UserHandle user)
    auto bindServiceAsUser(jobject service, jobject conn, jint flags, jobject user) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindServiceAsUser",
                        "(Landroid/content/Intent;Landroid/content/ServiceConnection;ILandroid/os/UserHandle;)Z", service, conn, flags, user);
    }


    // method: public boolean bindServiceAsUser(android.content.Intent service, android.content.ServiceConnection conn, android.content.Context.BindServiceFlags flags, android.os.UserHandle user)
    auto bindServiceAsUser(jobject service, jobject conn, jobject flags, jobject user) const {
        return m_jniObject.callMethod<jboolean>(
                        "bindServiceAsUser",
                        "(Landroid/content/Intent;Landroid/content/ServiceConnection;Landroid/content/Context$BindServiceFlags;Landroid/os/UserHandle;)Z", service, conn, flags, user);
    }


    // method: public void updateServiceGroup(android.content.ServiceConnection conn, int group, int importance)
    auto updateServiceGroup(jobject conn, jint group, jint importance) const {
        m_jniObject.callMethod<void>(
                        "updateServiceGroup",
                        "(Landroid/content/ServiceConnection;II)V", conn, group, importance);
    }


    // method: public abstract void unbindService(android.content.ServiceConnection arg0)
    auto unbindService(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "unbindService",
                        "(Landroid/content/ServiceConnection;)V", arg0);
    }


    // method: public abstract boolean startInstrumentation(android.content.ComponentName arg0, java.lang.String arg1, android.os.Bundle arg2)
    auto startInstrumentation(jobject arg0, jstring arg1, jobject arg2) const {
        return m_jniObject.callMethod<jboolean>(
                        "startInstrumentation",
                        "(Landroid/content/ComponentName;Ljava/lang/String;Landroid/os/Bundle;)Z", arg0, arg1, arg2);
    }


    // method: public abstract java.lang.Object getSystemService(java.lang.String arg0)
    auto getSystemService(jstring arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "getSystemService",
                        "(Ljava/lang/String;)Ljava/lang/Object;", arg0);
    }


    // method: public final T getSystemService(java.lang.Class<T> serviceClass)
    auto getSystemService(jclass serviceClass) const {
        return m_jniObject.callMethod<jobject>(
                        "getSystemService",
                        "(Ljava/lang/Class;)Ljava/lang/Object;", serviceClass);
    }


    // method: public abstract java.lang.String getSystemServiceName(java.lang.Class<?> arg0)
    auto getSystemServiceName(jclass arg0) const {
        return m_jniObject.callMethod<jstring>(
                        "getSystemServiceName",
                        "(Ljava/lang/Class;)Ljava/lang/String;", arg0);
    }


    // method: public abstract int checkPermission(java.lang.String arg0, int arg1, int arg2)
    auto checkPermission(jstring arg0, jint arg1, jint arg2) const {
        return m_jniObject.callMethod<jint>(
                        "checkPermission",
                        "(Ljava/lang/String;II)I", arg0, arg1, arg2);
    }


    // method: public abstract int checkCallingPermission(java.lang.String arg0)
    auto checkCallingPermission(jstring arg0) const {
        return m_jniObject.callMethod<jint>(
                        "checkCallingPermission",
                        "(Ljava/lang/String;)I", arg0);
    }


    // method: public abstract int checkCallingOrSelfPermission(java.lang.String arg0)
    auto checkCallingOrSelfPermission(jstring arg0) const {
        return m_jniObject.callMethod<jint>(
                        "checkCallingOrSelfPermission",
                        "(Ljava/lang/String;)I", arg0);
    }


    // method: public abstract int checkSelfPermission(java.lang.String arg0)
    auto checkSelfPermission(jstring arg0) const {
        return m_jniObject.callMethod<jint>(
                        "checkSelfPermission",
                        "(Ljava/lang/String;)I", arg0);
    }


    // method: public abstract void enforcePermission(java.lang.String arg0, int arg1, int arg2, java.lang.String arg3)
    auto enforcePermission(jstring arg0, jint arg1, jint arg2, jstring arg3) const {
        m_jniObject.callMethod<void>(
                        "enforcePermission",
                        "(Ljava/lang/String;IILjava/lang/String;)V", arg0, arg1, arg2, arg3);
    }


    // method: public abstract void enforceCallingPermission(java.lang.String arg0, java.lang.String arg1)
    auto enforceCallingPermission(jstring arg0, jstring arg1) const {
        m_jniObject.callMethod<void>(
                        "enforceCallingPermission",
                        "(Ljava/lang/String;Ljava/lang/String;)V", arg0, arg1);
    }


    // method: public abstract void enforceCallingOrSelfPermission(java.lang.String arg0, java.lang.String arg1)
    auto enforceCallingOrSelfPermission(jstring arg0, jstring arg1) const {
        m_jniObject.callMethod<void>(
                        "enforceCallingOrSelfPermission",
                        "(Ljava/lang/String;Ljava/lang/String;)V", arg0, arg1);
    }


    // method: public abstract void grantUriPermission(java.lang.String arg0, android.net.Uri arg1, int arg2)
    auto grantUriPermission(jstring arg0, jobject arg1, jint arg2) const {
        m_jniObject.callMethod<void>(
                        "grantUriPermission",
                        "(Ljava/lang/String;Landroid/net/Uri;I)V", arg0, arg1, arg2);
    }


    // method: public abstract void revokeUriPermission(android.net.Uri arg0, int arg1)
    auto revokeUriPermission(jobject arg0, jint arg1) const {
        m_jniObject.callMethod<void>(
                        "revokeUriPermission",
                        "(Landroid/net/Uri;I)V", arg0, arg1);
    }


    // method: public abstract void revokeUriPermission(java.lang.String arg0, android.net.Uri arg1, int arg2)
    auto revokeUriPermission(jstring arg0, jobject arg1, jint arg2) const {
        m_jniObject.callMethod<void>(
                        "revokeUriPermission",
                        "(Ljava/lang/String;Landroid/net/Uri;I)V", arg0, arg1, arg2);
    }


    // method: public abstract int checkUriPermission(android.net.Uri arg0, int arg1, int arg2, int arg3)
    auto checkUriPermission(jobject arg0, jint arg1, jint arg2, jint arg3) const {
        return m_jniObject.callMethod<jint>(
                        "checkUriPermission",
                        "(Landroid/net/Uri;III)I", arg0, arg1, arg2, arg3);
    }


    // method: public abstract int checkUriPermission(android.net.Uri arg0, java.lang.String arg1, java.lang.String arg2, int arg3, int arg4, int arg5)
    auto checkUriPermission(jobject arg0, jstring arg1, jstring arg2, jint arg3, jint arg4, jint arg5) const {
        return m_jniObject.callMethod<jint>(
                        "checkUriPermission",
                        "(Landroid/net/Uri;Ljava/lang/String;Ljava/lang/String;III)I", arg0, arg1, arg2, arg3, arg4, arg5);
    }


    // method: public int checkContentUriPermissionFull(android.net.Uri uri, int pid, int uid, int modeFlags)
    auto checkContentUriPermissionFull(jobject uri, jint pid, jint uid, jint modeFlags) const {
        return m_jniObject.callMethod<jint>(
                        "checkContentUriPermissionFull",
                        "(Landroid/net/Uri;III)I", uri, pid, uid, modeFlags);
    }


    // method: public int[] checkUriPermissions(java.util.List<android.net.Uri> uris, int pid, int uid, int modeFlags)
    auto checkUriPermissions(jobject uris, jint pid, jint uid, jint modeFlags) const {
        return m_jniObject.callMethod<jintArray>(
                        "checkUriPermissions",
                        "(Ljava/util/List;III)[I", uris, pid, uid, modeFlags);
    }


    // method: public abstract int checkCallingUriPermission(android.net.Uri arg0, int arg1)
    auto checkCallingUriPermission(jobject arg0, jint arg1) const {
        return m_jniObject.callMethod<jint>(
                        "checkCallingUriPermission",
                        "(Landroid/net/Uri;I)I", arg0, arg1);
    }


    // method: public int[] checkCallingUriPermissions(java.util.List<android.net.Uri> uris, int modeFlags)
    auto checkCallingUriPermissions(jobject uris, jint modeFlags) const {
        return m_jniObject.callMethod<jintArray>(
                        "checkCallingUriPermissions",
                        "(Ljava/util/List;I)[I", uris, modeFlags);
    }


    // method: public abstract int checkCallingOrSelfUriPermission(android.net.Uri arg0, int arg1)
    auto checkCallingOrSelfUriPermission(jobject arg0, jint arg1) const {
        return m_jniObject.callMethod<jint>(
                        "checkCallingOrSelfUriPermission",
                        "(Landroid/net/Uri;I)I", arg0, arg1);
    }


    // method: public int[] checkCallingOrSelfUriPermissions(java.util.List<android.net.Uri> uris, int modeFlags)
    auto checkCallingOrSelfUriPermissions(jobject uris, jint modeFlags) const {
        return m_jniObject.callMethod<jintArray>(
                        "checkCallingOrSelfUriPermissions",
                        "(Ljava/util/List;I)[I", uris, modeFlags);
    }


    // method: public abstract void enforceUriPermission(android.net.Uri arg0, int arg1, int arg2, int arg3, java.lang.String arg4)
    auto enforceUriPermission(jobject arg0, jint arg1, jint arg2, jint arg3, jstring arg4) const {
        m_jniObject.callMethod<void>(
                        "enforceUriPermission",
                        "(Landroid/net/Uri;IIILjava/lang/String;)V", arg0, arg1, arg2, arg3, arg4);
    }


    // method: public abstract void enforceUriPermission(android.net.Uri arg0, java.lang.String arg1, java.lang.String arg2, int arg3, int arg4, int arg5, java.lang.String arg6)
    auto enforceUriPermission(jobject arg0, jstring arg1, jstring arg2, jint arg3, jint arg4, jint arg5, jstring arg6) const {
        m_jniObject.callMethod<void>(
                        "enforceUriPermission",
                        "(Landroid/net/Uri;Ljava/lang/String;Ljava/lang/String;IIILjava/lang/String;)V", arg0, arg1, arg2, arg3, arg4, arg5, arg6);
    }


    // method: public abstract void enforceCallingUriPermission(android.net.Uri arg0, int arg1, java.lang.String arg2)
    auto enforceCallingUriPermission(jobject arg0, jint arg1, jstring arg2) const {
        m_jniObject.callMethod<void>(
                        "enforceCallingUriPermission",
                        "(Landroid/net/Uri;ILjava/lang/String;)V", arg0, arg1, arg2);
    }


    // method: public abstract void enforceCallingOrSelfUriPermission(android.net.Uri arg0, int arg1, java.lang.String arg2)
    auto enforceCallingOrSelfUriPermission(jobject arg0, jint arg1, jstring arg2) const {
        m_jniObject.callMethod<void>(
                        "enforceCallingOrSelfUriPermission",
                        "(Landroid/net/Uri;ILjava/lang/String;)V", arg0, arg1, arg2);
    }


    // method: public void revokeSelfPermissionOnKill(java.lang.String permName)
    auto revokeSelfPermissionOnKill(jstring permName) const {
        m_jniObject.callMethod<void>(
                        "revokeSelfPermissionOnKill",
                        "(Ljava/lang/String;)V", permName);
    }


    // method: public void revokeSelfPermissionsOnKill(java.util.Collection<java.lang.String> permissions)
    auto revokeSelfPermissionsOnKill(jobject permissions) const {
        m_jniObject.callMethod<void>(
                        "revokeSelfPermissionsOnKill",
                        "(Ljava/util/Collection;)V", permissions);
    }


    // method: public abstract android.content.Context createPackageContext(java.lang.String arg0, int arg1)
    auto createPackageContext(jstring arg0, jint arg1) const {
        return m_jniObject.callMethod<jobject>(
                        "createPackageContext",
                        "(Ljava/lang/String;I)Landroid/content/Context;", arg0, arg1);
    }


    // method: public abstract android.content.Context createContextForSplit(java.lang.String arg0)
    auto createContextForSplit(jstring arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "createContextForSplit",
                        "(Ljava/lang/String;)Landroid/content/Context;", arg0);
    }


    // method: public abstract android.content.Context createConfigurationContext(android.content.res.Configuration arg0)
    auto createConfigurationContext(jobject arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "createConfigurationContext",
                        "(Landroid/content/res/Configuration;)Landroid/content/Context;", arg0);
    }


    // method: public abstract android.content.Context createDisplayContext(android.view.Display arg0)
    auto createDisplayContext(jobject arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "createDisplayContext",
                        "(Landroid/view/Display;)Landroid/content/Context;", arg0);
    }


    // method: public android.content.Context createDeviceContext(int deviceId)
    auto createDeviceContext(jint deviceId) const {
        return m_jniObject.callMethod<jobject>(
                        "createDeviceContext",
                        "(I)Landroid/content/Context;", deviceId);
    }


    // method: public android.content.Context createWindowContext(int type, android.os.Bundle options)
    auto createWindowContext(jint type, jobject options) const {
        return m_jniObject.callMethod<jobject>(
                        "createWindowContext",
                        "(ILandroid/os/Bundle;)Landroid/content/Context;", type, options);
    }


    // method: public android.content.Context createWindowContext(android.view.Display display, int type, android.os.Bundle options)
    auto createWindowContext(jobject display, jint type, jobject options) const {
        return m_jniObject.callMethod<jobject>(
                        "createWindowContext",
                        "(Landroid/view/Display;ILandroid/os/Bundle;)Landroid/content/Context;", display, type, options);
    }


    // method: public android.content.Context createContext(android.content.ContextParams contextParams)
    auto createContext(jobject contextParams) const {
        return m_jniObject.callMethod<jobject>(
                        "createContext",
                        "(Landroid/content/ContextParams;)Landroid/content/Context;", contextParams);
    }


    // method: public android.content.Context createAttributionContext(java.lang.String attributionTag)
    auto createAttributionContext(jstring attributionTag) const {
        return m_jniObject.callMethod<jobject>(
                        "createAttributionContext",
                        "(Ljava/lang/String;)Landroid/content/Context;", attributionTag);
    }


    // method: public abstract android.content.Context createDeviceProtectedStorageContext()
    auto createDeviceProtectedStorageContext() const {
        return m_jniObject.callMethod<jobject>(
                        "createDeviceProtectedStorageContext",
                        "()Landroid/content/Context;");
    }


    // method: public android.view.Display getDisplay()
    auto getDisplay() const {
        return m_jniObject.callMethod<jobject>(
                        "getDisplay",
                        "()Landroid/view/Display;");
    }


    // method: public int getDeviceId()
    auto getDeviceId() const {
        return m_jniObject.callMethod<jint>(
                        "getDeviceId",
                        "()I");
    }


    // method: public void registerDeviceIdChangeListener(java.util.concurrent.Executor executor, java.util.function.IntConsumer listener)
    auto registerDeviceIdChangeListener(jobject executor, jobject listener) const {
        m_jniObject.callMethod<void>(
                        "registerDeviceIdChangeListener",
                        "(Ljava/util/concurrent/Executor;Ljava/util/function/IntConsumer;)V", executor, listener);
    }


    // method: public void unregisterDeviceIdChangeListener(java.util.function.IntConsumer listener)
    auto unregisterDeviceIdChangeListener(jobject listener) const {
        m_jniObject.callMethod<void>(
                        "unregisterDeviceIdChangeListener",
                        "(Ljava/util/function/IntConsumer;)V", listener);
    }


    // method: public boolean isRestricted()
    auto isRestricted() const {
        return m_jniObject.callMethod<jboolean>(
                        "isRestricted",
                        "()Z");
    }


    // method: public abstract boolean isDeviceProtectedStorage()
    auto isDeviceProtectedStorage() const {
        return m_jniObject.callMethod<jboolean>(
                        "isDeviceProtectedStorage",
                        "()Z");
    }


    // method: public boolean isUiContext()
    auto isUiContext() const {
        return m_jniObject.callMethod<jboolean>(
                        "isUiContext",
                        "()Z");
    }


};
} } // endof namespace android::os


namespace android { namespace os {


} } // endof namespace android::os

#endif // android_os_ContextProxy_H

