
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_os_VibratorManagerProxy_H
#define android_os_VibratorManagerProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace os {
class VibratorManagerProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/os/VibratorManager";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    VibratorManagerProxy() {}
    VibratorManagerProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    VibratorManagerProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static VibratorManagerProxy fromLocalRef(jobject localRef) {
        VibratorManagerProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }



    // method: public abstract int[] getVibratorIds()
    auto getVibratorIds() const {
        return m_jniObject.callMethod<jintArray>(
                        "getVibratorIds",
                        "()[I");
    }


    // method: public abstract android.os.Vibrator getVibrator(int arg0)
    auto getVibrator(jint arg0) const {
        return m_jniObject.callMethod<jobject>(
                        "getVibrator",
                        "(I)Landroid/os/Vibrator;", arg0);
    }


    // method: public abstract android.os.Vibrator getDefaultVibrator()
    auto getDefaultVibrator() const {
        return m_jniObject.callMethod<jobject>(
                        "getDefaultVibrator",
                        "()Landroid/os/Vibrator;");
    }


    // method: public final void vibrate(android.os.CombinedVibration effect)
    auto vibrate(jobject effect) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "(Landroid/os/CombinedVibration;)V", effect);
    }


    // method: public final void vibrate(android.os.CombinedVibration effect, android.os.VibrationAttributes attributes)
    auto vibrate(jobject effect, jobject attributes) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "(Landroid/os/CombinedVibration;Landroid/os/VibrationAttributes;)V", effect, attributes);
    }


    // method: public abstract void cancel()
    auto cancel() const {
        m_jniObject.callMethod<void>(
                        "cancel",
                        "()V");
    }


};
} } // endof namespace android::os


namespace android { namespace os {


} } // endof namespace android::os

#endif // android_os_VibratorManagerProxy_H

