
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_app_NotificationManagerProxy_H
#define android_app_NotificationManagerProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace app {
class NotificationManagerProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/app/NotificationManager";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    NotificationManagerProxy() {}
    NotificationManagerProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    NotificationManagerProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static NotificationManagerProxy fromLocalRef(jobject localRef) {
        NotificationManagerProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr auto ACTION_APP_BLOCK_STATE_CHANGED = u8"android.app.action.APP_BLOCK_STATE_CHANGED";
    static constexpr auto ACTION_AUTOMATIC_ZEN_RULE = u8"android.app.action.AUTOMATIC_ZEN_RULE";
    static constexpr auto ACTION_AUTOMATIC_ZEN_RULE_STATUS_CHANGED = u8"android.app.action.AUTOMATIC_ZEN_RULE_STATUS_CHANGED";
    static constexpr auto ACTION_CONSOLIDATED_NOTIFICATION_POLICY_CHANGED = u8"android.app.action.CONSOLIDATED_NOTIFICATION_POLICY_CHANGED";
    static constexpr auto ACTION_INTERRUPTION_FILTER_CHANGED = u8"android.app.action.INTERRUPTION_FILTER_CHANGED";
    static constexpr auto ACTION_NOTIFICATION_CHANNEL_BLOCK_STATE_CHANGED = u8"android.app.action.NOTIFICATION_CHANNEL_BLOCK_STATE_CHANGED";
    static constexpr auto ACTION_NOTIFICATION_CHANNEL_GROUP_BLOCK_STATE_CHANGED = u8"android.app.action.NOTIFICATION_CHANNEL_GROUP_BLOCK_STATE_CHANGED";
    static constexpr auto ACTION_NOTIFICATION_POLICY_ACCESS_GRANTED_CHANGED = u8"android.app.action.NOTIFICATION_POLICY_ACCESS_GRANTED_CHANGED";
    static constexpr auto ACTION_NOTIFICATION_POLICY_CHANGED = u8"android.app.action.NOTIFICATION_POLICY_CHANGED";
    static constexpr jint AUTOMATIC_RULE_STATUS_ACTIVATED = 4;
    static constexpr jint AUTOMATIC_RULE_STATUS_DEACTIVATED = 5;
    static constexpr jint AUTOMATIC_RULE_STATUS_DISABLED = 2;
    static constexpr jint AUTOMATIC_RULE_STATUS_ENABLED = 1;
    static constexpr jint AUTOMATIC_RULE_STATUS_REMOVED = 3;
    static constexpr jint AUTOMATIC_RULE_STATUS_UNKNOWN = -1;
    static constexpr jint BUBBLE_PREFERENCE_ALL = 1;
    static constexpr jint BUBBLE_PREFERENCE_NONE = 0;
    static constexpr jint BUBBLE_PREFERENCE_SELECTED = 2;
    static constexpr auto EXTRA_AUTOMATIC_RULE_ID = u8"android.app.extra.AUTOMATIC_RULE_ID";
    static constexpr auto EXTRA_AUTOMATIC_ZEN_RULE_ID = u8"android.app.extra.AUTOMATIC_ZEN_RULE_ID";
    static constexpr auto EXTRA_AUTOMATIC_ZEN_RULE_STATUS = u8"android.app.extra.AUTOMATIC_ZEN_RULE_STATUS";
    static constexpr auto EXTRA_BLOCKED_STATE = u8"android.app.extra.BLOCKED_STATE";
    static constexpr auto EXTRA_NOTIFICATION_CHANNEL_GROUP_ID = u8"android.app.extra.NOTIFICATION_CHANNEL_GROUP_ID";
    static constexpr auto EXTRA_NOTIFICATION_CHANNEL_ID = u8"android.app.extra.NOTIFICATION_CHANNEL_ID";
    static constexpr auto EXTRA_NOTIFICATION_POLICY = u8"android.app.extra.NOTIFICATION_POLICY";
    static constexpr jint IMPORTANCE_DEFAULT = 3;
    static constexpr jint IMPORTANCE_HIGH = 4;
    static constexpr jint IMPORTANCE_LOW = 2;
    static constexpr jint IMPORTANCE_MAX = 5;
    static constexpr jint IMPORTANCE_MIN = 1;
    static constexpr jint IMPORTANCE_NONE = 0;
    static constexpr jint IMPORTANCE_UNSPECIFIED = -1000;
    static constexpr jint INTERRUPTION_FILTER_ALARMS = 4;
    static constexpr jint INTERRUPTION_FILTER_ALL = 1;
    static constexpr jint INTERRUPTION_FILTER_NONE = 3;
    static constexpr jint INTERRUPTION_FILTER_PRIORITY = 2;
    static constexpr jint INTERRUPTION_FILTER_UNKNOWN = 0;
    static constexpr auto META_DATA_AUTOMATIC_RULE_TYPE = u8"android.service.zen.automatic.ruleType";
    static constexpr auto META_DATA_RULE_INSTANCE_LIMIT = u8"android.service.zen.automatic.ruleInstanceLimit";


    // method: public void notify(int id, android.app.Notification notification)
    auto notify(jint id, jobject notification) const {
        m_jniObject.callMethod<void>(
                        "notify",
                        "(ILandroid/app/Notification;)V", id, notification);
    }


    // method: public void notify(java.lang.String tag, int id, android.app.Notification notification)
    auto notify(jstring tag, jint id, jobject notification) const {
        m_jniObject.callMethod<void>(
                        "notify",
                        "(Ljava/lang/String;ILandroid/app/Notification;)V", tag, id, notification);
    }


    // method: public void notifyAsPackage(java.lang.String targetPackage, java.lang.String tag, int id, android.app.Notification notification)
    auto notifyAsPackage(jstring targetPackage, jstring tag, jint id, jobject notification) const {
        m_jniObject.callMethod<void>(
                        "notifyAsPackage",
                        "(Ljava/lang/String;Ljava/lang/String;ILandroid/app/Notification;)V", targetPackage, tag, id, notification);
    }


    // method: public void cancel(int id)
    auto cancel(jint id) const {
        m_jniObject.callMethod<void>(
                        "cancel",
                        "(I)V", id);
    }


    // method: public void cancel(java.lang.String tag, int id)
    auto cancel(jstring tag, jint id) const {
        m_jniObject.callMethod<void>(
                        "cancel",
                        "(Ljava/lang/String;I)V", tag, id);
    }


    // method: public void cancelAsPackage(java.lang.String targetPackage, java.lang.String tag, int id)
    auto cancelAsPackage(jstring targetPackage, jstring tag, jint id) const {
        m_jniObject.callMethod<void>(
                        "cancelAsPackage",
                        "(Ljava/lang/String;Ljava/lang/String;I)V", targetPackage, tag, id);
    }


    // method: public void cancelAll()
    auto cancelAll() const {
        m_jniObject.callMethod<void>(
                        "cancelAll",
                        "()V");
    }


    // method: public void setNotificationDelegate(java.lang.String delegate)
    auto setNotificationDelegate(jstring delegate) const {
        m_jniObject.callMethod<void>(
                        "setNotificationDelegate",
                        "(Ljava/lang/String;)V", delegate);
    }


    // method: public java.lang.String getNotificationDelegate()
    auto getNotificationDelegate() const {
        return m_jniObject.callMethod<jstring>(
                        "getNotificationDelegate",
                        "()Ljava/lang/String;");
    }


    // method: public boolean canNotifyAsPackage(java.lang.String pkg)
    auto canNotifyAsPackage(jstring pkg) const {
        return m_jniObject.callMethod<jboolean>(
                        "canNotifyAsPackage",
                        "(Ljava/lang/String;)Z", pkg);
    }


    // method: public boolean canUseFullScreenIntent()
    auto canUseFullScreenIntent() const {
        return m_jniObject.callMethod<jboolean>(
                        "canUseFullScreenIntent",
                        "()Z");
    }


    // method: public void createNotificationChannelGroup(android.app.NotificationChannelGroup group)
    auto createNotificationChannelGroup(jobject group) const {
        m_jniObject.callMethod<void>(
                        "createNotificationChannelGroup",
                        "(Landroid/app/NotificationChannelGroup;)V", group);
    }


    // method: public void createNotificationChannelGroups(java.util.List<android.app.NotificationChannelGroup> groups)
    auto createNotificationChannelGroups(jobject groups) const {
        m_jniObject.callMethod<void>(
                        "createNotificationChannelGroups",
                        "(Ljava/util/List;)V", groups);
    }


    // method: public void createNotificationChannel(android.app.NotificationChannel channel)
    auto createNotificationChannel(jobject channel) const {
        m_jniObject.callMethod<void>(
                        "createNotificationChannel",
                        "(Landroid/app/NotificationChannel;)V", channel);
    }


    // method: public void createNotificationChannels(java.util.List<android.app.NotificationChannel> channels)
    auto createNotificationChannels(jobject channels) const {
        m_jniObject.callMethod<void>(
                        "createNotificationChannels",
                        "(Ljava/util/List;)V", channels);
    }


    // method: public android.app.NotificationChannel getNotificationChannel(java.lang.String channelId)
    auto getNotificationChannel(jstring channelId) const {
        return m_jniObject.callMethod<jobject>(
                        "getNotificationChannel",
                        "(Ljava/lang/String;)Landroid/app/NotificationChannel;", channelId);
    }


    // method: public android.app.NotificationChannel getNotificationChannel(java.lang.String channelId, java.lang.String conversationId)
    auto getNotificationChannel(jstring channelId, jstring conversationId) const {
        return m_jniObject.callMethod<jobject>(
                        "getNotificationChannel",
                        "(Ljava/lang/String;Ljava/lang/String;)Landroid/app/NotificationChannel;", channelId, conversationId);
    }


    // method: public java.util.List<android.app.NotificationChannel> getNotificationChannels()
    auto getNotificationChannels() const {
        return m_jniObject.callMethod<jobject>(
                        "getNotificationChannels",
                        "()Ljava/util/List;");
    }


    // method: public void deleteNotificationChannel(java.lang.String channelId)
    auto deleteNotificationChannel(jstring channelId) const {
        m_jniObject.callMethod<void>(
                        "deleteNotificationChannel",
                        "(Ljava/lang/String;)V", channelId);
    }


    // method: public android.app.NotificationChannelGroup getNotificationChannelGroup(java.lang.String channelGroupId)
    auto getNotificationChannelGroup(jstring channelGroupId) const {
        return m_jniObject.callMethod<jobject>(
                        "getNotificationChannelGroup",
                        "(Ljava/lang/String;)Landroid/app/NotificationChannelGroup;", channelGroupId);
    }


    // method: public java.util.List<android.app.NotificationChannelGroup> getNotificationChannelGroups()
    auto getNotificationChannelGroups() const {
        return m_jniObject.callMethod<jobject>(
                        "getNotificationChannelGroups",
                        "()Ljava/util/List;");
    }


    // method: public void deleteNotificationChannelGroup(java.lang.String groupId)
    auto deleteNotificationChannelGroup(jstring groupId) const {
        m_jniObject.callMethod<void>(
                        "deleteNotificationChannelGroup",
                        "(Ljava/lang/String;)V", groupId);
    }


    // method: public android.app.NotificationManager.Policy getConsolidatedNotificationPolicy()
    auto getConsolidatedNotificationPolicy() const {
        return m_jniObject.callMethod<jobject>(
                        "getConsolidatedNotificationPolicy",
                        "()Landroid/app/NotificationManager$Policy;");
    }


    // method: public boolean areAutomaticZenRulesUserManaged()
    auto areAutomaticZenRulesUserManaged() const {
        return m_jniObject.callMethod<jboolean>(
                        "areAutomaticZenRulesUserManaged",
                        "()Z");
    }


    // method: public java.util.Map<java.lang.String,android.app.AutomaticZenRule> getAutomaticZenRules()
    auto getAutomaticZenRules() const {
        return m_jniObject.callMethod<jobject>(
                        "getAutomaticZenRules",
                        "()Ljava/util/Map;");
    }


    // method: public android.app.AutomaticZenRule getAutomaticZenRule(java.lang.String id)
    auto getAutomaticZenRule(jstring id) const {
        return m_jniObject.callMethod<jobject>(
                        "getAutomaticZenRule",
                        "(Ljava/lang/String;)Landroid/app/AutomaticZenRule;", id);
    }


    // method: public java.lang.String addAutomaticZenRule(android.app.AutomaticZenRule automaticZenRule)
    auto addAutomaticZenRule(jobject automaticZenRule) const {
        return m_jniObject.callMethod<jstring>(
                        "addAutomaticZenRule",
                        "(Landroid/app/AutomaticZenRule;)Ljava/lang/String;", automaticZenRule);
    }


    // method: public boolean updateAutomaticZenRule(java.lang.String id, android.app.AutomaticZenRule automaticZenRule)
    auto updateAutomaticZenRule(jstring id, jobject automaticZenRule) const {
        return m_jniObject.callMethod<jboolean>(
                        "updateAutomaticZenRule",
                        "(Ljava/lang/String;Landroid/app/AutomaticZenRule;)Z", id, automaticZenRule);
    }


    // method: public int getAutomaticZenRuleState(java.lang.String id)
    auto getAutomaticZenRuleState(jstring id) const {
        return m_jniObject.callMethod<jint>(
                        "getAutomaticZenRuleState",
                        "(Ljava/lang/String;)I", id);
    }


    // method: public void setAutomaticZenRuleState(java.lang.String id, android.service.notification.Condition condition)
    auto setAutomaticZenRuleState(jstring id, jobject condition) const {
        m_jniObject.callMethod<void>(
                        "setAutomaticZenRuleState",
                        "(Ljava/lang/String;Landroid/service/notification/Condition;)V", id, condition);
    }


    // method: public boolean removeAutomaticZenRule(java.lang.String id)
    auto removeAutomaticZenRule(jstring id) const {
        return m_jniObject.callMethod<jboolean>(
                        "removeAutomaticZenRule",
                        "(Ljava/lang/String;)Z", id);
    }


    // method: public int getImportance()
    auto getImportance() const {
        return m_jniObject.callMethod<jint>(
                        "getImportance",
                        "()I");
    }


    // method: public boolean areNotificationsEnabled()
    auto areNotificationsEnabled() const {
        return m_jniObject.callMethod<jboolean>(
                        "areNotificationsEnabled",
                        "()Z");
    }


    // method: public boolean areBubblesAllowed()
    auto areBubblesAllowed() const {
        return m_jniObject.callMethod<jboolean>(
                        "areBubblesAllowed",
                        "()Z");
    }


    // method: public boolean areBubblesEnabled()
    auto areBubblesEnabled() const {
        return m_jniObject.callMethod<jboolean>(
                        "areBubblesEnabled",
                        "()Z");
    }


    // method: public int getBubblePreference()
    auto getBubblePreference() const {
        return m_jniObject.callMethod<jint>(
                        "getBubblePreference",
                        "()I");
    }


    // method: public boolean areNotificationsPaused()
    auto areNotificationsPaused() const {
        return m_jniObject.callMethod<jboolean>(
                        "areNotificationsPaused",
                        "()Z");
    }


    // method: public boolean isNotificationPolicyAccessGranted()
    auto isNotificationPolicyAccessGranted() const {
        return m_jniObject.callMethod<jboolean>(
                        "isNotificationPolicyAccessGranted",
                        "()Z");
    }


    // method: public boolean isNotificationListenerAccessGranted(android.content.ComponentName listener)
    auto isNotificationListenerAccessGranted(jobject listener) const {
        return m_jniObject.callMethod<jboolean>(
                        "isNotificationListenerAccessGranted",
                        "(Landroid/content/ComponentName;)Z", listener);
    }


    // method: public boolean shouldHideSilentStatusBarIcons()
    auto shouldHideSilentStatusBarIcons() const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldHideSilentStatusBarIcons",
                        "()Z");
    }


    // method: public android.app.NotificationManager.Policy getNotificationPolicy()
    auto getNotificationPolicy() const {
        return m_jniObject.callMethod<jobject>(
                        "getNotificationPolicy",
                        "()Landroid/app/NotificationManager$Policy;");
    }


    // method: public void setNotificationPolicy(android.app.NotificationManager.Policy policy)
    auto setNotificationPolicy(jobject policy) const {
        m_jniObject.callMethod<void>(
                        "setNotificationPolicy",
                        "(Landroid/app/NotificationManager$Policy;)V", policy);
    }


    // method: public android.service.notification.StatusBarNotification[] getActiveNotifications()
    auto getActiveNotifications() const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getActiveNotifications",
                        "()[Landroid/service/notification/StatusBarNotification;");
    }


    // method: public final int getCurrentInterruptionFilter()
    auto getCurrentInterruptionFilter() const {
        return m_jniObject.callMethod<jint>(
                        "getCurrentInterruptionFilter",
                        "()I");
    }


    // method: public final void setInterruptionFilter(int interruptionFilter)
    auto setInterruptionFilter(jint interruptionFilter) const {
        m_jniObject.callMethod<void>(
                        "setInterruptionFilter",
                        "(I)V", interruptionFilter);
    }


    // method: public boolean matchesCallFilter(android.net.Uri uri)
    auto matchesCallFilter(jobject uri) const {
        return m_jniObject.callMethod<jboolean>(
                        "matchesCallFilter",
                        "(Landroid/net/Uri;)Z", uri);
    }


};
} } // endof namespace android::app


namespace android { namespace app {


} } // endof namespace android::app

#endif // android_app_NotificationManagerProxy_H

