
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_view_WindowProxy_H
#define android_view_WindowProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace view {
class WindowProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/view/Window";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    WindowProxy() {}
    WindowProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    WindowProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static WindowProxy fromLocalRef(jobject localRef) {
        WindowProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr jint DECOR_CAPTION_SHADE_AUTO = 0;
    static constexpr jint DECOR_CAPTION_SHADE_DARK = 2;
    static constexpr jint DECOR_CAPTION_SHADE_LIGHT = 1;
    static constexpr jint FEATURE_ACTION_BAR = 8;
    static constexpr jint FEATURE_ACTION_BAR_OVERLAY = 9;
    static constexpr jint FEATURE_ACTION_MODE_OVERLAY = 10;
    static constexpr jint FEATURE_ACTIVITY_TRANSITIONS = 13;
    static constexpr jint FEATURE_CONTENT_TRANSITIONS = 12;
    static constexpr jint FEATURE_CONTEXT_MENU = 6;
    static constexpr jint FEATURE_CUSTOM_TITLE = 7;
    static constexpr jint FEATURE_INDETERMINATE_PROGRESS = 5;
    static constexpr jint FEATURE_LEFT_ICON = 3;
    static constexpr jint FEATURE_NO_TITLE = 1;
    static constexpr jint FEATURE_OPTIONS_PANEL = 0;
    static constexpr jint FEATURE_PROGRESS = 2;
    static constexpr jint FEATURE_RIGHT_ICON = 4;
    static constexpr jint FEATURE_SWIPE_TO_DISMISS = 11;
    static constexpr jint ID_ANDROID_CONTENT = 16908290;
    static constexpr auto NAVIGATION_BAR_BACKGROUND_TRANSITION_NAME = u8"android:navigation:background";
    static constexpr jint PROGRESS_END = 10000;
    static constexpr jint PROGRESS_INDETERMINATE_OFF = -4;
    static constexpr jint PROGRESS_INDETERMINATE_ON = -3;
    static constexpr jint PROGRESS_SECONDARY_END = 30000;
    static constexpr jint PROGRESS_SECONDARY_START = 20000;
    static constexpr jint PROGRESS_START = 0;
    static constexpr jint PROGRESS_VISIBILITY_OFF = -2;
    static constexpr jint PROGRESS_VISIBILITY_ON = -1;
    static constexpr auto STATUS_BAR_BACKGROUND_TRANSITION_NAME = u8"android:status:background";


    // construct: public Window(android.content.Context context)
    static WindowProxy newInstance(jobject context) {
        WindowProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Landroid/content/Context;)V", context);
        return ret;
    }

    // method: public final android.content.Context getContext()
    auto getContext() const {
        return m_jniObject.callMethod<jobject>(
                        "getContext",
                        "()Landroid/content/Context;");
    }


    // method: public final android.content.res.TypedArray getWindowStyle()
    auto getWindowStyle() const {
        return m_jniObject.callMethod<jobject>(
                        "getWindowStyle",
                        "()Landroid/content/res/TypedArray;");
    }


    // method: public void setContainer(android.view.Window container)
    auto setContainer(jobject container) const {
        m_jniObject.callMethod<void>(
                        "setContainer",
                        "(Landroid/view/Window;)V", container);
    }


    // method: public final android.view.Window getContainer()
    auto getContainer() const {
        return m_jniObject.callMethod<jobject>(
                        "getContainer",
                        "()Landroid/view/Window;");
    }


    // method: public final boolean hasChildren()
    auto hasChildren() const {
        return m_jniObject.callMethod<jboolean>(
                        "hasChildren",
                        "()Z");
    }


    // method: public void setWindowManager(android.view.WindowManager wm, android.os.IBinder appToken, java.lang.String appName)
    auto setWindowManager(jobject wm, jobject appToken, jstring appName) const {
        m_jniObject.callMethod<void>(
                        "setWindowManager",
                        "(Landroid/view/WindowManager;Landroid/os/IBinder;Ljava/lang/String;)V", wm, appToken, appName);
    }


    // method: public void setWindowManager(android.view.WindowManager wm, android.os.IBinder appToken, java.lang.String appName, boolean hardwareAccelerated)
    auto setWindowManager(jobject wm, jobject appToken, jstring appName, jboolean hardwareAccelerated) const {
        m_jniObject.callMethod<void>(
                        "setWindowManager",
                        "(Landroid/view/WindowManager;Landroid/os/IBinder;Ljava/lang/String;Z)V", wm, appToken, appName, hardwareAccelerated);
    }


    // method: public android.view.WindowManager getWindowManager()
    auto getWindowManager() const {
        return m_jniObject.callMethod<jobject>(
                        "getWindowManager",
                        "()Landroid/view/WindowManager;");
    }


    // method: public void setCallback(android.view.Window.Callback callback)
    auto setCallback(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "setCallback",
                        "(Landroid/view/Window$Callback;)V", callback);
    }


    // method: public final android.view.Window.Callback getCallback()
    auto getCallback() const {
        return m_jniObject.callMethod<jobject>(
                        "getCallback",
                        "()Landroid/view/Window$Callback;");
    }


    // method: public final void addOnFrameMetricsAvailableListener(android.view.Window.OnFrameMetricsAvailableListener listener, android.os.Handler handler)
    auto addOnFrameMetricsAvailableListener(jobject listener, jobject handler) const {
        m_jniObject.callMethod<void>(
                        "addOnFrameMetricsAvailableListener",
                        "(Landroid/view/Window$OnFrameMetricsAvailableListener;Landroid/os/Handler;)V", listener, handler);
    }


    // method: public final void removeOnFrameMetricsAvailableListener(android.view.Window.OnFrameMetricsAvailableListener listener)
    auto removeOnFrameMetricsAvailableListener(jobject listener) const {
        m_jniObject.callMethod<void>(
                        "removeOnFrameMetricsAvailableListener",
                        "(Landroid/view/Window$OnFrameMetricsAvailableListener;)V", listener);
    }


    // method: public final void setRestrictedCaptionAreaListener(android.view.Window.OnRestrictedCaptionAreaChangedListener listener)
    auto setRestrictedCaptionAreaListener(jobject listener) const {
        m_jniObject.callMethod<void>(
                        "setRestrictedCaptionAreaListener",
                        "(Landroid/view/Window$OnRestrictedCaptionAreaChangedListener;)V", listener);
    }


    // method: public final void setHideOverlayWindows(boolean hide)
    auto setHideOverlayWindows(jboolean hide) const {
        m_jniObject.callMethod<void>(
                        "setHideOverlayWindows",
                        "(Z)V", hide);
    }


    // method: public abstract void takeSurface(android.view.SurfaceHolder.Callback2 arg0)
    auto takeSurface(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "takeSurface",
                        "(Landroid/view/SurfaceHolder$Callback2;)V", arg0);
    }


    // method: public abstract void takeInputQueue(android.view.InputQueue.Callback arg0)
    auto takeInputQueue(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "takeInputQueue",
                        "(Landroid/view/InputQueue$Callback;)V", arg0);
    }


    // method: public abstract boolean isFloating()
    auto isFloating() const {
        return m_jniObject.callMethod<jboolean>(
                        "isFloating",
                        "()Z");
    }


    // method: public void setLayout(int width, int height)
    auto setLayout(jint width, jint height) const {
        m_jniObject.callMethod<void>(
                        "setLayout",
                        "(II)V", width, height);
    }


    // method: public void setGravity(int gravity)
    auto setGravity(jint gravity) const {
        m_jniObject.callMethod<void>(
                        "setGravity",
                        "(I)V", gravity);
    }


    // method: public void setType(int type)
    auto setType(jint type) const {
        m_jniObject.callMethod<void>(
                        "setType",
                        "(I)V", type);
    }


    // method: public void setFormat(int format)
    auto setFormat(jint format) const {
        m_jniObject.callMethod<void>(
                        "setFormat",
                        "(I)V", format);
    }


    // method: public void setWindowAnimations(int resId)
    auto setWindowAnimations(jint resId) const {
        m_jniObject.callMethod<void>(
                        "setWindowAnimations",
                        "(I)V", resId);
    }


    // method: public void setSoftInputMode(int mode)
    auto setSoftInputMode(jint mode) const {
        m_jniObject.callMethod<void>(
                        "setSoftInputMode",
                        "(I)V", mode);
    }


    // method: public void addFlags(int flags)
    auto addFlags(jint flags) const {
        m_jniObject.callMethod<void>(
                        "addFlags",
                        "(I)V", flags);
    }


    // method: public void clearFlags(int flags)
    auto clearFlags(jint flags) const {
        m_jniObject.callMethod<void>(
                        "clearFlags",
                        "(I)V", flags);
    }


    // method: public void setFlags(int flags, int mask)
    auto setFlags(jint flags, jint mask) const {
        m_jniObject.callMethod<void>(
                        "setFlags",
                        "(II)V", flags, mask);
    }


    // method: public void setColorMode(int colorMode)
    auto setColorMode(jint colorMode) const {
        m_jniObject.callMethod<void>(
                        "setColorMode",
                        "(I)V", colorMode);
    }


    // method: public void setDesiredHdrHeadroom(float desiredHeadroom)
    auto setDesiredHdrHeadroom(jfloat desiredHeadroom) const {
        m_jniObject.callMethod<void>(
                        "setDesiredHdrHeadroom",
                        "(F)V", desiredHeadroom);
    }


    // method: public float getDesiredHdrHeadroom()
    auto getDesiredHdrHeadroom() const {
        return m_jniObject.callMethod<jfloat>(
                        "getDesiredHdrHeadroom",
                        "()F");
    }


    // method: public void setFrameRateBoostOnTouchEnabled(boolean enabled)
    auto setFrameRateBoostOnTouchEnabled(jboolean enabled) const {
        m_jniObject.callMethod<void>(
                        "setFrameRateBoostOnTouchEnabled",
                        "(Z)V", enabled);
    }


    // method: public boolean getFrameRateBoostOnTouchEnabled()
    auto getFrameRateBoostOnTouchEnabled() const {
        return m_jniObject.callMethod<jboolean>(
                        "getFrameRateBoostOnTouchEnabled",
                        "()Z");
    }


    // method: public void setFrameRatePowerSavingsBalanced(boolean enabled)
    auto setFrameRatePowerSavingsBalanced(jboolean enabled) const {
        m_jniObject.callMethod<void>(
                        "setFrameRatePowerSavingsBalanced",
                        "(Z)V", enabled);
    }


    // method: public boolean isFrameRatePowerSavingsBalanced()
    auto isFrameRatePowerSavingsBalanced() const {
        return m_jniObject.callMethod<jboolean>(
                        "isFrameRatePowerSavingsBalanced",
                        "()Z");
    }


    // method: public void setPreferMinimalPostProcessing(boolean isPreferred)
    auto setPreferMinimalPostProcessing(jboolean isPreferred) const {
        m_jniObject.callMethod<void>(
                        "setPreferMinimalPostProcessing",
                        "(Z)V", isPreferred);
    }


    // method: public int getColorMode()
    auto getColorMode() const {
        return m_jniObject.callMethod<jint>(
                        "getColorMode",
                        "()I");
    }


    // method: public boolean isWideColorGamut()
    auto isWideColorGamut() const {
        return m_jniObject.callMethod<jboolean>(
                        "isWideColorGamut",
                        "()Z");
    }


    // method: public void setDimAmount(float amount)
    auto setDimAmount(jfloat amount) const {
        m_jniObject.callMethod<void>(
                        "setDimAmount",
                        "(F)V", amount);
    }


    // method: public void setDecorFitsSystemWindows(boolean decorFitsSystemWindows)
    auto setDecorFitsSystemWindows(jboolean decorFitsSystemWindows) const {
        m_jniObject.callMethod<void>(
                        "setDecorFitsSystemWindows",
                        "(Z)V", decorFitsSystemWindows);
    }


    // method: public void setAttributes(android.view.WindowManager.LayoutParams a)
    auto setAttributes(jobject a) const {
        m_jniObject.callMethod<void>(
                        "setAttributes",
                        "(Landroid/view/WindowManager$LayoutParams;)V", a);
    }


    // method: public final android.view.WindowManager.LayoutParams getAttributes()
    auto getAttributes() const {
        return m_jniObject.callMethod<jobject>(
                        "getAttributes",
                        "()Landroid/view/WindowManager$LayoutParams;");
    }


    // method: public void setSustainedPerformanceMode(boolean enable)
    auto setSustainedPerformanceMode(jboolean enable) const {
        m_jniObject.callMethod<void>(
                        "setSustainedPerformanceMode",
                        "(Z)V", enable);
    }


    // method: public boolean requestFeature(int featureId)
    auto requestFeature(jint featureId) const {
        return m_jniObject.callMethod<jboolean>(
                        "requestFeature",
                        "(I)Z", featureId);
    }


    // method: public final void makeActive()
    auto makeActive() const {
        m_jniObject.callMethod<void>(
                        "makeActive",
                        "()V");
    }


    // method: public final boolean isActive()
    auto isActive() const {
        return m_jniObject.callMethod<jboolean>(
                        "isActive",
                        "()Z");
    }


    // method: public T findViewById(int id)
    auto findViewById(jint id) const {
        return m_jniObject.callMethod<jobject>(
                        "findViewById",
                        "(I)Landroid/view/View;", id);
    }


    // method: public final T requireViewById(int id)
    auto requireViewById(jint id) const {
        return m_jniObject.callMethod<jobject>(
                        "requireViewById",
                        "(I)Landroid/view/View;", id);
    }


    // method: public abstract void setContentView(int arg0)
    auto setContentView(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "setContentView",
                        "(I)V", arg0);
    }


    // method: public abstract void setContentView(android.view.View arg0)
    auto setContentView(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "setContentView",
                        "(Landroid/view/View;)V", arg0);
    }


    // method: public abstract void setContentView(android.view.View arg0, android.view.ViewGroup.LayoutParams arg1)
    auto setContentView(jobject arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "setContentView",
                        "(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V", arg0, arg1);
    }


    // method: public abstract void addContentView(android.view.View arg0, android.view.ViewGroup.LayoutParams arg1)
    auto addContentView(jobject arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "addContentView",
                        "(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V", arg0, arg1);
    }


    // method: public abstract android.view.View getCurrentFocus()
    auto getCurrentFocus() const {
        return m_jniObject.callMethod<jobject>(
                        "getCurrentFocus",
                        "()Landroid/view/View;");
    }


    // method: public abstract android.view.LayoutInflater getLayoutInflater()
    auto getLayoutInflater() const {
        return m_jniObject.callMethod<jobject>(
                        "getLayoutInflater",
                        "()Landroid/view/LayoutInflater;");
    }


    // method: public abstract void setTitle(java.lang.CharSequence arg0)
    auto setTitle(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "setTitle",
                        "(Ljava/lang/CharSequence;)V", arg0);
    }


    // method: public abstract void setTitleColor(int arg0)
    auto setTitleColor(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "setTitleColor",
                        "(I)V", arg0);
    }


    // method: public abstract void openPanel(int arg0, android.view.KeyEvent arg1)
    auto openPanel(jint arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "openPanel",
                        "(ILandroid/view/KeyEvent;)V", arg0, arg1);
    }


    // method: public abstract void closePanel(int arg0)
    auto closePanel(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "closePanel",
                        "(I)V", arg0);
    }


    // method: public abstract void togglePanel(int arg0, android.view.KeyEvent arg1)
    auto togglePanel(jint arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "togglePanel",
                        "(ILandroid/view/KeyEvent;)V", arg0, arg1);
    }


    // method: public abstract void invalidatePanelMenu(int arg0)
    auto invalidatePanelMenu(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "invalidatePanelMenu",
                        "(I)V", arg0);
    }


    // method: public abstract boolean performPanelShortcut(int arg0, int arg1, android.view.KeyEvent arg2, int arg3)
    auto performPanelShortcut(jint arg0, jint arg1, jobject arg2, jint arg3) const {
        return m_jniObject.callMethod<jboolean>(
                        "performPanelShortcut",
                        "(IILandroid/view/KeyEvent;I)Z", arg0, arg1, arg2, arg3);
    }


    // method: public abstract boolean performPanelIdentifierAction(int arg0, int arg1, int arg2)
    auto performPanelIdentifierAction(jint arg0, jint arg1, jint arg2) const {
        return m_jniObject.callMethod<jboolean>(
                        "performPanelIdentifierAction",
                        "(III)Z", arg0, arg1, arg2);
    }


    // method: public abstract void closeAllPanels()
    auto closeAllPanels() const {
        m_jniObject.callMethod<void>(
                        "closeAllPanels",
                        "()V");
    }


    // method: public abstract boolean performContextMenuIdentifierAction(int arg0, int arg1)
    auto performContextMenuIdentifierAction(jint arg0, jint arg1) const {
        return m_jniObject.callMethod<jboolean>(
                        "performContextMenuIdentifierAction",
                        "(II)Z", arg0, arg1);
    }


    // method: public abstract void onConfigurationChanged(android.content.res.Configuration arg0)
    auto onConfigurationChanged(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "onConfigurationChanged",
                        "(Landroid/content/res/Configuration;)V", arg0);
    }


    // method: public void setElevation(float elevation)
    auto setElevation(jfloat elevation) const {
        m_jniObject.callMethod<void>(
                        "setElevation",
                        "(F)V", elevation);
    }


    // method: public void setClipToOutline(boolean clipToOutline)
    auto setClipToOutline(jboolean clipToOutline) const {
        m_jniObject.callMethod<void>(
                        "setClipToOutline",
                        "(Z)V", clipToOutline);
    }


    // method: public void setBackgroundDrawableResource(int resId)
    auto setBackgroundDrawableResource(jint resId) const {
        m_jniObject.callMethod<void>(
                        "setBackgroundDrawableResource",
                        "(I)V", resId);
    }


    // method: public abstract void setBackgroundDrawable(android.graphics.drawable.Drawable arg0)
    auto setBackgroundDrawable(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "setBackgroundDrawable",
                        "(Landroid/graphics/drawable/Drawable;)V", arg0);
    }


    // method: public void setBackgroundBlurRadius(int blurRadius)
    auto setBackgroundBlurRadius(jint blurRadius) const {
        m_jniObject.callMethod<void>(
                        "setBackgroundBlurRadius",
                        "(I)V", blurRadius);
    }


    // method: public abstract void setFeatureDrawableResource(int arg0, int arg1)
    auto setFeatureDrawableResource(jint arg0, jint arg1) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawableResource",
                        "(II)V", arg0, arg1);
    }


    // method: public abstract void setFeatureDrawableUri(int arg0, android.net.Uri arg1)
    auto setFeatureDrawableUri(jint arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawableUri",
                        "(ILandroid/net/Uri;)V", arg0, arg1);
    }


    // method: public abstract void setFeatureDrawable(int arg0, android.graphics.drawable.Drawable arg1)
    auto setFeatureDrawable(jint arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawable",
                        "(ILandroid/graphics/drawable/Drawable;)V", arg0, arg1);
    }


    // method: public abstract void setFeatureDrawableAlpha(int arg0, int arg1)
    auto setFeatureDrawableAlpha(jint arg0, jint arg1) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawableAlpha",
                        "(II)V", arg0, arg1);
    }


    // method: public abstract void setFeatureInt(int arg0, int arg1)
    auto setFeatureInt(jint arg0, jint arg1) const {
        m_jniObject.callMethod<void>(
                        "setFeatureInt",
                        "(II)V", arg0, arg1);
    }


    // method: public abstract void takeKeyEvents(boolean arg0)
    auto takeKeyEvents(jboolean arg0) const {
        m_jniObject.callMethod<void>(
                        "takeKeyEvents",
                        "(Z)V", arg0);
    }


    // method: public abstract boolean superDispatchKeyEvent(android.view.KeyEvent arg0)
    auto superDispatchKeyEvent(jobject arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "superDispatchKeyEvent",
                        "(Landroid/view/KeyEvent;)Z", arg0);
    }


    // method: public abstract boolean superDispatchKeyShortcutEvent(android.view.KeyEvent arg0)
    auto superDispatchKeyShortcutEvent(jobject arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "superDispatchKeyShortcutEvent",
                        "(Landroid/view/KeyEvent;)Z", arg0);
    }


    // method: public abstract boolean superDispatchTouchEvent(android.view.MotionEvent arg0)
    auto superDispatchTouchEvent(jobject arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "superDispatchTouchEvent",
                        "(Landroid/view/MotionEvent;)Z", arg0);
    }


    // method: public abstract boolean superDispatchTrackballEvent(android.view.MotionEvent arg0)
    auto superDispatchTrackballEvent(jobject arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "superDispatchTrackballEvent",
                        "(Landroid/view/MotionEvent;)Z", arg0);
    }


    // method: public abstract boolean superDispatchGenericMotionEvent(android.view.MotionEvent arg0)
    auto superDispatchGenericMotionEvent(jobject arg0) const {
        return m_jniObject.callMethod<jboolean>(
                        "superDispatchGenericMotionEvent",
                        "(Landroid/view/MotionEvent;)Z", arg0);
    }


    // method: public abstract android.view.View getDecorView()
    auto getDecorView() const {
        return m_jniObject.callMethod<jobject>(
                        "getDecorView",
                        "()Landroid/view/View;");
    }


    // method: public abstract android.view.View peekDecorView()
    auto peekDecorView() const {
        return m_jniObject.callMethod<jobject>(
                        "peekDecorView",
                        "()Landroid/view/View;");
    }


    // method: public abstract android.os.Bundle saveHierarchyState()
    auto saveHierarchyState() const {
        return m_jniObject.callMethod<jobject>(
                        "saveHierarchyState",
                        "()Landroid/os/Bundle;");
    }


    // method: public abstract void restoreHierarchyState(android.os.Bundle arg0)
    auto restoreHierarchyState(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "restoreHierarchyState",
                        "(Landroid/os/Bundle;)V", arg0);
    }


    // method: public static int getDefaultFeatures(android.content.Context context)
    static auto getDefaultFeatures(jobject context) {
        return QJniObject::callStaticMethod<jint>(FULL_CLASS_NAME,
                        "getDefaultFeatures",
                        "(Landroid/content/Context;)I", context);
    }


    // method: public boolean hasFeature(int feature)
    auto hasFeature(jint feature) const {
        return m_jniObject.callMethod<jboolean>(
                        "hasFeature",
                        "(I)Z", feature);
    }


    // method: public abstract void setChildDrawable(int arg0, android.graphics.drawable.Drawable arg1)
    auto setChildDrawable(jint arg0, jobject arg1) const {
        m_jniObject.callMethod<void>(
                        "setChildDrawable",
                        "(ILandroid/graphics/drawable/Drawable;)V", arg0, arg1);
    }


    // method: public abstract void setChildInt(int arg0, int arg1)
    auto setChildInt(jint arg0, jint arg1) const {
        m_jniObject.callMethod<void>(
                        "setChildInt",
                        "(II)V", arg0, arg1);
    }


    // method: public abstract boolean isShortcutKey(int arg0, android.view.KeyEvent arg1)
    auto isShortcutKey(jint arg0, jobject arg1) const {
        return m_jniObject.callMethod<jboolean>(
                        "isShortcutKey",
                        "(ILandroid/view/KeyEvent;)Z", arg0, arg1);
    }


    // method: public abstract void setVolumeControlStream(int arg0)
    auto setVolumeControlStream(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "setVolumeControlStream",
                        "(I)V", arg0);
    }


    // method: public abstract int getVolumeControlStream()
    auto getVolumeControlStream() const {
        return m_jniObject.callMethod<jint>(
                        "getVolumeControlStream",
                        "()I");
    }


    // method: public void setMediaController(android.media.session.MediaController controller)
    auto setMediaController(jobject controller) const {
        m_jniObject.callMethod<void>(
                        "setMediaController",
                        "(Landroid/media/session/MediaController;)V", controller);
    }


    // method: public android.media.session.MediaController getMediaController()
    auto getMediaController() const {
        return m_jniObject.callMethod<jobject>(
                        "getMediaController",
                        "()Landroid/media/session/MediaController;");
    }


    // method: public void setUiOptions(int uiOptions)
    auto setUiOptions(jint uiOptions) const {
        m_jniObject.callMethod<void>(
                        "setUiOptions",
                        "(I)V", uiOptions);
    }


    // method: public void setUiOptions(int uiOptions, int mask)
    auto setUiOptions(jint uiOptions, jint mask) const {
        m_jniObject.callMethod<void>(
                        "setUiOptions",
                        "(II)V", uiOptions, mask);
    }


    // method: public void setIcon(int resId)
    auto setIcon(jint resId) const {
        m_jniObject.callMethod<void>(
                        "setIcon",
                        "(I)V", resId);
    }


    // method: public void setLogo(int resId)
    auto setLogo(jint resId) const {
        m_jniObject.callMethod<void>(
                        "setLogo",
                        "(I)V", resId);
    }


    // method: public void setLocalFocus(boolean hasFocus, boolean inTouchMode)
    auto setLocalFocus(jboolean hasFocus, jboolean inTouchMode) const {
        m_jniObject.callMethod<void>(
                        "setLocalFocus",
                        "(ZZ)V", hasFocus, inTouchMode);
    }


    // method: public void injectInputEvent(android.view.InputEvent event)
    auto injectInputEvent(jobject event) const {
        m_jniObject.callMethod<void>(
                        "injectInputEvent",
                        "(Landroid/view/InputEvent;)V", event);
    }


    // method: public android.transition.TransitionManager getTransitionManager()
    auto getTransitionManager() const {
        return m_jniObject.callMethod<jobject>(
                        "getTransitionManager",
                        "()Landroid/transition/TransitionManager;");
    }


    // method: public void setTransitionManager(android.transition.TransitionManager tm)
    auto setTransitionManager(jobject tm) const {
        m_jniObject.callMethod<void>(
                        "setTransitionManager",
                        "(Landroid/transition/TransitionManager;)V", tm);
    }


    // method: public android.transition.Scene getContentScene()
    auto getContentScene() const {
        return m_jniObject.callMethod<jobject>(
                        "getContentScene",
                        "()Landroid/transition/Scene;");
    }


    // method: public void setEnterTransition(android.transition.Transition transition)
    auto setEnterTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setEnterTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public void setReturnTransition(android.transition.Transition transition)
    auto setReturnTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setReturnTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public void setExitTransition(android.transition.Transition transition)
    auto setExitTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setExitTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public void setReenterTransition(android.transition.Transition transition)
    auto setReenterTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setReenterTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public android.transition.Transition getEnterTransition()
    auto getEnterTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getEnterTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public android.transition.Transition getReturnTransition()
    auto getReturnTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getReturnTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public android.transition.Transition getExitTransition()
    auto getExitTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getExitTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public android.transition.Transition getReenterTransition()
    auto getReenterTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getReenterTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public void setSharedElementEnterTransition(android.transition.Transition transition)
    auto setSharedElementEnterTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setSharedElementEnterTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public void setSharedElementReturnTransition(android.transition.Transition transition)
    auto setSharedElementReturnTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setSharedElementReturnTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public android.transition.Transition getSharedElementEnterTransition()
    auto getSharedElementEnterTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getSharedElementEnterTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public android.transition.Transition getSharedElementReturnTransition()
    auto getSharedElementReturnTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getSharedElementReturnTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public void setSharedElementExitTransition(android.transition.Transition transition)
    auto setSharedElementExitTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setSharedElementExitTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public void setSharedElementReenterTransition(android.transition.Transition transition)
    auto setSharedElementReenterTransition(jobject transition) const {
        m_jniObject.callMethod<void>(
                        "setSharedElementReenterTransition",
                        "(Landroid/transition/Transition;)V", transition);
    }


    // method: public android.transition.Transition getSharedElementExitTransition()
    auto getSharedElementExitTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getSharedElementExitTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public android.transition.Transition getSharedElementReenterTransition()
    auto getSharedElementReenterTransition() const {
        return m_jniObject.callMethod<jobject>(
                        "getSharedElementReenterTransition",
                        "()Landroid/transition/Transition;");
    }


    // method: public void setAllowEnterTransitionOverlap(boolean allow)
    auto setAllowEnterTransitionOverlap(jboolean allow) const {
        m_jniObject.callMethod<void>(
                        "setAllowEnterTransitionOverlap",
                        "(Z)V", allow);
    }


    // method: public boolean getAllowEnterTransitionOverlap()
    auto getAllowEnterTransitionOverlap() const {
        return m_jniObject.callMethod<jboolean>(
                        "getAllowEnterTransitionOverlap",
                        "()Z");
    }


    // method: public void setAllowReturnTransitionOverlap(boolean allow)
    auto setAllowReturnTransitionOverlap(jboolean allow) const {
        m_jniObject.callMethod<void>(
                        "setAllowReturnTransitionOverlap",
                        "(Z)V", allow);
    }


    // method: public boolean getAllowReturnTransitionOverlap()
    auto getAllowReturnTransitionOverlap() const {
        return m_jniObject.callMethod<jboolean>(
                        "getAllowReturnTransitionOverlap",
                        "()Z");
    }


    // method: public long getTransitionBackgroundFadeDuration()
    auto getTransitionBackgroundFadeDuration() const {
        return m_jniObject.callMethod<jlong>(
                        "getTransitionBackgroundFadeDuration",
                        "()J");
    }


    // method: public void setTransitionBackgroundFadeDuration(long fadeDurationMillis)
    auto setTransitionBackgroundFadeDuration(jlong fadeDurationMillis) const {
        m_jniObject.callMethod<void>(
                        "setTransitionBackgroundFadeDuration",
                        "(J)V", fadeDurationMillis);
    }


    // method: public boolean getSharedElementsUseOverlay()
    auto getSharedElementsUseOverlay() const {
        return m_jniObject.callMethod<jboolean>(
                        "getSharedElementsUseOverlay",
                        "()Z");
    }


    // method: public void setSharedElementsUseOverlay(boolean sharedElementsUseOverlay)
    auto setSharedElementsUseOverlay(jboolean sharedElementsUseOverlay) const {
        m_jniObject.callMethod<void>(
                        "setSharedElementsUseOverlay",
                        "(Z)V", sharedElementsUseOverlay);
    }


    // method: public abstract int getStatusBarColor()
    auto getStatusBarColor() const {
        return m_jniObject.callMethod<jint>(
                        "getStatusBarColor",
                        "()I");
    }


    // method: public abstract void setStatusBarColor(int arg0)
    auto setStatusBarColor(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "setStatusBarColor",
                        "(I)V", arg0);
    }


    // method: public abstract int getNavigationBarColor()
    auto getNavigationBarColor() const {
        return m_jniObject.callMethod<jint>(
                        "getNavigationBarColor",
                        "()I");
    }


    // method: public abstract void setNavigationBarColor(int arg0)
    auto setNavigationBarColor(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "setNavigationBarColor",
                        "(I)V", arg0);
    }


    // method: public void setNavigationBarDividerColor(int dividerColor)
    auto setNavigationBarDividerColor(jint dividerColor) const {
        m_jniObject.callMethod<void>(
                        "setNavigationBarDividerColor",
                        "(I)V", dividerColor);
    }


    // method: public int getNavigationBarDividerColor()
    auto getNavigationBarDividerColor() const {
        return m_jniObject.callMethod<jint>(
                        "getNavigationBarDividerColor",
                        "()I");
    }


    // method: public void setStatusBarContrastEnforced(boolean ensureContrast)
    auto setStatusBarContrastEnforced(jboolean ensureContrast) const {
        m_jniObject.callMethod<void>(
                        "setStatusBarContrastEnforced",
                        "(Z)V", ensureContrast);
    }


    // method: public boolean isStatusBarContrastEnforced()
    auto isStatusBarContrastEnforced() const {
        return m_jniObject.callMethod<jboolean>(
                        "isStatusBarContrastEnforced",
                        "()Z");
    }


    // method: public void setNavigationBarContrastEnforced(boolean enforceContrast)
    auto setNavigationBarContrastEnforced(jboolean enforceContrast) const {
        m_jniObject.callMethod<void>(
                        "setNavigationBarContrastEnforced",
                        "(Z)V", enforceContrast);
    }


    // method: public boolean isNavigationBarContrastEnforced()
    auto isNavigationBarContrastEnforced() const {
        return m_jniObject.callMethod<jboolean>(
                        "isNavigationBarContrastEnforced",
                        "()Z");
    }


    // method: public void setSystemGestureExclusionRects(java.util.List<android.graphics.Rect> rects)
    auto setSystemGestureExclusionRects(jobject rects) const {
        m_jniObject.callMethod<void>(
                        "setSystemGestureExclusionRects",
                        "(Ljava/util/List;)V", rects);
    }


    // method: public java.util.List<android.graphics.Rect> getSystemGestureExclusionRects()
    auto getSystemGestureExclusionRects() const {
        return m_jniObject.callMethod<jobject>(
                        "getSystemGestureExclusionRects",
                        "()Ljava/util/List;");
    }


    // method: public void registerScrollCaptureCallback(android.view.ScrollCaptureCallback callback)
    auto registerScrollCaptureCallback(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "registerScrollCaptureCallback",
                        "(Landroid/view/ScrollCaptureCallback;)V", callback);
    }


    // method: public void unregisterScrollCaptureCallback(android.view.ScrollCaptureCallback callback)
    auto unregisterScrollCaptureCallback(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "unregisterScrollCaptureCallback",
                        "(Landroid/view/ScrollCaptureCallback;)V", callback);
    }


    // method: public abstract void setDecorCaptionShade(int arg0)
    auto setDecorCaptionShade(jint arg0) const {
        m_jniObject.callMethod<void>(
                        "setDecorCaptionShade",
                        "(I)V", arg0);
    }


    // method: public abstract void setResizingCaptionDrawable(android.graphics.drawable.Drawable arg0)
    auto setResizingCaptionDrawable(jobject arg0) const {
        m_jniObject.callMethod<void>(
                        "setResizingCaptionDrawable",
                        "(Landroid/graphics/drawable/Drawable;)V", arg0);
    }


    // method: public android.view.WindowInsetsController getInsetsController()
    auto getInsetsController() const {
        return m_jniObject.callMethod<jobject>(
                        "getInsetsController",
                        "()Landroid/view/WindowInsetsController;");
    }


    // method: public android.view.AttachedSurfaceControl getRootSurfaceControl()
    auto getRootSurfaceControl() const {
        return m_jniObject.callMethod<jobject>(
                        "getRootSurfaceControl",
                        "()Landroid/view/AttachedSurfaceControl;");
    }


    // method: public android.window.OnBackInvokedDispatcher getOnBackInvokedDispatcher()
    auto getOnBackInvokedDispatcher() const {
        return m_jniObject.callMethod<jobject>(
                        "getOnBackInvokedDispatcher",
                        "()Landroid/window/OnBackInvokedDispatcher;");
    }


};
} } // endof namespace android::view


namespace android { namespace view {


} } // endof namespace android::view

#endif // android_view_WindowProxy_H

