
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_app_ActivityProxy_H
#define android_app_ActivityProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace app {
class ActivityProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/app/Activity";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    ActivityProxy() {}
    ActivityProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    ActivityProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static ActivityProxy fromLocalRef(jobject localRef) {
        ActivityProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr jint DEFAULT_KEYS_DIALER = 1;
    static constexpr jint DEFAULT_KEYS_DISABLE = 0;
    static constexpr jint DEFAULT_KEYS_SEARCH_GLOBAL = 4;
    static constexpr jint DEFAULT_KEYS_SEARCH_LOCAL = 3;
    static constexpr jint DEFAULT_KEYS_SHORTCUT = 2;
    static constexpr jint FULLSCREEN_MODE_REQUEST_ENTER = 1;
    static constexpr jint FULLSCREEN_MODE_REQUEST_EXIT = 0;
    static constexpr jint OVERRIDE_TRANSITION_CLOSE = 1;
    static constexpr jint OVERRIDE_TRANSITION_OPEN = 0;
    static constexpr jint RESULT_CANCELED = 0;
    static constexpr jint RESULT_FIRST_USER = 1;
    static constexpr jint RESULT_OK = -1;


    // construct: public Activity()
    static ActivityProxy newInstance() {
        ActivityProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "()V");
        return ret;
    }

    // method: public android.content.Intent getIntent()
    auto getIntent() const {
        return m_jniObject.callMethod<jobject>(
                        "getIntent",
                        "()Landroid/content/Intent;");
    }


    // method: public void setIntent(android.content.Intent newIntent)
    auto setIntent(jobject newIntent) const {
        m_jniObject.callMethod<void>(
                        "setIntent",
                        "(Landroid/content/Intent;)V", newIntent);
    }


    // method: public void setIntent(android.content.Intent newIntent, android.app.ComponentCaller newCaller)
    auto setIntent(jobject newIntent, jobject newCaller) const {
        m_jniObject.callMethod<void>(
                        "setIntent",
                        "(Landroid/content/Intent;Landroid/app/ComponentCaller;)V", newIntent, newCaller);
    }


    // method: public android.app.ComponentCaller getCaller()
    auto getCaller() const {
        return m_jniObject.callMethod<jobject>(
                        "getCaller",
                        "()Landroid/app/ComponentCaller;");
    }


    // method: public void setLocusContext(android.content.LocusId locusId, android.os.Bundle bundle)
    auto setLocusContext(jobject locusId, jobject bundle) const {
        m_jniObject.callMethod<void>(
                        "setLocusContext",
                        "(Landroid/content/LocusId;Landroid/os/Bundle;)V", locusId, bundle);
    }


    // method: public final android.app.Application getApplication()
    auto getApplication() const {
        return m_jniObject.callMethod<jobject>(
                        "getApplication",
                        "()Landroid/app/Application;");
    }


    // method: public final boolean isChild()
    auto isChild() const {
        return m_jniObject.callMethod<jboolean>(
                        "isChild",
                        "()Z");
    }


    // method: public final android.app.Activity getParent()
    auto getParent() const {
        return m_jniObject.callMethod<jobject>(
                        "getParent",
                        "()Landroid/app/Activity;");
    }


    // method: public android.view.WindowManager getWindowManager()
    auto getWindowManager() const {
        return m_jniObject.callMethod<jobject>(
                        "getWindowManager",
                        "()Landroid/view/WindowManager;");
    }


    // method: public android.view.Window getWindow()
    auto getWindow() const {
        return m_jniObject.callMethod<jobject>(
                        "getWindow",
                        "()Landroid/view/Window;");
    }


    // method: public android.app.LoaderManager getLoaderManager()
    auto getLoaderManager() const {
        return m_jniObject.callMethod<jobject>(
                        "getLoaderManager",
                        "()Landroid/app/LoaderManager;");
    }


    // method: public android.view.View getCurrentFocus()
    auto getCurrentFocus() const {
        return m_jniObject.callMethod<jobject>(
                        "getCurrentFocus",
                        "()Landroid/view/View;");
    }


    // method: public void registerActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks callback)
    auto registerActivityLifecycleCallbacks(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "registerActivityLifecycleCallbacks",
                        "(Landroid/app/Application$ActivityLifecycleCallbacks;)V", callback);
    }


    // method: public void unregisterActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks callback)
    auto unregisterActivityLifecycleCallbacks(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "unregisterActivityLifecycleCallbacks",
                        "(Landroid/app/Application$ActivityLifecycleCallbacks;)V", callback);
    }


    // method: public void registerComponentCallbacks(android.content.ComponentCallbacks callback)
    auto registerComponentCallbacks(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "registerComponentCallbacks",
                        "(Landroid/content/ComponentCallbacks;)V", callback);
    }


    // method: public void unregisterComponentCallbacks(android.content.ComponentCallbacks callback)
    auto unregisterComponentCallbacks(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "unregisterComponentCallbacks",
                        "(Landroid/content/ComponentCallbacks;)V", callback);
    }


    // method: public final android.window.SplashScreen getSplashScreen()
    auto getSplashScreen() const {
        return m_jniObject.callMethod<jobject>(
                        "getSplashScreen",
                        "()Landroid/window/SplashScreen;");
    }


    // method: public void onCreate(android.os.Bundle savedInstanceState, android.os.PersistableBundle persistentState)
    auto onCreate(jobject savedInstanceState, jobject persistentState) const {
        m_jniObject.callMethod<void>(
                        "onCreate",
                        "(Landroid/os/Bundle;Landroid/os/PersistableBundle;)V", savedInstanceState, persistentState);
    }


    // method: public void onRestoreInstanceState(android.os.Bundle savedInstanceState, android.os.PersistableBundle persistentState)
    auto onRestoreInstanceState(jobject savedInstanceState, jobject persistentState) const {
        m_jniObject.callMethod<void>(
                        "onRestoreInstanceState",
                        "(Landroid/os/Bundle;Landroid/os/PersistableBundle;)V", savedInstanceState, persistentState);
    }


    // method: public void onPostCreate(android.os.Bundle savedInstanceState, android.os.PersistableBundle persistentState)
    auto onPostCreate(jobject savedInstanceState, jobject persistentState) const {
        m_jniObject.callMethod<void>(
                        "onPostCreate",
                        "(Landroid/os/Bundle;Landroid/os/PersistableBundle;)V", savedInstanceState, persistentState);
    }


    // method: public void onStateNotSaved()
    auto onStateNotSaved() const {
        m_jniObject.callMethod<void>(
                        "onStateNotSaved",
                        "()V");
    }


    // method: public void onTopResumedActivityChanged(boolean isTopResumedActivity)
    auto onTopResumedActivityChanged(jboolean isTopResumedActivity) const {
        m_jniObject.callMethod<void>(
                        "onTopResumedActivityChanged",
                        "(Z)V", isTopResumedActivity);
    }


    // method: public boolean isVoiceInteraction()
    auto isVoiceInteraction() const {
        return m_jniObject.callMethod<jboolean>(
                        "isVoiceInteraction",
                        "()Z");
    }


    // method: public boolean isVoiceInteractionRoot()
    auto isVoiceInteractionRoot() const {
        return m_jniObject.callMethod<jboolean>(
                        "isVoiceInteractionRoot",
                        "()Z");
    }


    // method: public android.app.VoiceInteractor getVoiceInteractor()
    auto getVoiceInteractor() const {
        return m_jniObject.callMethod<jobject>(
                        "getVoiceInteractor",
                        "()Landroid/app/VoiceInteractor;");
    }


    // method: public boolean isLocalVoiceInteractionSupported()
    auto isLocalVoiceInteractionSupported() const {
        return m_jniObject.callMethod<jboolean>(
                        "isLocalVoiceInteractionSupported",
                        "()Z");
    }


    // method: public void startLocalVoiceInteraction(android.os.Bundle privateOptions)
    auto startLocalVoiceInteraction(jobject privateOptions) const {
        m_jniObject.callMethod<void>(
                        "startLocalVoiceInteraction",
                        "(Landroid/os/Bundle;)V", privateOptions);
    }


    // method: public void onLocalVoiceInteractionStarted()
    auto onLocalVoiceInteractionStarted() const {
        m_jniObject.callMethod<void>(
                        "onLocalVoiceInteractionStarted",
                        "()V");
    }


    // method: public void onLocalVoiceInteractionStopped()
    auto onLocalVoiceInteractionStopped() const {
        m_jniObject.callMethod<void>(
                        "onLocalVoiceInteractionStopped",
                        "()V");
    }


    // method: public void stopLocalVoiceInteraction()
    auto stopLocalVoiceInteraction() const {
        m_jniObject.callMethod<void>(
                        "stopLocalVoiceInteraction",
                        "()V");
    }


    // method: public void onNewIntent(android.content.Intent intent, android.app.ComponentCaller caller)
    auto onNewIntent(jobject intent, jobject caller) const {
        m_jniObject.callMethod<void>(
                        "onNewIntent",
                        "(Landroid/content/Intent;Landroid/app/ComponentCaller;)V", intent, caller);
    }


    // method: public void onSaveInstanceState(android.os.Bundle outState, android.os.PersistableBundle outPersistentState)
    auto onSaveInstanceState(jobject outState, jobject outPersistentState) const {
        m_jniObject.callMethod<void>(
                        "onSaveInstanceState",
                        "(Landroid/os/Bundle;Landroid/os/PersistableBundle;)V", outState, outPersistentState);
    }


    // method: public boolean onCreateThumbnail(android.graphics.Bitmap outBitmap, android.graphics.Canvas canvas)
    auto onCreateThumbnail(jobject outBitmap, jobject canvas) const {
        return m_jniObject.callMethod<jboolean>(
                        "onCreateThumbnail",
                        "(Landroid/graphics/Bitmap;Landroid/graphics/Canvas;)Z", outBitmap, canvas);
    }


    // method: public java.lang.CharSequence onCreateDescription()
    auto onCreateDescription() const {
        return m_jniObject.callMethod<jobject>(
                        "onCreateDescription",
                        "()Ljava/lang/CharSequence;");
    }


    // method: public void onProvideAssistData(android.os.Bundle data)
    auto onProvideAssistData(jobject data) const {
        m_jniObject.callMethod<void>(
                        "onProvideAssistData",
                        "(Landroid/os/Bundle;)V", data);
    }


    // method: public void onProvideAssistContent(android.app.assist.AssistContent outContent)
    auto onProvideAssistContent(jobject outContent) const {
        m_jniObject.callMethod<void>(
                        "onProvideAssistContent",
                        "(Landroid/app/assist/AssistContent;)V", outContent);
    }


    // method: public void onGetDirectActions(android.os.CancellationSignal cancellationSignal, java.util.function.Consumer<java.util.List<android.app.DirectAction>> callback)
    auto onGetDirectActions(jobject cancellationSignal, jobject callback) const {
        m_jniObject.callMethod<void>(
                        "onGetDirectActions",
                        "(Landroid/os/CancellationSignal;Ljava/util/function/Consumer;)V", cancellationSignal, callback);
    }


    // method: public void onPerformDirectAction(java.lang.String actionId, android.os.Bundle arguments, android.os.CancellationSignal cancellationSignal, java.util.function.Consumer<android.os.Bundle> resultListener)
    auto onPerformDirectAction(jstring actionId, jobject arguments, jobject cancellationSignal, jobject resultListener) const {
        m_jniObject.callMethod<void>(
                        "onPerformDirectAction",
                        "(Ljava/lang/String;Landroid/os/Bundle;Landroid/os/CancellationSignal;Ljava/util/function/Consumer;)V", actionId, arguments, cancellationSignal, resultListener);
    }


    // method: public final void requestShowKeyboardShortcuts()
    auto requestShowKeyboardShortcuts() const {
        m_jniObject.callMethod<void>(
                        "requestShowKeyboardShortcuts",
                        "()V");
    }


    // method: public final void dismissKeyboardShortcutsHelper()
    auto dismissKeyboardShortcutsHelper() const {
        m_jniObject.callMethod<void>(
                        "dismissKeyboardShortcutsHelper",
                        "()V");
    }


    // method: public void onProvideKeyboardShortcuts(java.util.List<android.view.KeyboardShortcutGroup> data, android.view.Menu menu, int deviceId)
    auto onProvideKeyboardShortcuts(jobject data, jobject menu, jint deviceId) const {
        m_jniObject.callMethod<void>(
                        "onProvideKeyboardShortcuts",
                        "(Ljava/util/List;Landroid/view/Menu;I)V", data, menu, deviceId);
    }


    // method: public boolean showAssist(android.os.Bundle args)
    auto showAssist(jobject args) const {
        return m_jniObject.callMethod<jboolean>(
                        "showAssist",
                        "(Landroid/os/Bundle;)Z", args);
    }


    // method: public void reportFullyDrawn()
    auto reportFullyDrawn() const {
        m_jniObject.callMethod<void>(
                        "reportFullyDrawn",
                        "()V");
    }


    // method: public void onMultiWindowModeChanged(boolean isInMultiWindowMode, android.content.res.Configuration newConfig)
    auto onMultiWindowModeChanged(jboolean isInMultiWindowMode, jobject newConfig) const {
        m_jniObject.callMethod<void>(
                        "onMultiWindowModeChanged",
                        "(ZLandroid/content/res/Configuration;)V", isInMultiWindowMode, newConfig);
    }


    // method: public void onMultiWindowModeChanged(boolean isInMultiWindowMode)
    auto onMultiWindowModeChanged(jboolean isInMultiWindowMode) const {
        m_jniObject.callMethod<void>(
                        "onMultiWindowModeChanged",
                        "(Z)V", isInMultiWindowMode);
    }


    // method: public boolean isInMultiWindowMode()
    auto isInMultiWindowMode() const {
        return m_jniObject.callMethod<jboolean>(
                        "isInMultiWindowMode",
                        "()Z");
    }


    // method: public void onPictureInPictureModeChanged(boolean isInPictureInPictureMode, android.content.res.Configuration newConfig)
    auto onPictureInPictureModeChanged(jboolean isInPictureInPictureMode, jobject newConfig) const {
        m_jniObject.callMethod<void>(
                        "onPictureInPictureModeChanged",
                        "(ZLandroid/content/res/Configuration;)V", isInPictureInPictureMode, newConfig);
    }


    // method: public void onPictureInPictureModeChanged(boolean isInPictureInPictureMode)
    auto onPictureInPictureModeChanged(jboolean isInPictureInPictureMode) const {
        m_jniObject.callMethod<void>(
                        "onPictureInPictureModeChanged",
                        "(Z)V", isInPictureInPictureMode);
    }


    // method: public void onPictureInPictureUiStateChanged(android.app.PictureInPictureUiState pipState)
    auto onPictureInPictureUiStateChanged(jobject pipState) const {
        m_jniObject.callMethod<void>(
                        "onPictureInPictureUiStateChanged",
                        "(Landroid/app/PictureInPictureUiState;)V", pipState);
    }


    // method: public boolean isInPictureInPictureMode()
    auto isInPictureInPictureMode() const {
        return m_jniObject.callMethod<jboolean>(
                        "isInPictureInPictureMode",
                        "()Z");
    }


    // method: public void enterPictureInPictureMode()
    auto enterPictureInPictureMode() const {
        m_jniObject.callMethod<void>(
                        "enterPictureInPictureMode",
                        "()V");
    }


    // method: public boolean enterPictureInPictureMode(android.app.PictureInPictureParams params)
    auto enterPictureInPictureMode(jobject params) const {
        return m_jniObject.callMethod<jboolean>(
                        "enterPictureInPictureMode",
                        "(Landroid/app/PictureInPictureParams;)Z", params);
    }


    // method: public void setPictureInPictureParams(android.app.PictureInPictureParams params)
    auto setPictureInPictureParams(jobject params) const {
        m_jniObject.callMethod<void>(
                        "setPictureInPictureParams",
                        "(Landroid/app/PictureInPictureParams;)V", params);
    }


    // method: public int getMaxNumPictureInPictureActions()
    auto getMaxNumPictureInPictureActions() const {
        return m_jniObject.callMethod<jint>(
                        "getMaxNumPictureInPictureActions",
                        "()I");
    }


    // method: public boolean onPictureInPictureRequested()
    auto onPictureInPictureRequested() const {
        return m_jniObject.callMethod<jboolean>(
                        "onPictureInPictureRequested",
                        "()Z");
    }


    // method: public void requestFullscreenMode(int request, android.os.OutcomeReceiver<java.lang.Void,java.lang.Throwable> approvalCallback)
    auto requestFullscreenMode(jint request, jobject approvalCallback) const {
        m_jniObject.callMethod<void>(
                        "requestFullscreenMode",
                        "(ILandroid/os/OutcomeReceiver;)V", request, approvalCallback);
    }


    // method: public void setShouldDockBigOverlays(boolean shouldDockBigOverlays)
    auto setShouldDockBigOverlays(jboolean shouldDockBigOverlays) const {
        m_jniObject.callMethod<void>(
                        "setShouldDockBigOverlays",
                        "(Z)V", shouldDockBigOverlays);
    }


    // method: public boolean shouldDockBigOverlays()
    auto shouldDockBigOverlays() const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldDockBigOverlays",
                        "()Z");
    }


    // method: public void onConfigurationChanged(android.content.res.Configuration newConfig)
    auto onConfigurationChanged(jobject newConfig) const {
        m_jniObject.callMethod<void>(
                        "onConfigurationChanged",
                        "(Landroid/content/res/Configuration;)V", newConfig);
    }


    // method: public int getChangingConfigurations()
    auto getChangingConfigurations() const {
        return m_jniObject.callMethod<jint>(
                        "getChangingConfigurations",
                        "()I");
    }


    // method: public java.lang.Object getLastNonConfigurationInstance()
    auto getLastNonConfigurationInstance() const {
        return m_jniObject.callMethod<jobject>(
                        "getLastNonConfigurationInstance",
                        "()Ljava/lang/Object;");
    }


    // method: public java.lang.Object onRetainNonConfigurationInstance()
    auto onRetainNonConfigurationInstance() const {
        return m_jniObject.callMethod<jobject>(
                        "onRetainNonConfigurationInstance",
                        "()Ljava/lang/Object;");
    }


    // method: public void onLowMemory()
    auto onLowMemory() const {
        m_jniObject.callMethod<void>(
                        "onLowMemory",
                        "()V");
    }


    // method: public void onTrimMemory(int level)
    auto onTrimMemory(jint level) const {
        m_jniObject.callMethod<void>(
                        "onTrimMemory",
                        "(I)V", level);
    }


    // method: public android.app.FragmentManager getFragmentManager()
    auto getFragmentManager() const {
        return m_jniObject.callMethod<jobject>(
                        "getFragmentManager",
                        "()Landroid/app/FragmentManager;");
    }


    // method: public void onAttachFragment(android.app.Fragment fragment)
    auto onAttachFragment(jobject fragment) const {
        m_jniObject.callMethod<void>(
                        "onAttachFragment",
                        "(Landroid/app/Fragment;)V", fragment);
    }


    // method: public final android.database.Cursor managedQuery(android.net.Uri uri, java.lang.String[] projection, java.lang.String selection, java.lang.String[] selectionArgs, java.lang.String sortOrder)
    auto managedQuery(jobject uri, jobjectArray projection, jstring selection, jobjectArray selectionArgs, jstring sortOrder) const {
        return m_jniObject.callMethod<jobject>(
                        "managedQuery",
                        "(Landroid/net/Uri;[Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)Landroid/database/Cursor;", uri, projection, selection, selectionArgs, sortOrder);
    }


    // method: public void startManagingCursor(android.database.Cursor c)
    auto startManagingCursor(jobject c) const {
        m_jniObject.callMethod<void>(
                        "startManagingCursor",
                        "(Landroid/database/Cursor;)V", c);
    }


    // method: public void stopManagingCursor(android.database.Cursor c)
    auto stopManagingCursor(jobject c) const {
        m_jniObject.callMethod<void>(
                        "stopManagingCursor",
                        "(Landroid/database/Cursor;)V", c);
    }


    // method: public T findViewById(int id)
    auto findViewById(jint id) const {
        return m_jniObject.callMethod<jobject>(
                        "findViewById",
                        "(I)Landroid/view/View;", id);
    }


    // method: public final T requireViewById(int id)
    auto requireViewById(jint id) const {
        return m_jniObject.callMethod<jobject>(
                        "requireViewById",
                        "(I)Landroid/view/View;", id);
    }


    // method: public android.app.ActionBar getActionBar()
    auto getActionBar() const {
        return m_jniObject.callMethod<jobject>(
                        "getActionBar",
                        "()Landroid/app/ActionBar;");
    }


    // method: public void setActionBar(android.widget.Toolbar toolbar)
    auto setActionBar(jobject toolbar) const {
        m_jniObject.callMethod<void>(
                        "setActionBar",
                        "(Landroid/widget/Toolbar;)V", toolbar);
    }


    // method: public void setContentView(int layoutResID)
    auto setContentView(jint layoutResID) const {
        m_jniObject.callMethod<void>(
                        "setContentView",
                        "(I)V", layoutResID);
    }


    // method: public void setContentView(android.view.View view)
    auto setContentView(jobject view) const {
        m_jniObject.callMethod<void>(
                        "setContentView",
                        "(Landroid/view/View;)V", view);
    }


    // method: public void setContentView(android.view.View view, android.view.ViewGroup.LayoutParams params)
    auto setContentView(jobject view, jobject params) const {
        m_jniObject.callMethod<void>(
                        "setContentView",
                        "(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V", view, params);
    }


    // method: public void addContentView(android.view.View view, android.view.ViewGroup.LayoutParams params)
    auto addContentView(jobject view, jobject params) const {
        m_jniObject.callMethod<void>(
                        "addContentView",
                        "(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V", view, params);
    }


    // method: public android.transition.TransitionManager getContentTransitionManager()
    auto getContentTransitionManager() const {
        return m_jniObject.callMethod<jobject>(
                        "getContentTransitionManager",
                        "()Landroid/transition/TransitionManager;");
    }


    // method: public void setContentTransitionManager(android.transition.TransitionManager tm)
    auto setContentTransitionManager(jobject tm) const {
        m_jniObject.callMethod<void>(
                        "setContentTransitionManager",
                        "(Landroid/transition/TransitionManager;)V", tm);
    }


    // method: public android.transition.Scene getContentScene()
    auto getContentScene() const {
        return m_jniObject.callMethod<jobject>(
                        "getContentScene",
                        "()Landroid/transition/Scene;");
    }


    // method: public void setFinishOnTouchOutside(boolean finish)
    auto setFinishOnTouchOutside(jboolean finish) const {
        m_jniObject.callMethod<void>(
                        "setFinishOnTouchOutside",
                        "(Z)V", finish);
    }


    // method: public final void setDefaultKeyMode(int mode)
    auto setDefaultKeyMode(jint mode) const {
        m_jniObject.callMethod<void>(
                        "setDefaultKeyMode",
                        "(I)V", mode);
    }


    // method: public boolean onKeyDown(int keyCode, android.view.KeyEvent event)
    auto onKeyDown(jint keyCode, jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onKeyDown",
                        "(ILandroid/view/KeyEvent;)Z", keyCode, event);
    }


    // method: public boolean onKeyLongPress(int keyCode, android.view.KeyEvent event)
    auto onKeyLongPress(jint keyCode, jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onKeyLongPress",
                        "(ILandroid/view/KeyEvent;)Z", keyCode, event);
    }


    // method: public boolean onKeyUp(int keyCode, android.view.KeyEvent event)
    auto onKeyUp(jint keyCode, jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onKeyUp",
                        "(ILandroid/view/KeyEvent;)Z", keyCode, event);
    }


    // method: public boolean onKeyMultiple(int keyCode, int repeatCount, android.view.KeyEvent event)
    auto onKeyMultiple(jint keyCode, jint repeatCount, jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onKeyMultiple",
                        "(IILandroid/view/KeyEvent;)Z", keyCode, repeatCount, event);
    }


    // method: public void onBackPressed()
    auto onBackPressed() const {
        m_jniObject.callMethod<void>(
                        "onBackPressed",
                        "()V");
    }


    // method: public boolean onKeyShortcut(int keyCode, android.view.KeyEvent event)
    auto onKeyShortcut(jint keyCode, jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onKeyShortcut",
                        "(ILandroid/view/KeyEvent;)Z", keyCode, event);
    }


    // method: public boolean onTouchEvent(android.view.MotionEvent event)
    auto onTouchEvent(jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onTouchEvent",
                        "(Landroid/view/MotionEvent;)Z", event);
    }


    // method: public boolean onTrackballEvent(android.view.MotionEvent event)
    auto onTrackballEvent(jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onTrackballEvent",
                        "(Landroid/view/MotionEvent;)Z", event);
    }


    // method: public boolean onGenericMotionEvent(android.view.MotionEvent event)
    auto onGenericMotionEvent(jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "onGenericMotionEvent",
                        "(Landroid/view/MotionEvent;)Z", event);
    }


    // method: public void onUserInteraction()
    auto onUserInteraction() const {
        m_jniObject.callMethod<void>(
                        "onUserInteraction",
                        "()V");
    }


    // method: public void onWindowAttributesChanged(android.view.WindowManager.LayoutParams params)
    auto onWindowAttributesChanged(jobject params) const {
        m_jniObject.callMethod<void>(
                        "onWindowAttributesChanged",
                        "(Landroid/view/WindowManager$LayoutParams;)V", params);
    }


    // method: public void onContentChanged()
    auto onContentChanged() const {
        m_jniObject.callMethod<void>(
                        "onContentChanged",
                        "()V");
    }


    // method: public void onWindowFocusChanged(boolean hasFocus)
    auto onWindowFocusChanged(jboolean hasFocus) const {
        m_jniObject.callMethod<void>(
                        "onWindowFocusChanged",
                        "(Z)V", hasFocus);
    }


    // method: public void onAttachedToWindow()
    auto onAttachedToWindow() const {
        m_jniObject.callMethod<void>(
                        "onAttachedToWindow",
                        "()V");
    }


    // method: public void onDetachedFromWindow()
    auto onDetachedFromWindow() const {
        m_jniObject.callMethod<void>(
                        "onDetachedFromWindow",
                        "()V");
    }


    // method: public boolean hasWindowFocus()
    auto hasWindowFocus() const {
        return m_jniObject.callMethod<jboolean>(
                        "hasWindowFocus",
                        "()Z");
    }


    // method: public boolean dispatchKeyEvent(android.view.KeyEvent event)
    auto dispatchKeyEvent(jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "dispatchKeyEvent",
                        "(Landroid/view/KeyEvent;)Z", event);
    }


    // method: public boolean dispatchKeyShortcutEvent(android.view.KeyEvent event)
    auto dispatchKeyShortcutEvent(jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "dispatchKeyShortcutEvent",
                        "(Landroid/view/KeyEvent;)Z", event);
    }


    // method: public boolean dispatchTouchEvent(android.view.MotionEvent ev)
    auto dispatchTouchEvent(jobject ev) const {
        return m_jniObject.callMethod<jboolean>(
                        "dispatchTouchEvent",
                        "(Landroid/view/MotionEvent;)Z", ev);
    }


    // method: public boolean dispatchTrackballEvent(android.view.MotionEvent ev)
    auto dispatchTrackballEvent(jobject ev) const {
        return m_jniObject.callMethod<jboolean>(
                        "dispatchTrackballEvent",
                        "(Landroid/view/MotionEvent;)Z", ev);
    }


    // method: public boolean dispatchGenericMotionEvent(android.view.MotionEvent ev)
    auto dispatchGenericMotionEvent(jobject ev) const {
        return m_jniObject.callMethod<jboolean>(
                        "dispatchGenericMotionEvent",
                        "(Landroid/view/MotionEvent;)Z", ev);
    }


    // method: public boolean dispatchPopulateAccessibilityEvent(android.view.accessibility.AccessibilityEvent event)
    auto dispatchPopulateAccessibilityEvent(jobject event) const {
        return m_jniObject.callMethod<jboolean>(
                        "dispatchPopulateAccessibilityEvent",
                        "(Landroid/view/accessibility/AccessibilityEvent;)Z", event);
    }


    // method: public android.view.View onCreatePanelView(int featureId)
    auto onCreatePanelView(jint featureId) const {
        return m_jniObject.callMethod<jobject>(
                        "onCreatePanelView",
                        "(I)Landroid/view/View;", featureId);
    }


    // method: public boolean onCreatePanelMenu(int featureId, android.view.Menu menu)
    auto onCreatePanelMenu(jint featureId, jobject menu) const {
        return m_jniObject.callMethod<jboolean>(
                        "onCreatePanelMenu",
                        "(ILandroid/view/Menu;)Z", featureId, menu);
    }


    // method: public boolean onPreparePanel(int featureId, android.view.View view, android.view.Menu menu)
    auto onPreparePanel(jint featureId, jobject view, jobject menu) const {
        return m_jniObject.callMethod<jboolean>(
                        "onPreparePanel",
                        "(ILandroid/view/View;Landroid/view/Menu;)Z", featureId, view, menu);
    }


    // method: public boolean onMenuOpened(int featureId, android.view.Menu menu)
    auto onMenuOpened(jint featureId, jobject menu) const {
        return m_jniObject.callMethod<jboolean>(
                        "onMenuOpened",
                        "(ILandroid/view/Menu;)Z", featureId, menu);
    }


    // method: public boolean onMenuItemSelected(int featureId, android.view.MenuItem item)
    auto onMenuItemSelected(jint featureId, jobject item) const {
        return m_jniObject.callMethod<jboolean>(
                        "onMenuItemSelected",
                        "(ILandroid/view/MenuItem;)Z", featureId, item);
    }


    // method: public void onPanelClosed(int featureId, android.view.Menu menu)
    auto onPanelClosed(jint featureId, jobject menu) const {
        m_jniObject.callMethod<void>(
                        "onPanelClosed",
                        "(ILandroid/view/Menu;)V", featureId, menu);
    }


    // method: public void invalidateOptionsMenu()
    auto invalidateOptionsMenu() const {
        m_jniObject.callMethod<void>(
                        "invalidateOptionsMenu",
                        "()V");
    }


    // method: public boolean onCreateOptionsMenu(android.view.Menu menu)
    auto onCreateOptionsMenu(jobject menu) const {
        return m_jniObject.callMethod<jboolean>(
                        "onCreateOptionsMenu",
                        "(Landroid/view/Menu;)Z", menu);
    }


    // method: public boolean onPrepareOptionsMenu(android.view.Menu menu)
    auto onPrepareOptionsMenu(jobject menu) const {
        return m_jniObject.callMethod<jboolean>(
                        "onPrepareOptionsMenu",
                        "(Landroid/view/Menu;)Z", menu);
    }


    // method: public boolean onOptionsItemSelected(android.view.MenuItem item)
    auto onOptionsItemSelected(jobject item) const {
        return m_jniObject.callMethod<jboolean>(
                        "onOptionsItemSelected",
                        "(Landroid/view/MenuItem;)Z", item);
    }


    // method: public boolean onNavigateUp()
    auto onNavigateUp() const {
        return m_jniObject.callMethod<jboolean>(
                        "onNavigateUp",
                        "()Z");
    }


    // method: public boolean onNavigateUpFromChild(android.app.Activity child)
    auto onNavigateUpFromChild(jobject child) const {
        return m_jniObject.callMethod<jboolean>(
                        "onNavigateUpFromChild",
                        "(Landroid/app/Activity;)Z", child);
    }


    // method: public void onCreateNavigateUpTaskStack(android.app.TaskStackBuilder builder)
    auto onCreateNavigateUpTaskStack(jobject builder) const {
        m_jniObject.callMethod<void>(
                        "onCreateNavigateUpTaskStack",
                        "(Landroid/app/TaskStackBuilder;)V", builder);
    }


    // method: public void onPrepareNavigateUpTaskStack(android.app.TaskStackBuilder builder)
    auto onPrepareNavigateUpTaskStack(jobject builder) const {
        m_jniObject.callMethod<void>(
                        "onPrepareNavigateUpTaskStack",
                        "(Landroid/app/TaskStackBuilder;)V", builder);
    }


    // method: public void onOptionsMenuClosed(android.view.Menu menu)
    auto onOptionsMenuClosed(jobject menu) const {
        m_jniObject.callMethod<void>(
                        "onOptionsMenuClosed",
                        "(Landroid/view/Menu;)V", menu);
    }


    // method: public void openOptionsMenu()
    auto openOptionsMenu() const {
        m_jniObject.callMethod<void>(
                        "openOptionsMenu",
                        "()V");
    }


    // method: public void closeOptionsMenu()
    auto closeOptionsMenu() const {
        m_jniObject.callMethod<void>(
                        "closeOptionsMenu",
                        "()V");
    }


    // method: public void onCreateContextMenu(android.view.ContextMenu menu, android.view.View v, android.view.ContextMenu.ContextMenuInfo menuInfo)
    auto onCreateContextMenu(jobject menu, jobject v, jobject menuInfo) const {
        m_jniObject.callMethod<void>(
                        "onCreateContextMenu",
                        "(Landroid/view/ContextMenu;Landroid/view/View;Landroid/view/ContextMenu$ContextMenuInfo;)V", menu, v, menuInfo);
    }


    // method: public void registerForContextMenu(android.view.View view)
    auto registerForContextMenu(jobject view) const {
        m_jniObject.callMethod<void>(
                        "registerForContextMenu",
                        "(Landroid/view/View;)V", view);
    }


    // method: public void unregisterForContextMenu(android.view.View view)
    auto unregisterForContextMenu(jobject view) const {
        m_jniObject.callMethod<void>(
                        "unregisterForContextMenu",
                        "(Landroid/view/View;)V", view);
    }


    // method: public void openContextMenu(android.view.View view)
    auto openContextMenu(jobject view) const {
        m_jniObject.callMethod<void>(
                        "openContextMenu",
                        "(Landroid/view/View;)V", view);
    }


    // method: public void closeContextMenu()
    auto closeContextMenu() const {
        m_jniObject.callMethod<void>(
                        "closeContextMenu",
                        "()V");
    }


    // method: public boolean onContextItemSelected(android.view.MenuItem item)
    auto onContextItemSelected(jobject item) const {
        return m_jniObject.callMethod<jboolean>(
                        "onContextItemSelected",
                        "(Landroid/view/MenuItem;)Z", item);
    }


    // method: public void onContextMenuClosed(android.view.Menu menu)
    auto onContextMenuClosed(jobject menu) const {
        m_jniObject.callMethod<void>(
                        "onContextMenuClosed",
                        "(Landroid/view/Menu;)V", menu);
    }


    // method: public final void showDialog(int id)
    auto showDialog(jint id) const {
        m_jniObject.callMethod<void>(
                        "showDialog",
                        "(I)V", id);
    }


    // method: public final boolean showDialog(int id, android.os.Bundle args)
    auto showDialog(jint id, jobject args) const {
        return m_jniObject.callMethod<jboolean>(
                        "showDialog",
                        "(ILandroid/os/Bundle;)Z", id, args);
    }


    // method: public final void dismissDialog(int id)
    auto dismissDialog(jint id) const {
        m_jniObject.callMethod<void>(
                        "dismissDialog",
                        "(I)V", id);
    }


    // method: public final void removeDialog(int id)
    auto removeDialog(jint id) const {
        m_jniObject.callMethod<void>(
                        "removeDialog",
                        "(I)V", id);
    }


    // method: public boolean onSearchRequested(android.view.SearchEvent searchEvent)
    auto onSearchRequested(jobject searchEvent) const {
        return m_jniObject.callMethod<jboolean>(
                        "onSearchRequested",
                        "(Landroid/view/SearchEvent;)Z", searchEvent);
    }


    // method: public boolean onSearchRequested()
    auto onSearchRequested() const {
        return m_jniObject.callMethod<jboolean>(
                        "onSearchRequested",
                        "()Z");
    }


    // method: public final android.view.SearchEvent getSearchEvent()
    auto getSearchEvent() const {
        return m_jniObject.callMethod<jobject>(
                        "getSearchEvent",
                        "()Landroid/view/SearchEvent;");
    }


    // method: public void startSearch(java.lang.String initialQuery, boolean selectInitialQuery, android.os.Bundle appSearchData, boolean globalSearch)
    auto startSearch(jstring initialQuery, jboolean selectInitialQuery, jobject appSearchData, jboolean globalSearch) const {
        m_jniObject.callMethod<void>(
                        "startSearch",
                        "(Ljava/lang/String;ZLandroid/os/Bundle;Z)V", initialQuery, selectInitialQuery, appSearchData, globalSearch);
    }


    // method: public void triggerSearch(java.lang.String query, android.os.Bundle appSearchData)
    auto triggerSearch(jstring query, jobject appSearchData) const {
        m_jniObject.callMethod<void>(
                        "triggerSearch",
                        "(Ljava/lang/String;Landroid/os/Bundle;)V", query, appSearchData);
    }


    // method: public void takeKeyEvents(boolean get)
    auto takeKeyEvents(jboolean get) const {
        m_jniObject.callMethod<void>(
                        "takeKeyEvents",
                        "(Z)V", get);
    }


    // method: public final boolean requestWindowFeature(int featureId)
    auto requestWindowFeature(jint featureId) const {
        return m_jniObject.callMethod<jboolean>(
                        "requestWindowFeature",
                        "(I)Z", featureId);
    }


    // method: public final void setFeatureDrawableResource(int featureId, int resId)
    auto setFeatureDrawableResource(jint featureId, jint resId) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawableResource",
                        "(II)V", featureId, resId);
    }


    // method: public final void setFeatureDrawableUri(int featureId, android.net.Uri uri)
    auto setFeatureDrawableUri(jint featureId, jobject uri) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawableUri",
                        "(ILandroid/net/Uri;)V", featureId, uri);
    }


    // method: public final void setFeatureDrawable(int featureId, android.graphics.drawable.Drawable drawable)
    auto setFeatureDrawable(jint featureId, jobject drawable) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawable",
                        "(ILandroid/graphics/drawable/Drawable;)V", featureId, drawable);
    }


    // method: public final void setFeatureDrawableAlpha(int featureId, int alpha)
    auto setFeatureDrawableAlpha(jint featureId, jint alpha) const {
        m_jniObject.callMethod<void>(
                        "setFeatureDrawableAlpha",
                        "(II)V", featureId, alpha);
    }


    // method: public android.view.LayoutInflater getLayoutInflater()
    auto getLayoutInflater() const {
        return m_jniObject.callMethod<jobject>(
                        "getLayoutInflater",
                        "()Landroid/view/LayoutInflater;");
    }


    // method: public android.view.MenuInflater getMenuInflater()
    auto getMenuInflater() const {
        return m_jniObject.callMethod<jobject>(
                        "getMenuInflater",
                        "()Landroid/view/MenuInflater;");
    }


    // method: public void setTheme(int resid)
    auto setTheme(jint resid) const {
        m_jniObject.callMethod<void>(
                        "setTheme",
                        "(I)V", resid);
    }


    // method: public final void requestPermissions(java.lang.String[] permissions, int requestCode)
    auto requestPermissions(jobjectArray permissions, jint requestCode) const {
        m_jniObject.callMethod<void>(
                        "requestPermissions",
                        "([Ljava/lang/String;I)V", permissions, requestCode);
    }


    // method: public final void requestPermissions(java.lang.String[] permissions, int requestCode, int deviceId)
    auto requestPermissions(jobjectArray permissions, jint requestCode, jint deviceId) const {
        m_jniObject.callMethod<void>(
                        "requestPermissions",
                        "([Ljava/lang/String;II)V", permissions, requestCode, deviceId);
    }


    // method: public void onRequestPermissionsResult(int requestCode, java.lang.String[] permissions, int[] grantResults)
    auto onRequestPermissionsResult(jint requestCode, jobjectArray permissions, jintArray grantResults) const {
        m_jniObject.callMethod<void>(
                        "onRequestPermissionsResult",
                        "(I[Ljava/lang/String;[I)V", requestCode, permissions, grantResults);
    }


    // method: public void onRequestPermissionsResult(int requestCode, java.lang.String[] permissions, int[] grantResults, int deviceId)
    auto onRequestPermissionsResult(jint requestCode, jobjectArray permissions, jintArray grantResults, jint deviceId) const {
        m_jniObject.callMethod<void>(
                        "onRequestPermissionsResult",
                        "(I[Ljava/lang/String;[II)V", requestCode, permissions, grantResults, deviceId);
    }


    // method: public boolean shouldShowRequestPermissionRationale(java.lang.String permission)
    auto shouldShowRequestPermissionRationale(jstring permission) const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldShowRequestPermissionRationale",
                        "(Ljava/lang/String;)Z", permission);
    }


    // method: public boolean shouldShowRequestPermissionRationale(java.lang.String permission, int deviceId)
    auto shouldShowRequestPermissionRationale(jstring permission, jint deviceId) const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldShowRequestPermissionRationale",
                        "(Ljava/lang/String;I)Z", permission, deviceId);
    }


    // method: public void startActivityForResult(android.content.Intent intent, int requestCode)
    auto startActivityForResult(jobject intent, jint requestCode) const {
        m_jniObject.callMethod<void>(
                        "startActivityForResult",
                        "(Landroid/content/Intent;I)V", intent, requestCode);
    }


    // method: public void startActivityForResult(android.content.Intent intent, int requestCode, android.os.Bundle options)
    auto startActivityForResult(jobject intent, jint requestCode, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startActivityForResult",
                        "(Landroid/content/Intent;ILandroid/os/Bundle;)V", intent, requestCode, options);
    }


    // method: public boolean isActivityTransitionRunning()
    auto isActivityTransitionRunning() const {
        return m_jniObject.callMethod<jboolean>(
                        "isActivityTransitionRunning",
                        "()Z");
    }


    // method: public void startIntentSenderForResult(android.content.IntentSender intent, int requestCode, android.content.Intent fillInIntent, int flagsMask, int flagsValues, int extraFlags)
    auto startIntentSenderForResult(jobject intent, jint requestCode, jobject fillInIntent, jint flagsMask, jint flagsValues, jint extraFlags) const {
        m_jniObject.callMethod<void>(
                        "startIntentSenderForResult",
                        "(Landroid/content/IntentSender;ILandroid/content/Intent;III)V", intent, requestCode, fillInIntent, flagsMask, flagsValues, extraFlags);
    }


    // method: public void startIntentSenderForResult(android.content.IntentSender intent, int requestCode, android.content.Intent fillInIntent, int flagsMask, int flagsValues, int extraFlags, android.os.Bundle options)
    auto startIntentSenderForResult(jobject intent, jint requestCode, jobject fillInIntent, jint flagsMask, jint flagsValues, jint extraFlags, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startIntentSenderForResult",
                        "(Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V", intent, requestCode, fillInIntent, flagsMask, flagsValues, extraFlags, options);
    }


    // method: public void startActivity(android.content.Intent intent)
    auto startActivity(jobject intent) const {
        m_jniObject.callMethod<void>(
                        "startActivity",
                        "(Landroid/content/Intent;)V", intent);
    }


    // method: public void startActivity(android.content.Intent intent, android.os.Bundle options)
    auto startActivity(jobject intent, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startActivity",
                        "(Landroid/content/Intent;Landroid/os/Bundle;)V", intent, options);
    }


    // method: public void startActivities(android.content.Intent[] intents)
    auto startActivities(jobjectArray intents) const {
        m_jniObject.callMethod<void>(
                        "startActivities",
                        "([Landroid/content/Intent;)V", intents);
    }


    // method: public void startActivities(android.content.Intent[] intents, android.os.Bundle options)
    auto startActivities(jobjectArray intents, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startActivities",
                        "([Landroid/content/Intent;Landroid/os/Bundle;)V", intents, options);
    }


    // method: public void startIntentSender(android.content.IntentSender intent, android.content.Intent fillInIntent, int flagsMask, int flagsValues, int extraFlags)
    auto startIntentSender(jobject intent, jobject fillInIntent, jint flagsMask, jint flagsValues, jint extraFlags) const {
        m_jniObject.callMethod<void>(
                        "startIntentSender",
                        "(Landroid/content/IntentSender;Landroid/content/Intent;III)V", intent, fillInIntent, flagsMask, flagsValues, extraFlags);
    }


    // method: public void startIntentSender(android.content.IntentSender intent, android.content.Intent fillInIntent, int flagsMask, int flagsValues, int extraFlags, android.os.Bundle options)
    auto startIntentSender(jobject intent, jobject fillInIntent, jint flagsMask, jint flagsValues, jint extraFlags, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startIntentSender",
                        "(Landroid/content/IntentSender;Landroid/content/Intent;IIILandroid/os/Bundle;)V", intent, fillInIntent, flagsMask, flagsValues, extraFlags, options);
    }


    // method: public boolean startActivityIfNeeded(android.content.Intent intent, int requestCode)
    auto startActivityIfNeeded(jobject intent, jint requestCode) const {
        return m_jniObject.callMethod<jboolean>(
                        "startActivityIfNeeded",
                        "(Landroid/content/Intent;I)Z", intent, requestCode);
    }


    // method: public boolean startActivityIfNeeded(android.content.Intent intent, int requestCode, android.os.Bundle options)
    auto startActivityIfNeeded(jobject intent, jint requestCode, jobject options) const {
        return m_jniObject.callMethod<jboolean>(
                        "startActivityIfNeeded",
                        "(Landroid/content/Intent;ILandroid/os/Bundle;)Z", intent, requestCode, options);
    }


    // method: public boolean startNextMatchingActivity(android.content.Intent intent)
    auto startNextMatchingActivity(jobject intent) const {
        return m_jniObject.callMethod<jboolean>(
                        "startNextMatchingActivity",
                        "(Landroid/content/Intent;)Z", intent);
    }


    // method: public boolean startNextMatchingActivity(android.content.Intent intent, android.os.Bundle options)
    auto startNextMatchingActivity(jobject intent, jobject options) const {
        return m_jniObject.callMethod<jboolean>(
                        "startNextMatchingActivity",
                        "(Landroid/content/Intent;Landroid/os/Bundle;)Z", intent, options);
    }


    // method: public void startActivityFromChild(android.app.Activity child, android.content.Intent intent, int requestCode)
    auto startActivityFromChild(jobject child, jobject intent, jint requestCode) const {
        m_jniObject.callMethod<void>(
                        "startActivityFromChild",
                        "(Landroid/app/Activity;Landroid/content/Intent;I)V", child, intent, requestCode);
    }


    // method: public void startActivityFromChild(android.app.Activity child, android.content.Intent intent, int requestCode, android.os.Bundle options)
    auto startActivityFromChild(jobject child, jobject intent, jint requestCode, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startActivityFromChild",
                        "(Landroid/app/Activity;Landroid/content/Intent;ILandroid/os/Bundle;)V", child, intent, requestCode, options);
    }


    // method: public void startActivityFromFragment(android.app.Fragment fragment, android.content.Intent intent, int requestCode)
    auto startActivityFromFragment(jobject fragment, jobject intent, jint requestCode) const {
        m_jniObject.callMethod<void>(
                        "startActivityFromFragment",
                        "(Landroid/app/Fragment;Landroid/content/Intent;I)V", fragment, intent, requestCode);
    }


    // method: public void startActivityFromFragment(android.app.Fragment fragment, android.content.Intent intent, int requestCode, android.os.Bundle options)
    auto startActivityFromFragment(jobject fragment, jobject intent, jint requestCode, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startActivityFromFragment",
                        "(Landroid/app/Fragment;Landroid/content/Intent;ILandroid/os/Bundle;)V", fragment, intent, requestCode, options);
    }


    // method: public void startIntentSenderFromChild(android.app.Activity child, android.content.IntentSender intent, int requestCode, android.content.Intent fillInIntent, int flagsMask, int flagsValues, int extraFlags)
    auto startIntentSenderFromChild(jobject child, jobject intent, jint requestCode, jobject fillInIntent, jint flagsMask, jint flagsValues, jint extraFlags) const {
        m_jniObject.callMethod<void>(
                        "startIntentSenderFromChild",
                        "(Landroid/app/Activity;Landroid/content/IntentSender;ILandroid/content/Intent;III)V", child, intent, requestCode, fillInIntent, flagsMask, flagsValues, extraFlags);
    }


    // method: public void startIntentSenderFromChild(android.app.Activity child, android.content.IntentSender intent, int requestCode, android.content.Intent fillInIntent, int flagsMask, int flagsValues, int extraFlags, android.os.Bundle options)
    auto startIntentSenderFromChild(jobject child, jobject intent, jint requestCode, jobject fillInIntent, jint flagsMask, jint flagsValues, jint extraFlags, jobject options) const {
        m_jniObject.callMethod<void>(
                        "startIntentSenderFromChild",
                        "(Landroid/app/Activity;Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V", child, intent, requestCode, fillInIntent, flagsMask, flagsValues, extraFlags, options);
    }


    // method: public void overrideActivityTransition(int overrideType, int enterAnim, int exitAnim)
    auto overrideActivityTransition(jint overrideType, jint enterAnim, jint exitAnim) const {
        m_jniObject.callMethod<void>(
                        "overrideActivityTransition",
                        "(III)V", overrideType, enterAnim, exitAnim);
    }


    // method: public void overrideActivityTransition(int overrideType, int enterAnim, int exitAnim, int backgroundColor)
    auto overrideActivityTransition(jint overrideType, jint enterAnim, jint exitAnim, jint backgroundColor) const {
        m_jniObject.callMethod<void>(
                        "overrideActivityTransition",
                        "(IIII)V", overrideType, enterAnim, exitAnim, backgroundColor);
    }


    // method: public void clearOverrideActivityTransition(int overrideType)
    auto clearOverrideActivityTransition(jint overrideType) const {
        m_jniObject.callMethod<void>(
                        "clearOverrideActivityTransition",
                        "(I)V", overrideType);
    }


    // method: public void overridePendingTransition(int enterAnim, int exitAnim)
    auto overridePendingTransition(jint enterAnim, jint exitAnim) const {
        m_jniObject.callMethod<void>(
                        "overridePendingTransition",
                        "(II)V", enterAnim, exitAnim);
    }


    // method: public void overridePendingTransition(int enterAnim, int exitAnim, int backgroundColor)
    auto overridePendingTransition(jint enterAnim, jint exitAnim, jint backgroundColor) const {
        m_jniObject.callMethod<void>(
                        "overridePendingTransition",
                        "(III)V", enterAnim, exitAnim, backgroundColor);
    }


    // method: public final void setResult(int resultCode)
    auto setResult(jint resultCode) const {
        m_jniObject.callMethod<void>(
                        "setResult",
                        "(I)V", resultCode);
    }


    // method: public final void setResult(int resultCode, android.content.Intent data)
    auto setResult(jint resultCode, jobject data) const {
        m_jniObject.callMethod<void>(
                        "setResult",
                        "(ILandroid/content/Intent;)V", resultCode, data);
    }


    // method: public android.net.Uri getReferrer()
    auto getReferrer() const {
        return m_jniObject.callMethod<jobject>(
                        "getReferrer",
                        "()Landroid/net/Uri;");
    }


    // method: public android.net.Uri onProvideReferrer()
    auto onProvideReferrer() const {
        return m_jniObject.callMethod<jobject>(
                        "onProvideReferrer",
                        "()Landroid/net/Uri;");
    }


    // method: public java.lang.String getCallingPackage()
    auto getCallingPackage() const {
        return m_jniObject.callMethod<jstring>(
                        "getCallingPackage",
                        "()Ljava/lang/String;");
    }


    // method: public android.content.ComponentName getCallingActivity()
    auto getCallingActivity() const {
        return m_jniObject.callMethod<jobject>(
                        "getCallingActivity",
                        "()Landroid/content/ComponentName;");
    }


    // method: public int getLaunchedFromUid()
    auto getLaunchedFromUid() const {
        return m_jniObject.callMethod<jint>(
                        "getLaunchedFromUid",
                        "()I");
    }


    // method: public java.lang.String getLaunchedFromPackage()
    auto getLaunchedFromPackage() const {
        return m_jniObject.callMethod<jstring>(
                        "getLaunchedFromPackage",
                        "()Ljava/lang/String;");
    }


    // method: public android.app.ComponentCaller getInitialCaller()
    auto getInitialCaller() const {
        return m_jniObject.callMethod<jobject>(
                        "getInitialCaller",
                        "()Landroid/app/ComponentCaller;");
    }


    // method: public android.app.ComponentCaller getCurrentCaller()
    auto getCurrentCaller() const {
        return m_jniObject.callMethod<jobject>(
                        "getCurrentCaller",
                        "()Landroid/app/ComponentCaller;");
    }


    // method: public void setVisible(boolean visible)
    auto setVisible(jboolean visible) const {
        m_jniObject.callMethod<void>(
                        "setVisible",
                        "(Z)V", visible);
    }


    // method: public boolean isFinishing()
    auto isFinishing() const {
        return m_jniObject.callMethod<jboolean>(
                        "isFinishing",
                        "()Z");
    }


    // method: public boolean isDestroyed()
    auto isDestroyed() const {
        return m_jniObject.callMethod<jboolean>(
                        "isDestroyed",
                        "()Z");
    }


    // method: public boolean isChangingConfigurations()
    auto isChangingConfigurations() const {
        return m_jniObject.callMethod<jboolean>(
                        "isChangingConfigurations",
                        "()Z");
    }


    // method: public void recreate()
    auto recreate() const {
        m_jniObject.callMethod<void>(
                        "recreate",
                        "()V");
    }


    // method: public void finish()
    auto finish() const {
        m_jniObject.callMethod<void>(
                        "finish",
                        "()V");
    }


    // method: public void finishAffinity()
    auto finishAffinity() const {
        m_jniObject.callMethod<void>(
                        "finishAffinity",
                        "()V");
    }


    // method: public void finishFromChild(android.app.Activity child)
    auto finishFromChild(jobject child) const {
        m_jniObject.callMethod<void>(
                        "finishFromChild",
                        "(Landroid/app/Activity;)V", child);
    }


    // method: public void finishAfterTransition()
    auto finishAfterTransition() const {
        m_jniObject.callMethod<void>(
                        "finishAfterTransition",
                        "()V");
    }


    // method: public void finishActivity(int requestCode)
    auto finishActivity(jint requestCode) const {
        m_jniObject.callMethod<void>(
                        "finishActivity",
                        "(I)V", requestCode);
    }


    // method: public void finishActivityFromChild(android.app.Activity child, int requestCode)
    auto finishActivityFromChild(jobject child, jint requestCode) const {
        m_jniObject.callMethod<void>(
                        "finishActivityFromChild",
                        "(Landroid/app/Activity;I)V", child, requestCode);
    }


    // method: public void finishAndRemoveTask()
    auto finishAndRemoveTask() const {
        m_jniObject.callMethod<void>(
                        "finishAndRemoveTask",
                        "()V");
    }


    // method: public boolean releaseInstance()
    auto releaseInstance() const {
        return m_jniObject.callMethod<jboolean>(
                        "releaseInstance",
                        "()Z");
    }


    // method: public void onActivityResult(int requestCode, int resultCode, android.content.Intent data, android.app.ComponentCaller caller)
    auto onActivityResult(jint requestCode, jint resultCode, jobject data, jobject caller) const {
        m_jniObject.callMethod<void>(
                        "onActivityResult",
                        "(IILandroid/content/Intent;Landroid/app/ComponentCaller;)V", requestCode, resultCode, data, caller);
    }


    // method: public void onActivityReenter(int resultCode, android.content.Intent data)
    auto onActivityReenter(jint resultCode, jobject data) const {
        m_jniObject.callMethod<void>(
                        "onActivityReenter",
                        "(ILandroid/content/Intent;)V", resultCode, data);
    }


    // method: public android.app.PendingIntent createPendingResult(int requestCode, android.content.Intent data, int flags)
    auto createPendingResult(jint requestCode, jobject data, jint flags) const {
        return m_jniObject.callMethod<jobject>(
                        "createPendingResult",
                        "(ILandroid/content/Intent;I)Landroid/app/PendingIntent;", requestCode, data, flags);
    }


    // method: public void setRequestedOrientation(int requestedOrientation)
    auto setRequestedOrientation(jint requestedOrientation) const {
        m_jniObject.callMethod<void>(
                        "setRequestedOrientation",
                        "(I)V", requestedOrientation);
    }


    // method: public int getRequestedOrientation()
    auto getRequestedOrientation() const {
        return m_jniObject.callMethod<jint>(
                        "getRequestedOrientation",
                        "()I");
    }


    // method: public int getTaskId()
    auto getTaskId() const {
        return m_jniObject.callMethod<jint>(
                        "getTaskId",
                        "()I");
    }


    // method: public boolean isTaskRoot()
    auto isTaskRoot() const {
        return m_jniObject.callMethod<jboolean>(
                        "isTaskRoot",
                        "()Z");
    }


    // method: public boolean moveTaskToBack(boolean nonRoot)
    auto moveTaskToBack(jboolean nonRoot) const {
        return m_jniObject.callMethod<jboolean>(
                        "moveTaskToBack",
                        "(Z)Z", nonRoot);
    }


    // method: public java.lang.String getLocalClassName()
    auto getLocalClassName() const {
        return m_jniObject.callMethod<jstring>(
                        "getLocalClassName",
                        "()Ljava/lang/String;");
    }


    // method: public android.content.ComponentName getComponentName()
    auto getComponentName() const {
        return m_jniObject.callMethod<jobject>(
                        "getComponentName",
                        "()Landroid/content/ComponentName;");
    }


    // method: public android.content.SharedPreferences getPreferences(int mode)
    auto getPreferences(jint mode) const {
        return m_jniObject.callMethod<jobject>(
                        "getPreferences",
                        "(I)Landroid/content/SharedPreferences;", mode);
    }


    // method: public boolean isLaunchedFromBubble()
    auto isLaunchedFromBubble() const {
        return m_jniObject.callMethod<jboolean>(
                        "isLaunchedFromBubble",
                        "()Z");
    }


    // method: public java.lang.Object getSystemService(java.lang.String name)
    auto getSystemService(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getSystemService",
                        "(Ljava/lang/String;)Ljava/lang/Object;", name);
    }


    // method: public void setTitle(java.lang.CharSequence title)
    auto setTitle(jobject title) const {
        m_jniObject.callMethod<void>(
                        "setTitle",
                        "(Ljava/lang/CharSequence;)V", title);
    }


    // method: public void setTitle(int titleId)
    auto setTitle(jint titleId) const {
        m_jniObject.callMethod<void>(
                        "setTitle",
                        "(I)V", titleId);
    }


    // method: public void setTitleColor(int textColor)
    auto setTitleColor(jint textColor) const {
        m_jniObject.callMethod<void>(
                        "setTitleColor",
                        "(I)V", textColor);
    }


    // method: public final java.lang.CharSequence getTitle()
    auto getTitle() const {
        return m_jniObject.callMethod<jobject>(
                        "getTitle",
                        "()Ljava/lang/CharSequence;");
    }


    // method: public final int getTitleColor()
    auto getTitleColor() const {
        return m_jniObject.callMethod<jint>(
                        "getTitleColor",
                        "()I");
    }


    // method: public void setTaskDescription(android.app.ActivityManager.TaskDescription taskDescription)
    auto setTaskDescription(jobject taskDescription) const {
        m_jniObject.callMethod<void>(
                        "setTaskDescription",
                        "(Landroid/app/ActivityManager$TaskDescription;)V", taskDescription);
    }


    // method: public final void setProgressBarVisibility(boolean visible)
    auto setProgressBarVisibility(jboolean visible) const {
        m_jniObject.callMethod<void>(
                        "setProgressBarVisibility",
                        "(Z)V", visible);
    }


    // method: public final void setProgressBarIndeterminateVisibility(boolean visible)
    auto setProgressBarIndeterminateVisibility(jboolean visible) const {
        m_jniObject.callMethod<void>(
                        "setProgressBarIndeterminateVisibility",
                        "(Z)V", visible);
    }


    // method: public final void setProgressBarIndeterminate(boolean indeterminate)
    auto setProgressBarIndeterminate(jboolean indeterminate) const {
        m_jniObject.callMethod<void>(
                        "setProgressBarIndeterminate",
                        "(Z)V", indeterminate);
    }


    // method: public final void setProgress(int progress)
    auto setProgress(jint progress) const {
        m_jniObject.callMethod<void>(
                        "setProgress",
                        "(I)V", progress);
    }


    // method: public final void setSecondaryProgress(int secondaryProgress)
    auto setSecondaryProgress(jint secondaryProgress) const {
        m_jniObject.callMethod<void>(
                        "setSecondaryProgress",
                        "(I)V", secondaryProgress);
    }


    // method: public final void setVolumeControlStream(int streamType)
    auto setVolumeControlStream(jint streamType) const {
        m_jniObject.callMethod<void>(
                        "setVolumeControlStream",
                        "(I)V", streamType);
    }


    // method: public final int getVolumeControlStream()
    auto getVolumeControlStream() const {
        return m_jniObject.callMethod<jint>(
                        "getVolumeControlStream",
                        "()I");
    }


    // method: public final void setMediaController(android.media.session.MediaController controller)
    auto setMediaController(jobject controller) const {
        m_jniObject.callMethod<void>(
                        "setMediaController",
                        "(Landroid/media/session/MediaController;)V", controller);
    }


    // method: public final android.media.session.MediaController getMediaController()
    auto getMediaController() const {
        return m_jniObject.callMethod<jobject>(
                        "getMediaController",
                        "()Landroid/media/session/MediaController;");
    }


    // method: public final void runOnUiThread(java.lang.Runnable action)
    auto runOnUiThread(jobject action) const {
        m_jniObject.callMethod<void>(
                        "runOnUiThread",
                        "(Ljava/lang/Runnable;)V", action);
    }


    // method: public android.view.View onCreateView(java.lang.String name, android.content.Context context, android.util.AttributeSet attrs)
    auto onCreateView(jstring name, jobject context, jobject attrs) const {
        return m_jniObject.callMethod<jobject>(
                        "onCreateView",
                        "(Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;", name, context, attrs);
    }


    // method: public android.view.View onCreateView(android.view.View parent, java.lang.String name, android.content.Context context, android.util.AttributeSet attrs)
    auto onCreateView(jobject parent, jstring name, jobject context, jobject attrs) const {
        return m_jniObject.callMethod<jobject>(
                        "onCreateView",
                        "(Landroid/view/View;Ljava/lang/String;Landroid/content/Context;Landroid/util/AttributeSet;)Landroid/view/View;", parent, name, context, attrs);
    }


    // method: public void dump(java.lang.String prefix, java.io.FileDescriptor fd, java.io.PrintWriter writer, java.lang.String[] args)
    auto dump(jstring prefix, jobject fd, jobject writer, jobjectArray args) const {
        m_jniObject.callMethod<void>(
                        "dump",
                        "(Ljava/lang/String;Ljava/io/FileDescriptor;Ljava/io/PrintWriter;[Ljava/lang/String;)V", prefix, fd, writer, args);
    }


    // method: public boolean isImmersive()
    auto isImmersive() const {
        return m_jniObject.callMethod<jboolean>(
                        "isImmersive",
                        "()Z");
    }


    // method: public boolean setTranslucent(boolean translucent)
    auto setTranslucent(jboolean translucent) const {
        return m_jniObject.callMethod<jboolean>(
                        "setTranslucent",
                        "(Z)Z", translucent);
    }


    // method: public boolean requestVisibleBehind(boolean visible)
    auto requestVisibleBehind(jboolean visible) const {
        return m_jniObject.callMethod<jboolean>(
                        "requestVisibleBehind",
                        "(Z)Z", visible);
    }


    // method: public void onVisibleBehindCanceled()
    auto onVisibleBehindCanceled() const {
        m_jniObject.callMethod<void>(
                        "onVisibleBehindCanceled",
                        "()V");
    }


    // method: public void onEnterAnimationComplete()
    auto onEnterAnimationComplete() const {
        m_jniObject.callMethod<void>(
                        "onEnterAnimationComplete",
                        "()V");
    }


    // method: public void setImmersive(boolean i)
    auto setImmersive(jboolean i) const {
        m_jniObject.callMethod<void>(
                        "setImmersive",
                        "(Z)V", i);
    }


    // method: public void setVrModeEnabled(boolean enabled, android.content.ComponentName requestedComponent)
    auto setVrModeEnabled(jboolean enabled, jobject requestedComponent) const {
        m_jniObject.callMethod<void>(
                        "setVrModeEnabled",
                        "(ZLandroid/content/ComponentName;)V", enabled, requestedComponent);
    }


    // method: public android.view.ActionMode startActionMode(android.view.ActionMode.Callback callback)
    auto startActionMode(jobject callback) const {
        return m_jniObject.callMethod<jobject>(
                        "startActionMode",
                        "(Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode;", callback);
    }


    // method: public android.view.ActionMode startActionMode(android.view.ActionMode.Callback callback, int type)
    auto startActionMode(jobject callback, jint type) const {
        return m_jniObject.callMethod<jobject>(
                        "startActionMode",
                        "(Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;", callback, type);
    }


    // method: public android.view.ActionMode onWindowStartingActionMode(android.view.ActionMode.Callback callback)
    auto onWindowStartingActionMode(jobject callback) const {
        return m_jniObject.callMethod<jobject>(
                        "onWindowStartingActionMode",
                        "(Landroid/view/ActionMode$Callback;)Landroid/view/ActionMode;", callback);
    }


    // method: public android.view.ActionMode onWindowStartingActionMode(android.view.ActionMode.Callback callback, int type)
    auto onWindowStartingActionMode(jobject callback, jint type) const {
        return m_jniObject.callMethod<jobject>(
                        "onWindowStartingActionMode",
                        "(Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;", callback, type);
    }


    // method: public void onActionModeStarted(android.view.ActionMode mode)
    auto onActionModeStarted(jobject mode) const {
        m_jniObject.callMethod<void>(
                        "onActionModeStarted",
                        "(Landroid/view/ActionMode;)V", mode);
    }


    // method: public void onActionModeFinished(android.view.ActionMode mode)
    auto onActionModeFinished(jobject mode) const {
        m_jniObject.callMethod<void>(
                        "onActionModeFinished",
                        "(Landroid/view/ActionMode;)V", mode);
    }


    // method: public boolean shouldUpRecreateTask(android.content.Intent targetIntent)
    auto shouldUpRecreateTask(jobject targetIntent) const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldUpRecreateTask",
                        "(Landroid/content/Intent;)Z", targetIntent);
    }


    // method: public boolean navigateUpTo(android.content.Intent upIntent)
    auto navigateUpTo(jobject upIntent) const {
        return m_jniObject.callMethod<jboolean>(
                        "navigateUpTo",
                        "(Landroid/content/Intent;)Z", upIntent);
    }


    // method: public boolean navigateUpToFromChild(android.app.Activity child, android.content.Intent upIntent)
    auto navigateUpToFromChild(jobject child, jobject upIntent) const {
        return m_jniObject.callMethod<jboolean>(
                        "navigateUpToFromChild",
                        "(Landroid/app/Activity;Landroid/content/Intent;)Z", child, upIntent);
    }


    // method: public android.content.Intent getParentActivityIntent()
    auto getParentActivityIntent() const {
        return m_jniObject.callMethod<jobject>(
                        "getParentActivityIntent",
                        "()Landroid/content/Intent;");
    }


    // method: public void setEnterSharedElementCallback(android.app.SharedElementCallback callback)
    auto setEnterSharedElementCallback(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "setEnterSharedElementCallback",
                        "(Landroid/app/SharedElementCallback;)V", callback);
    }


    // method: public void setExitSharedElementCallback(android.app.SharedElementCallback callback)
    auto setExitSharedElementCallback(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "setExitSharedElementCallback",
                        "(Landroid/app/SharedElementCallback;)V", callback);
    }


    // method: public void postponeEnterTransition()
    auto postponeEnterTransition() const {
        m_jniObject.callMethod<void>(
                        "postponeEnterTransition",
                        "()V");
    }


    // method: public void startPostponedEnterTransition()
    auto startPostponedEnterTransition() const {
        m_jniObject.callMethod<void>(
                        "startPostponedEnterTransition",
                        "()V");
    }


    // method: public android.view.DragAndDropPermissions requestDragAndDropPermissions(android.view.DragEvent event)
    auto requestDragAndDropPermissions(jobject event) const {
        return m_jniObject.callMethod<jobject>(
                        "requestDragAndDropPermissions",
                        "(Landroid/view/DragEvent;)Landroid/view/DragAndDropPermissions;", event);
    }


    // method: public void startLockTask()
    auto startLockTask() const {
        m_jniObject.callMethod<void>(
                        "startLockTask",
                        "()V");
    }


    // method: public void stopLockTask()
    auto stopLockTask() const {
        m_jniObject.callMethod<void>(
                        "stopLockTask",
                        "()V");
    }


    // method: public void showLockTaskEscapeMessage()
    auto showLockTaskEscapeMessage() const {
        m_jniObject.callMethod<void>(
                        "showLockTaskEscapeMessage",
                        "()V");
    }


    // method: public void setRecentsScreenshotEnabled(boolean enabled)
    auto setRecentsScreenshotEnabled(jboolean enabled) const {
        m_jniObject.callMethod<void>(
                        "setRecentsScreenshotEnabled",
                        "(Z)V", enabled);
    }


    // method: public void setShowWhenLocked(boolean showWhenLocked)
    auto setShowWhenLocked(jboolean showWhenLocked) const {
        m_jniObject.callMethod<void>(
                        "setShowWhenLocked",
                        "(Z)V", showWhenLocked);
    }


    // method: public void setInheritShowWhenLocked(boolean inheritShowWhenLocked)
    auto setInheritShowWhenLocked(jboolean inheritShowWhenLocked) const {
        m_jniObject.callMethod<void>(
                        "setInheritShowWhenLocked",
                        "(Z)V", inheritShowWhenLocked);
    }


    // method: public void setTurnScreenOn(boolean turnScreenOn)
    auto setTurnScreenOn(jboolean turnScreenOn) const {
        m_jniObject.callMethod<void>(
                        "setTurnScreenOn",
                        "(Z)V", turnScreenOn);
    }


    // method: public void setAllowCrossUidActivitySwitchFromBelow(boolean allowed)
    auto setAllowCrossUidActivitySwitchFromBelow(jboolean allowed) const {
        m_jniObject.callMethod<void>(
                        "setAllowCrossUidActivitySwitchFromBelow",
                        "(Z)V", allowed);
    }


    // method: public android.window.OnBackInvokedDispatcher getOnBackInvokedDispatcher()
    auto getOnBackInvokedDispatcher() const {
        return m_jniObject.callMethod<jobject>(
                        "getOnBackInvokedDispatcher",
                        "()Landroid/window/OnBackInvokedDispatcher;");
    }


    // method: public void registerScreenCaptureCallback(java.util.concurrent.Executor executor, android.app.Activity.ScreenCaptureCallback callback)
    auto registerScreenCaptureCallback(jobject executor, jobject callback) const {
        m_jniObject.callMethod<void>(
                        "registerScreenCaptureCallback",
                        "(Ljava/util/concurrent/Executor;Landroid/app/Activity$ScreenCaptureCallback;)V", executor, callback);
    }


    // method: public void unregisterScreenCaptureCallback(android.app.Activity.ScreenCaptureCallback callback)
    auto unregisterScreenCaptureCallback(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "unregisterScreenCaptureCallback",
                        "(Landroid/app/Activity$ScreenCaptureCallback;)V", callback);
    }


};
} } // endof namespace android::app


namespace android { namespace app {


} } // endof namespace android::app

#endif // android_app_ActivityProxy_H

