
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_view_LayoutParamsProxy_H
#define android_view_LayoutParamsProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace view {
class LayoutParamsProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/view/WindowManager$LayoutParams";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    LayoutParamsProxy() {}
    LayoutParamsProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    LayoutParamsProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static LayoutParamsProxy fromLocalRef(jobject localRef) {
        LayoutParamsProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr jint ALPHA_CHANGED = 128;
    static constexpr jint ANIMATION_CHANGED = 16;
    static constexpr jfloat BRIGHTNESS_OVERRIDE_FULL = 1.0;
    static constexpr jfloat BRIGHTNESS_OVERRIDE_NONE = -1.0;
    static constexpr jfloat BRIGHTNESS_OVERRIDE_OFF = 0.0;
    static constexpr jint DIM_AMOUNT_CHANGED = 32;
    static constexpr jint DISPLAY_FLAG_DISABLE_HDR_CONVERSION = 1;
    static constexpr jint FIRST_APPLICATION_WINDOW = 1;
    static constexpr jint FIRST_SUB_WINDOW = 1000;
    static constexpr jint FIRST_SYSTEM_WINDOW = 2000;
    static constexpr jint FLAGS_CHANGED = 4;
    static constexpr jint FLAG_ALLOW_LOCK_WHILE_SCREEN_ON = 1;
    static constexpr jint FLAG_ALT_FOCUSABLE_IM = 131072;
    static constexpr jint FLAG_BLUR_BEHIND = 4;
    static constexpr jint FLAG_DIM_BEHIND = 2;
    static constexpr jint FLAG_DISMISS_KEYGUARD = 4194304;
    static constexpr jint FLAG_DITHER = 4096;
    static constexpr jint FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS = -2147483648;
    static constexpr jint FLAG_FORCE_NOT_FULLSCREEN = 2048;
    static constexpr jint FLAG_FULLSCREEN = 1024;
    static constexpr jint FLAG_HARDWARE_ACCELERATED = 16777216;
    static constexpr jint FLAG_IGNORE_CHEEK_PRESSES = 32768;
    static constexpr jint FLAG_KEEP_SCREEN_ON = 128;
    static constexpr jint FLAG_LAYOUT_ATTACHED_IN_DECOR = 1073741824;
    static constexpr jint FLAG_LAYOUT_INSET_DECOR = 65536;
    static constexpr jint FLAG_LAYOUT_IN_OVERSCAN = 33554432;
    static constexpr jint FLAG_LAYOUT_IN_SCREEN = 256;
    static constexpr jint FLAG_LAYOUT_NO_LIMITS = 512;
    static constexpr jint FLAG_LOCAL_FOCUS_MODE = 268435456;
    static constexpr jint FLAG_NOT_FOCUSABLE = 8;
    static constexpr jint FLAG_NOT_TOUCHABLE = 16;
    static constexpr jint FLAG_NOT_TOUCH_MODAL = 32;
    static constexpr jint FLAG_SCALED = 16384;
    static constexpr jint FLAG_SECURE = 8192;
    static constexpr jint FLAG_SHOW_WALLPAPER = 1048576;
    static constexpr jint FLAG_SHOW_WHEN_LOCKED = 524288;
    static constexpr jint FLAG_SPLIT_TOUCH = 8388608;
    static constexpr jint FLAG_TOUCHABLE_WHEN_WAKING = 64;
    static constexpr jint FLAG_TRANSLUCENT_NAVIGATION = 134217728;
    static constexpr jint FLAG_TRANSLUCENT_STATUS = 67108864;
    static constexpr jint FLAG_TURN_SCREEN_ON = 2097152;
    static constexpr jint FLAG_WATCH_OUTSIDE_TOUCH = 262144;
    static constexpr jint FORMAT_CHANGED = 8;
    static constexpr jint LAST_APPLICATION_WINDOW = 99;
    static constexpr jint LAST_SUB_WINDOW = 1999;
    static constexpr jint LAST_SYSTEM_WINDOW = 2999;
    static constexpr jint LAYOUT_CHANGED = 1;
    static constexpr jint LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS = 3;
    static constexpr jint LAYOUT_IN_DISPLAY_CUTOUT_MODE_DEFAULT = 0;
    static constexpr jint LAYOUT_IN_DISPLAY_CUTOUT_MODE_NEVER = 2;
    static constexpr jint LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES = 1;
    static constexpr jint MEMORY_TYPE_CHANGED = 256;
    static constexpr jint MEMORY_TYPE_GPU = 2;
    static constexpr jint MEMORY_TYPE_HARDWARE = 1;
    static constexpr jint MEMORY_TYPE_NORMAL = 0;
    static constexpr jint MEMORY_TYPE_PUSH_BUFFERS = 3;
    static constexpr jint ROTATION_ANIMATION_CHANGED = 4096;
    static constexpr jint ROTATION_ANIMATION_CROSSFADE = 1;
    static constexpr jint ROTATION_ANIMATION_JUMPCUT = 2;
    static constexpr jint ROTATION_ANIMATION_ROTATE = 0;
    static constexpr jint ROTATION_ANIMATION_SEAMLESS = 3;
    static constexpr jint SCREEN_BRIGHTNESS_CHANGED = 2048;
    static constexpr jint SCREEN_ORIENTATION_CHANGED = 1024;
    static constexpr jint SOFT_INPUT_ADJUST_NOTHING = 48;
    static constexpr jint SOFT_INPUT_ADJUST_PAN = 32;
    static constexpr jint SOFT_INPUT_ADJUST_RESIZE = 16;
    static constexpr jint SOFT_INPUT_ADJUST_UNSPECIFIED = 0;
    static constexpr jint SOFT_INPUT_IS_FORWARD_NAVIGATION = 256;
    static constexpr jint SOFT_INPUT_MASK_ADJUST = 240;
    static constexpr jint SOFT_INPUT_MASK_STATE = 15;
    static constexpr jint SOFT_INPUT_MODE_CHANGED = 512;
    static constexpr jint SOFT_INPUT_STATE_ALWAYS_HIDDEN = 3;
    static constexpr jint SOFT_INPUT_STATE_ALWAYS_VISIBLE = 5;
    static constexpr jint SOFT_INPUT_STATE_HIDDEN = 2;
    static constexpr jint SOFT_INPUT_STATE_UNCHANGED = 1;
    static constexpr jint SOFT_INPUT_STATE_UNSPECIFIED = 0;
    static constexpr jint SOFT_INPUT_STATE_VISIBLE = 4;
    static constexpr jint TITLE_CHANGED = 64;
    static constexpr jint TYPE_ACCESSIBILITY_OVERLAY = 2032;
    static constexpr jint TYPE_APPLICATION = 2;
    static constexpr jint TYPE_APPLICATION_ATTACHED_DIALOG = 1003;
    static constexpr jint TYPE_APPLICATION_MEDIA = 1001;
    static constexpr jint TYPE_APPLICATION_OVERLAY = 2038;
    static constexpr jint TYPE_APPLICATION_PANEL = 1000;
    static constexpr jint TYPE_APPLICATION_STARTING = 3;
    static constexpr jint TYPE_APPLICATION_SUB_PANEL = 1002;
    static constexpr jint TYPE_BASE_APPLICATION = 1;
    static constexpr jint TYPE_CHANGED = 2;
    static constexpr jint TYPE_DRAWN_APPLICATION = 4;
    static constexpr jint TYPE_INPUT_METHOD = 2011;
    static constexpr jint TYPE_INPUT_METHOD_DIALOG = 2012;
    static constexpr jint TYPE_KEYGUARD_DIALOG = 2009;
    static constexpr jint TYPE_PHONE = 2002;
    static constexpr jint TYPE_PRIORITY_PHONE = 2007;
    static constexpr jint TYPE_PRIVATE_PRESENTATION = 2030;
    static constexpr jint TYPE_SEARCH_BAR = 2001;
    static constexpr jint TYPE_STATUS_BAR = 2000;
    static constexpr jint TYPE_SYSTEM_ALERT = 2003;
    static constexpr jint TYPE_SYSTEM_DIALOG = 2008;
    static constexpr jint TYPE_SYSTEM_ERROR = 2010;
    static constexpr jint TYPE_SYSTEM_OVERLAY = 2006;
    static constexpr jint TYPE_TOAST = 2005;
    static constexpr jint TYPE_WALLPAPER = 2013;


    // construct: public LayoutParams()
    static LayoutParamsProxy newInstance() {
        LayoutParamsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "()V");
        return ret;
    }

    // construct: public LayoutParams(int _type)
    static LayoutParamsProxy newInstance(jint _type) {
        LayoutParamsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(I)V", _type);
        return ret;
    }

    // construct: public LayoutParams(int _type, int _flags)
    static LayoutParamsProxy newInstance(jint _type, jint _flags) {
        LayoutParamsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(II)V", _type, _flags);
        return ret;
    }

    // construct: public LayoutParams(int _type, int _flags, int _format)
    static LayoutParamsProxy newInstance(jint _type, jint _flags, jint _format) {
        LayoutParamsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(III)V", _type, _flags, _format);
        return ret;
    }

    // construct: public LayoutParams(int w, int h, int _type, int _flags, int _format)
    static LayoutParamsProxy newInstance(jint w, jint h, jint _type, jint _flags, jint _format) {
        LayoutParamsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(IIIII)V", w, h, _type, _flags, _format);
        return ret;
    }

    // construct: public LayoutParams(int w, int h, int xpos, int ypos, int _type, int _flags, int _format)
    static LayoutParamsProxy newInstance(jint w, jint h, jint xpos, jint ypos, jint _type, jint _flags, jint _format) {
        LayoutParamsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(IIIIIII)V", w, h, xpos, ypos, _type, _flags, _format);
        return ret;
    }

    // construct: public LayoutParams(android.os.Parcel in)
    static LayoutParamsProxy newInstance(jobject in) {
        LayoutParamsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Landroid/os/Parcel;)V", in);
        return ret;
    }

    // method: public static boolean mayUseInputMethod(int flags)
    static auto mayUseInputMethod(jint flags) {
        return QJniObject::callStaticMethod<jboolean>(FULL_CLASS_NAME,
                        "mayUseInputMethod",
                        "(I)Z", flags);
    }


    // method: public void setFitInsetsTypes(int types)
    auto setFitInsetsTypes(jint types) const {
        m_jniObject.callMethod<void>(
                        "setFitInsetsTypes",
                        "(I)V", types);
    }


    // method: public void setFitInsetsSides(int sides)
    auto setFitInsetsSides(jint sides) const {
        m_jniObject.callMethod<void>(
                        "setFitInsetsSides",
                        "(I)V", sides);
    }


    // method: public void setFitInsetsIgnoringVisibility(boolean ignore)
    auto setFitInsetsIgnoringVisibility(jboolean ignore) const {
        m_jniObject.callMethod<void>(
                        "setFitInsetsIgnoringVisibility",
                        "(Z)V", ignore);
    }


    // method: public void setWallpaperTouchEventsEnabled(boolean enable)
    auto setWallpaperTouchEventsEnabled(jboolean enable) const {
        m_jniObject.callMethod<void>(
                        "setWallpaperTouchEventsEnabled",
                        "(Z)V", enable);
    }


    // method: public boolean areWallpaperTouchEventsEnabled()
    auto areWallpaperTouchEventsEnabled() const {
        return m_jniObject.callMethod<jboolean>(
                        "areWallpaperTouchEventsEnabled",
                        "()Z");
    }


    // method: public void setCanPlayMoveAnimation(boolean enable)
    auto setCanPlayMoveAnimation(jboolean enable) const {
        m_jniObject.callMethod<void>(
                        "setCanPlayMoveAnimation",
                        "(Z)V", enable);
    }


    // method: public boolean canPlayMoveAnimation()
    auto canPlayMoveAnimation() const {
        return m_jniObject.callMethod<jboolean>(
                        "canPlayMoveAnimation",
                        "()Z");
    }


    // method: public int getFitInsetsTypes()
    auto getFitInsetsTypes() const {
        return m_jniObject.callMethod<jint>(
                        "getFitInsetsTypes",
                        "()I");
    }


    // method: public int getFitInsetsSides()
    auto getFitInsetsSides() const {
        return m_jniObject.callMethod<jint>(
                        "getFitInsetsSides",
                        "()I");
    }


    // method: public boolean isFitInsetsIgnoringVisibility()
    auto isFitInsetsIgnoringVisibility() const {
        return m_jniObject.callMethod<jboolean>(
                        "isFitInsetsIgnoringVisibility",
                        "()Z");
    }


    // method: public final void setTitle(java.lang.CharSequence title)
    auto setTitle(jobject title) const {
        m_jniObject.callMethod<void>(
                        "setTitle",
                        "(Ljava/lang/CharSequence;)V", title);
    }


    // method: public final java.lang.CharSequence getTitle()
    auto getTitle() const {
        return m_jniObject.callMethod<jobject>(
                        "getTitle",
                        "()Ljava/lang/CharSequence;");
    }


    // method: public boolean isHdrConversionEnabled()
    auto isHdrConversionEnabled() const {
        return m_jniObject.callMethod<jboolean>(
                        "isHdrConversionEnabled",
                        "()Z");
    }


    // method: public void setHdrConversionEnabled(boolean enabled)
    auto setHdrConversionEnabled(jboolean enabled) const {
        m_jniObject.callMethod<void>(
                        "setHdrConversionEnabled",
                        "(Z)V", enabled);
    }


    // method: public void setColorMode(int colorMode)
    auto setColorMode(jint colorMode) const {
        m_jniObject.callMethod<void>(
                        "setColorMode",
                        "(I)V", colorMode);
    }


    // method: public int getColorMode()
    auto getColorMode() const {
        return m_jniObject.callMethod<jint>(
                        "getColorMode",
                        "()I");
    }


    // method: public void setDesiredHdrHeadroom(float desiredHeadroom)
    auto setDesiredHdrHeadroom(jfloat desiredHeadroom) const {
        m_jniObject.callMethod<void>(
                        "setDesiredHdrHeadroom",
                        "(F)V", desiredHeadroom);
    }


    // method: public float getDesiredHdrHeadroom()
    auto getDesiredHdrHeadroom() const {
        return m_jniObject.callMethod<jfloat>(
                        "getDesiredHdrHeadroom",
                        "()F");
    }


    // method: public void setFrameRateBoostOnTouchEnabled(boolean enabled)
    auto setFrameRateBoostOnTouchEnabled(jboolean enabled) const {
        m_jniObject.callMethod<void>(
                        "setFrameRateBoostOnTouchEnabled",
                        "(Z)V", enabled);
    }


    // method: public boolean getFrameRateBoostOnTouchEnabled()
    auto getFrameRateBoostOnTouchEnabled() const {
        return m_jniObject.callMethod<jboolean>(
                        "getFrameRateBoostOnTouchEnabled",
                        "()Z");
    }


    // method: public void setFrameRatePowerSavingsBalanced(boolean enabled)
    auto setFrameRatePowerSavingsBalanced(jboolean enabled) const {
        m_jniObject.callMethod<void>(
                        "setFrameRatePowerSavingsBalanced",
                        "(Z)V", enabled);
    }


    // method: public boolean isFrameRatePowerSavingsBalanced()
    auto isFrameRatePowerSavingsBalanced() const {
        return m_jniObject.callMethod<jboolean>(
                        "isFrameRatePowerSavingsBalanced",
                        "()Z");
    }


    // method: public void setBlurBehindRadius(int blurBehindRadius)
    auto setBlurBehindRadius(jint blurBehindRadius) const {
        m_jniObject.callMethod<void>(
                        "setBlurBehindRadius",
                        "(I)V", blurBehindRadius);
    }


    // method: public int getBlurBehindRadius()
    auto getBlurBehindRadius() const {
        return m_jniObject.callMethod<jint>(
                        "getBlurBehindRadius",
                        "()I");
    }


    // method: public int describeContents()
    auto describeContents() const {
        return m_jniObject.callMethod<jint>(
                        "describeContents",
                        "()I");
    }


    // method: public void writeToParcel(android.os.Parcel out, int parcelableFlags)
    auto writeToParcel(jobject out, jint parcelableFlags) const {
        m_jniObject.callMethod<void>(
                        "writeToParcel",
                        "(Landroid/os/Parcel;I)V", out, parcelableFlags);
    }


    // method: public final int copyFrom(android.view.WindowManager.LayoutParams o)
    auto copyFrom(jobject o) const {
        return m_jniObject.callMethod<jint>(
                        "copyFrom",
                        "(Landroid/view/WindowManager$LayoutParams;)I", o);
    }


    // method: public java.lang.String debug(java.lang.String output)
    auto debug(jstring output) const {
        return m_jniObject.callMethod<jstring>(
                        "debug",
                        "(Ljava/lang/String;)Ljava/lang/String;", output);
    }


    // method: public java.lang.String toString()
    auto toString() const {
        return m_jniObject.callMethod<jstring>(
                        "toString",
                        "()Ljava/lang/String;");
    }


    // field: public static final android.os.Parcelable.Creator<android.view.WindowManager.LayoutParams> CREATOR
    static auto getCREATOR() {
       return QJniObject::getStaticField<jobject>(FULL_CLASS_NAME,"CREATOR");

    }

    // field: public static final android.os.Parcelable.Creator<android.view.WindowManager.LayoutParams> CREATOR
    static void setCREATOR(jobject CREATOR) {
        QJniObject::setStaticField(FULL_CLASS_NAME,"CREATOR", CREATOR);
    }


    // field: public float alpha
    auto getAlpha() {
       return m_jniObject.getField<jfloat>("alpha");

    }

    // field: public float alpha
    void setAlpha(jfloat alpha) {
        m_jniObject.setField("alpha", alpha);
    }


    // field: public float buttonBrightness
    auto getButtonBrightness() {
       return m_jniObject.getField<jfloat>("buttonBrightness");

    }

    // field: public float buttonBrightness
    void setButtonBrightness(jfloat buttonBrightness) {
        m_jniObject.setField("buttonBrightness", buttonBrightness);
    }


    // field: public float dimAmount
    auto getDimAmount() {
       return m_jniObject.getField<jfloat>("dimAmount");

    }

    // field: public float dimAmount
    void setDimAmount(jfloat dimAmount) {
        m_jniObject.setField("dimAmount", dimAmount);
    }


    // field: public int flags
    auto getFlags() {
       return m_jniObject.getField<jint>("flags");

    }

    // field: public int flags
    void setFlags(jint flags) {
        m_jniObject.setField("flags", flags);
    }


    // field: public int format
    auto getFormat() {
       return m_jniObject.getField<jint>("format");

    }

    // field: public int format
    void setFormat(jint format) {
        m_jniObject.setField("format", format);
    }


    // field: public int gravity
    auto getGravity() {
       return m_jniObject.getField<jint>("gravity");

    }

    // field: public int gravity
    void setGravity(jint gravity) {
        m_jniObject.setField("gravity", gravity);
    }


    // field: public float horizontalMargin
    auto getHorizontalMargin() {
       return m_jniObject.getField<jfloat>("horizontalMargin");

    }

    // field: public float horizontalMargin
    void setHorizontalMargin(jfloat horizontalMargin) {
        m_jniObject.setField("horizontalMargin", horizontalMargin);
    }


    // field: public float horizontalWeight
    auto getHorizontalWeight() {
       return m_jniObject.getField<jfloat>("horizontalWeight");

    }

    // field: public float horizontalWeight
    void setHorizontalWeight(jfloat horizontalWeight) {
        m_jniObject.setField("horizontalWeight", horizontalWeight);
    }


    // field: public int layoutInDisplayCutoutMode
    auto getLayoutInDisplayCutoutMode() {
       return m_jniObject.getField<jint>("layoutInDisplayCutoutMode");

    }

    // field: public int layoutInDisplayCutoutMode
    void setLayoutInDisplayCutoutMode(jint layoutInDisplayCutoutMode) {
        m_jniObject.setField("layoutInDisplayCutoutMode", layoutInDisplayCutoutMode);
    }


    // field: public int memoryType
    auto getMemoryType() {
       return m_jniObject.getField<jint>("memoryType");

    }

    // field: public int memoryType
    void setMemoryType(jint memoryType) {
        m_jniObject.setField("memoryType", memoryType);
    }


    // field: public java.lang.String packageName
    auto getPackageName() {
       return m_jniObject.getField<jstring>("packageName");

    }

    // field: public java.lang.String packageName
    void setPackageName(jstring packageName) {
        m_jniObject.setField("packageName", packageName);
    }


    // field: public boolean preferMinimalPostProcessing
    auto getPreferMinimalPostProcessing() {
       return m_jniObject.getField<jboolean>("preferMinimalPostProcessing");

    }

    // field: public boolean preferMinimalPostProcessing
    void setPreferMinimalPostProcessing(jboolean preferMinimalPostProcessing) {
        m_jniObject.setField("preferMinimalPostProcessing", preferMinimalPostProcessing);
    }


    // field: public int preferredDisplayModeId
    auto getPreferredDisplayModeId() {
       return m_jniObject.getField<jint>("preferredDisplayModeId");

    }

    // field: public int preferredDisplayModeId
    void setPreferredDisplayModeId(jint preferredDisplayModeId) {
        m_jniObject.setField("preferredDisplayModeId", preferredDisplayModeId);
    }


    // field: public float preferredRefreshRate
    auto getPreferredRefreshRate() {
       return m_jniObject.getField<jfloat>("preferredRefreshRate");

    }

    // field: public float preferredRefreshRate
    void setPreferredRefreshRate(jfloat preferredRefreshRate) {
        m_jniObject.setField("preferredRefreshRate", preferredRefreshRate);
    }


    // field: public int rotationAnimation
    auto getRotationAnimation() {
       return m_jniObject.getField<jint>("rotationAnimation");

    }

    // field: public int rotationAnimation
    void setRotationAnimation(jint rotationAnimation) {
        m_jniObject.setField("rotationAnimation", rotationAnimation);
    }


    // field: public float screenBrightness
    auto getScreenBrightness() {
       return m_jniObject.getField<jfloat>("screenBrightness");

    }

    // field: public float screenBrightness
    void setScreenBrightness(jfloat screenBrightness) {
        m_jniObject.setField("screenBrightness", screenBrightness);
    }


    // field: public int screenOrientation
    auto getScreenOrientation() {
       return m_jniObject.getField<jint>("screenOrientation");

    }

    // field: public int screenOrientation
    void setScreenOrientation(jint screenOrientation) {
        m_jniObject.setField("screenOrientation", screenOrientation);
    }


    // field: public int softInputMode
    auto getSoftInputMode() {
       return m_jniObject.getField<jint>("softInputMode");

    }

    // field: public int softInputMode
    void setSoftInputMode(jint softInputMode) {
        m_jniObject.setField("softInputMode", softInputMode);
    }


    // field: public int systemUiVisibility
    auto getSystemUiVisibility() {
       return m_jniObject.getField<jint>("systemUiVisibility");

    }

    // field: public int systemUiVisibility
    void setSystemUiVisibility(jint systemUiVisibility) {
        m_jniObject.setField("systemUiVisibility", systemUiVisibility);
    }


    // field: public android.os.IBinder token
    auto getToken() {
       return m_jniObject.getField<jobject>("token");

    }

    // field: public android.os.IBinder token
    void setToken(jobject token) {
        m_jniObject.setField("token", token);
    }


    // field: public int type
    auto getType() {
       return m_jniObject.getField<jint>("type");

    }

    // field: public int type
    void setType(jint type) {
        m_jniObject.setField("type", type);
    }


    // field: public float verticalMargin
    auto getVerticalMargin() {
       return m_jniObject.getField<jfloat>("verticalMargin");

    }

    // field: public float verticalMargin
    void setVerticalMargin(jfloat verticalMargin) {
        m_jniObject.setField("verticalMargin", verticalMargin);
    }


    // field: public float verticalWeight
    auto getVerticalWeight() {
       return m_jniObject.getField<jfloat>("verticalWeight");

    }

    // field: public float verticalWeight
    void setVerticalWeight(jfloat verticalWeight) {
        m_jniObject.setField("verticalWeight", verticalWeight);
    }


    // field: public int windowAnimations
    auto getWindowAnimations() {
       return m_jniObject.getField<jint>("windowAnimations");

    }

    // field: public int windowAnimations
    void setWindowAnimations(jint windowAnimations) {
        m_jniObject.setField("windowAnimations", windowAnimations);
    }


    // field: public int x
    auto getX() {
       return m_jniObject.getField<jint>("x");

    }

    // field: public int x
    void setX(jint x) {
        m_jniObject.setField("x", x);
    }


    // field: public int y
    auto getY() {
       return m_jniObject.getField<jint>("y");

    }

    // field: public int y
    void setY(jint y) {
        m_jniObject.setField("y", y);
    }


};
} } // endof namespace android::view


namespace android { namespace view {


} } // endof namespace android::view

#endif // android_view_LayoutParamsProxy_H

