
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_os_VibratorProxy_H
#define android_os_VibratorProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace os {
class VibratorProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/os/Vibrator";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    VibratorProxy() {}
    VibratorProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    VibratorProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static VibratorProxy fromLocalRef(jobject localRef) {
        VibratorProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr jint VIBRATION_EFFECT_SUPPORT_NO = 2;
    static constexpr jint VIBRATION_EFFECT_SUPPORT_UNKNOWN = 0;
    static constexpr jint VIBRATION_EFFECT_SUPPORT_YES = 1;


    // method: public int getId()
    auto getId() const {
        return m_jniObject.callMethod<jint>(
                        "getId",
                        "()I");
    }


    // method: public abstract boolean hasVibrator()
    auto hasVibrator() const {
        return m_jniObject.callMethod<jboolean>(
                        "hasVibrator",
                        "()Z");
    }


    // method: public abstract boolean hasAmplitudeControl()
    auto hasAmplitudeControl() const {
        return m_jniObject.callMethod<jboolean>(
                        "hasAmplitudeControl",
                        "()Z");
    }


    // method: public float getResonantFrequency()
    auto getResonantFrequency() const {
        return m_jniObject.callMethod<jfloat>(
                        "getResonantFrequency",
                        "()F");
    }


    // method: public float getQFactor()
    auto getQFactor() const {
        return m_jniObject.callMethod<jfloat>(
                        "getQFactor",
                        "()F");
    }


    // method: public void vibrate(long milliseconds)
    auto vibrate(jlong milliseconds) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "(J)V", milliseconds);
    }


    // method: public void vibrate(long milliseconds, android.media.AudioAttributes attributes)
    auto vibrate(jlong milliseconds, jobject attributes) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "(JLandroid/media/AudioAttributes;)V", milliseconds, attributes);
    }


    // method: public void vibrate(long[] pattern, int repeat)
    auto vibrate(jlongArray pattern, jint repeat) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "([JI)V", pattern, repeat);
    }


    // method: public void vibrate(long[] pattern, int repeat, android.media.AudioAttributes attributes)
    auto vibrate(jlongArray pattern, jint repeat, jobject attributes) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "([JILandroid/media/AudioAttributes;)V", pattern, repeat, attributes);
    }


    // method: public void vibrate(android.os.VibrationEffect vibe)
    auto vibrate(jobject vibe) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "(Landroid/os/VibrationEffect;)V", vibe);
    }


    // method: public void vibrate(android.os.VibrationEffect vibe, android.media.AudioAttributes attributes)
    auto vibrate__Landroid_os_VibrationEffect_2Landroid_media_AudioAttributes_2(jobject vibe, jobject attributes) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "(Landroid/os/VibrationEffect;Landroid/media/AudioAttributes;)V", vibe, attributes);
    }


    // method: public void vibrate(android.os.VibrationEffect vibe, android.os.VibrationAttributes attributes)
    auto vibrate__Landroid_os_VibrationEffect_2Landroid_os_VibrationAttributes_2(jobject vibe, jobject attributes) const {
        m_jniObject.callMethod<void>(
                        "vibrate",
                        "(Landroid/os/VibrationEffect;Landroid/os/VibrationAttributes;)V", vibe, attributes);
    }


    // method: public int[] areEffectsSupported(int[] effectIds)
    auto areEffectsSupported(jintArray effectIds) const {
        return m_jniObject.callMethod<jintArray>(
                        "areEffectsSupported",
                        "([I)[I", effectIds);
    }


    // method: public final int areAllEffectsSupported(int[] effectIds)
    auto areAllEffectsSupported(jintArray effectIds) const {
        return m_jniObject.callMethod<jint>(
                        "areAllEffectsSupported",
                        "([I)I", effectIds);
    }


    // method: public boolean[] arePrimitivesSupported(int[] primitiveIds)
    auto arePrimitivesSupported(jintArray primitiveIds) const {
        return m_jniObject.callMethod<jbooleanArray>(
                        "arePrimitivesSupported",
                        "([I)[Z", primitiveIds);
    }


    // method: public final boolean areAllPrimitivesSupported(int[] primitiveIds)
    auto areAllPrimitivesSupported(jintArray primitiveIds) const {
        return m_jniObject.callMethod<jboolean>(
                        "areAllPrimitivesSupported",
                        "([I)Z", primitiveIds);
    }


    // method: public int[] getPrimitiveDurations(int[] primitiveIds)
    auto getPrimitiveDurations(jintArray primitiveIds) const {
        return m_jniObject.callMethod<jintArray>(
                        "getPrimitiveDurations",
                        "([I)[I", primitiveIds);
    }


    // method: public abstract void cancel()
    auto cancel() const {
        m_jniObject.callMethod<void>(
                        "cancel",
                        "()V");
    }


};
} } // endof namespace android::os


namespace android { namespace os {


} } // endof namespace android::os

#endif // android_os_VibratorProxy_H

