
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_drawable_drawableProxy_H
#define android_drawable_drawableProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace drawable {
class drawableProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/R$drawable";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    drawableProxy() {}
    drawableProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    drawableProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static drawableProxy fromLocalRef(jobject localRef) {
        drawableProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr jint alert_dark_frame = 17301504;
    static constexpr jint alert_light_frame = 17301505;
    static constexpr jint arrow_down_float = 17301506;
    static constexpr jint arrow_up_float = 17301507;
    static constexpr jint bottom_bar = 17301658;
    static constexpr jint btn_default = 17301508;
    static constexpr jint btn_default_small = 17301509;
    static constexpr jint btn_dialog = 17301527;
    static constexpr jint btn_dropdown = 17301510;
    static constexpr jint btn_minus = 17301511;
    static constexpr jint btn_plus = 17301512;
    static constexpr jint btn_radio = 17301513;
    static constexpr jint btn_star = 17301514;
    static constexpr jint btn_star_big_off = 17301515;
    static constexpr jint btn_star_big_on = 17301516;
    static constexpr jint button_onoff_indicator_off = 17301518;
    static constexpr jint button_onoff_indicator_on = 17301517;
    static constexpr jint checkbox_off_background = 17301519;
    static constexpr jint checkbox_on_background = 17301520;
    static constexpr jint dark_header = 17301669;
    static constexpr jint dialog_frame = 17301521;
    static constexpr jint dialog_holo_dark_frame = 17301682;
    static constexpr jint dialog_holo_light_frame = 17301683;
    static constexpr jint divider_horizontal_bright = 17301522;
    static constexpr jint divider_horizontal_dark = 17301524;
    static constexpr jint divider_horizontal_dim_dark = 17301525;
    static constexpr jint divider_horizontal_textfield = 17301523;
    static constexpr jint edit_text = 17301526;
    static constexpr jint editbox_background = 17301528;
    static constexpr jint editbox_background_normal = 17301529;
    static constexpr jint editbox_dropdown_dark_frame = 17301530;
    static constexpr jint editbox_dropdown_light_frame = 17301531;
    static constexpr jint gallery_thumb = 17301532;
    static constexpr jint ic_btn_speak_now = 17301668;
    static constexpr jint ic_delete = 17301533;
    static constexpr jint ic_dialog_alert = 17301543;
    static constexpr jint ic_dialog_dialer = 17301544;
    static constexpr jint ic_dialog_email = 17301545;
    static constexpr jint ic_dialog_info = 17301659;
    static constexpr jint ic_dialog_map = 17301546;
    static constexpr jint ic_input_add = 17301547;
    static constexpr jint ic_input_delete = 17301548;
    static constexpr jint ic_input_get = 17301549;
    static constexpr jint ic_lock_idle_alarm = 17301550;
    static constexpr jint ic_lock_idle_charging = 17301534;
    static constexpr jint ic_lock_idle_lock = 17301535;
    static constexpr jint ic_lock_idle_low_battery = 17301536;
    static constexpr jint ic_lock_lock = 17301551;
    static constexpr jint ic_lock_power_off = 17301552;
    static constexpr jint ic_lock_silent_mode = 17301553;
    static constexpr jint ic_lock_silent_mode_off = 17301554;
    static constexpr jint ic_media_ff = 17301537;
    static constexpr jint ic_media_next = 17301538;
    static constexpr jint ic_media_pause = 17301539;
    static constexpr jint ic_media_play = 17301540;
    static constexpr jint ic_media_previous = 17301541;
    static constexpr jint ic_media_rew = 17301542;
    static constexpr jint ic_menu_add = 17301555;
    static constexpr jint ic_menu_agenda = 17301556;
    static constexpr jint ic_menu_always_landscape_portrait = 17301557;
    static constexpr jint ic_menu_call = 17301558;
    static constexpr jint ic_menu_camera = 17301559;
    static constexpr jint ic_menu_close_clear_cancel = 17301560;
    static constexpr jint ic_menu_compass = 17301561;
    static constexpr jint ic_menu_crop = 17301562;
    static constexpr jint ic_menu_day = 17301563;
    static constexpr jint ic_menu_delete = 17301564;
    static constexpr jint ic_menu_directions = 17301565;
    static constexpr jint ic_menu_edit = 17301566;
    static constexpr jint ic_menu_gallery = 17301567;
    static constexpr jint ic_menu_help = 17301568;
    static constexpr jint ic_menu_info_details = 17301569;
    static constexpr jint ic_menu_manage = 17301570;
    static constexpr jint ic_menu_mapmode = 17301571;
    static constexpr jint ic_menu_month = 17301572;
    static constexpr jint ic_menu_more = 17301573;
    static constexpr jint ic_menu_my_calendar = 17301574;
    static constexpr jint ic_menu_mylocation = 17301575;
    static constexpr jint ic_menu_myplaces = 17301576;
    static constexpr jint ic_menu_preferences = 17301577;
    static constexpr jint ic_menu_recent_history = 17301578;
    static constexpr jint ic_menu_report_image = 17301579;
    static constexpr jint ic_menu_revert = 17301580;
    static constexpr jint ic_menu_rotate = 17301581;
    static constexpr jint ic_menu_save = 17301582;
    static constexpr jint ic_menu_search = 17301583;
    static constexpr jint ic_menu_send = 17301584;
    static constexpr jint ic_menu_set_as = 17301585;
    static constexpr jint ic_menu_share = 17301586;
    static constexpr jint ic_menu_slideshow = 17301587;
    static constexpr jint ic_menu_sort_alphabetically = 17301660;
    static constexpr jint ic_menu_sort_by_size = 17301661;
    static constexpr jint ic_menu_today = 17301588;
    static constexpr jint ic_menu_upload = 17301589;
    static constexpr jint ic_menu_upload_you_tube = 17301590;
    static constexpr jint ic_menu_view = 17301591;
    static constexpr jint ic_menu_week = 17301592;
    static constexpr jint ic_menu_zoom = 17301593;
    static constexpr jint ic_notification_clear_all = 17301594;
    static constexpr jint ic_notification_overlay = 17301595;
    static constexpr jint ic_partial_secure = 17301596;
    static constexpr jint ic_popup_disk_full = 17301597;
    static constexpr jint ic_popup_reminder = 17301598;
    static constexpr jint ic_popup_sync = 17301599;
    static constexpr jint ic_search_category_default = 17301600;
    static constexpr jint ic_secure = 17301601;
    static constexpr jint list_selector_background = 17301602;
    static constexpr jint menu_frame = 17301603;
    static constexpr jint menu_full_frame = 17301604;
    static constexpr jint menuitem_background = 17301605;
    static constexpr jint picture_frame = 17301606;
    static constexpr jint presence_audio_away = 17301679;
    static constexpr jint presence_audio_busy = 17301680;
    static constexpr jint presence_audio_online = 17301681;
    static constexpr jint presence_away = 17301607;
    static constexpr jint presence_busy = 17301608;
    static constexpr jint presence_invisible = 17301609;
    static constexpr jint presence_offline = 17301610;
    static constexpr jint presence_online = 17301611;
    static constexpr jint presence_video_away = 17301676;
    static constexpr jint presence_video_busy = 17301677;
    static constexpr jint presence_video_online = 17301678;
    static constexpr jint progress_horizontal = 17301612;
    static constexpr jint progress_indeterminate_horizontal = 17301613;
    static constexpr jint radiobutton_off_background = 17301614;
    static constexpr jint radiobutton_on_background = 17301615;
    static constexpr jint screen_background_dark = 17301656;
    static constexpr jint screen_background_dark_transparent = 17301673;
    static constexpr jint screen_background_light = 17301657;
    static constexpr jint screen_background_light_transparent = 17301674;
    static constexpr jint spinner_background = 17301616;
    static constexpr jint spinner_dropdown_background = 17301617;
    static constexpr jint star_big_off = 17301619;
    static constexpr jint star_big_on = 17301618;
    static constexpr jint star_off = 17301621;
    static constexpr jint star_on = 17301620;
    static constexpr jint stat_notify_call_mute = 17301622;
    static constexpr jint stat_notify_chat = 17301623;
    static constexpr jint stat_notify_error = 17301624;
    static constexpr jint stat_notify_missed_call = 17301631;
    static constexpr jint stat_notify_more = 17301625;
    static constexpr jint stat_notify_sdcard = 17301626;
    static constexpr jint stat_notify_sdcard_prepare = 17301675;
    static constexpr jint stat_notify_sdcard_usb = 17301627;
    static constexpr jint stat_notify_sync = 17301628;
    static constexpr jint stat_notify_sync_noanim = 17301629;
    static constexpr jint stat_notify_voicemail = 17301630;
    static constexpr jint stat_sys_data_bluetooth = 17301632;
    static constexpr jint stat_sys_download = 17301633;
    static constexpr jint stat_sys_download_done = 17301634;
    static constexpr jint stat_sys_headset = 17301635;
    static constexpr jint stat_sys_phone_call = 17301636;
    static constexpr jint stat_sys_phone_call_forward = 17301637;
    static constexpr jint stat_sys_phone_call_on_hold = 17301638;
    static constexpr jint stat_sys_speakerphone = 17301639;
    static constexpr jint stat_sys_upload = 17301640;
    static constexpr jint stat_sys_upload_done = 17301641;
    static constexpr jint stat_sys_vp_phone_call = 17301671;
    static constexpr jint stat_sys_vp_phone_call_on_hold = 17301672;
    static constexpr jint stat_sys_warning = 17301642;
    static constexpr jint status_bar_item_app_background = 17301643;
    static constexpr jint status_bar_item_background = 17301644;
    static constexpr jint sym_action_call = 17301645;
    static constexpr jint sym_action_chat = 17301646;
    static constexpr jint sym_action_email = 17301647;
    static constexpr jint sym_call_incoming = 17301648;
    static constexpr jint sym_call_missed = 17301649;
    static constexpr jint sym_call_outgoing = 17301650;
    static constexpr jint sym_contact_card = 17301652;
    static constexpr jint sym_def_app_icon = 17301651;
    static constexpr jint title_bar = 17301653;
    static constexpr jint title_bar_tall = 17301670;
    static constexpr jint toast_frame = 17301654;
    static constexpr jint zoom_plate = 17301655;


    // construct: public drawable()
    static drawableProxy newInstance() {
        drawableProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "()V");
        return ret;
    }

};
} } // endof namespace android::drawable


namespace android { namespace drawable {


} } // endof namespace android::drawable

#endif // android_drawable_drawableProxy_H

