
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_os_VibrationEffectProxy_H
#define android_os_VibrationEffectProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace os {
class VibrationEffectProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/os/VibrationEffect";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    VibrationEffectProxy() {}
    VibrationEffectProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    VibrationEffectProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static VibrationEffectProxy fromLocalRef(jobject localRef) {
        VibrationEffectProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr jint DEFAULT_AMPLITUDE = -1;
    static constexpr jint EFFECT_CLICK = 0;
    static constexpr jint EFFECT_DOUBLE_CLICK = 1;
    static constexpr jint EFFECT_HEAVY_CLICK = 5;
    static constexpr jint EFFECT_TICK = 2;


    // method: public static android.os.VibrationEffect createOneShot(long milliseconds, int amplitude)
    static auto createOneShot(jlong milliseconds, jint amplitude) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "createOneShot",
                        "(JI)Landroid/os/VibrationEffect;", milliseconds, amplitude);
    }


    // method: public static android.os.VibrationEffect createWaveform(long[] timings, int repeat)
    static auto createWaveform(jlongArray timings, jint repeat) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "createWaveform",
                        "([JI)Landroid/os/VibrationEffect;", timings, repeat);
    }


    // method: public static android.os.VibrationEffect createWaveform(long[] timings, int[] amplitudes, int repeat)
    static auto createWaveform(jlongArray timings, jintArray amplitudes, jint repeat) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "createWaveform",
                        "([J[II)Landroid/os/VibrationEffect;", timings, amplitudes, repeat);
    }


    // method: public static android.os.VibrationEffect createPredefined(int effectId)
    static auto createPredefined(jint effectId) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "createPredefined",
                        "(I)Landroid/os/VibrationEffect;", effectId);
    }


    // method: public static android.os.VibrationEffect.Composition startComposition()
    static auto startComposition() {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "startComposition",
                        "()Landroid/os/VibrationEffect$Composition;");
    }


    // method: public int describeContents()
    auto describeContents() const {
        return m_jniObject.callMethod<jint>(
                        "describeContents",
                        "()I");
    }


    // field: public static final android.os.Parcelable.Creator<android.os.VibrationEffect> CREATOR
    static auto getCREATOR() {
       return QJniObject::getStaticField<jobject>(FULL_CLASS_NAME,"CREATOR");

    }

    // field: public static final android.os.Parcelable.Creator<android.os.VibrationEffect> CREATOR
    static void setCREATOR(jobject CREATOR) {
        QJniObject::setStaticField(FULL_CLASS_NAME,"CREATOR", CREATOR);
    }


};
} } // endof namespace android::os


namespace android { namespace os {


} } // endof namespace android::os

#endif // android_os_VibrationEffectProxy_H

