
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_provider_SettingsProxy_H
#define android_provider_SettingsProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace provider {
class SettingsProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/provider/Settings";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    SettingsProxy() {}
    SettingsProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    SettingsProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static SettingsProxy fromLocalRef(jobject localRef) {
        SettingsProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr auto ACTION_ACCESSIBILITY_SETTINGS = u8"android.settings.ACCESSIBILITY_SETTINGS";
    static constexpr auto ACTION_ADD_ACCOUNT = u8"android.settings.ADD_ACCOUNT_SETTINGS";
    static constexpr auto ACTION_ADVANCED_MEMORY_PROTECTION_SETTINGS = u8"android.settings.ADVANCED_MEMORY_PROTECTION_SETTINGS";
    static constexpr auto ACTION_AIRPLANE_MODE_SETTINGS = u8"android.settings.AIRPLANE_MODE_SETTINGS";
    static constexpr auto ACTION_ALL_APPS_NOTIFICATION_SETTINGS = u8"android.settings.ALL_APPS_NOTIFICATION_SETTINGS";
    static constexpr auto ACTION_APN_SETTINGS = u8"android.settings.APN_SETTINGS";
    static constexpr auto ACTION_APPLICATION_DETAILS_SETTINGS = u8"android.settings.APPLICATION_DETAILS_SETTINGS";
    static constexpr auto ACTION_APPLICATION_DEVELOPMENT_SETTINGS = u8"android.settings.APPLICATION_DEVELOPMENT_SETTINGS";
    static constexpr auto ACTION_APPLICATION_SETTINGS = u8"android.settings.APPLICATION_SETTINGS";
    static constexpr auto ACTION_APP_LOCALE_SETTINGS = u8"android.settings.APP_LOCALE_SETTINGS";
    static constexpr auto ACTION_APP_NOTIFICATION_BUBBLE_SETTINGS = u8"android.settings.APP_NOTIFICATION_BUBBLE_SETTINGS";
    static constexpr auto ACTION_APP_NOTIFICATION_SETTINGS = u8"android.settings.APP_NOTIFICATION_SETTINGS";
    static constexpr auto ACTION_APP_OPEN_BY_DEFAULT_SETTINGS = u8"android.settings.APP_OPEN_BY_DEFAULT_SETTINGS";
    static constexpr auto ACTION_APP_SEARCH_SETTINGS = u8"android.settings.APP_SEARCH_SETTINGS";
    static constexpr auto ACTION_APP_USAGE_SETTINGS = u8"android.settings.action.APP_USAGE_SETTINGS";
    static constexpr auto ACTION_AUTOMATIC_ZEN_RULE_SETTINGS = u8"android.settings.AUTOMATIC_ZEN_RULE_SETTINGS";
    static constexpr auto ACTION_AUTO_ROTATE_SETTINGS = u8"android.settings.AUTO_ROTATE_SETTINGS";
    static constexpr auto ACTION_BATTERY_SAVER_SETTINGS = u8"android.settings.BATTERY_SAVER_SETTINGS";
    static constexpr auto ACTION_BIOMETRIC_ENROLL = u8"android.settings.BIOMETRIC_ENROLL";
    static constexpr auto ACTION_BLUETOOTH_SETTINGS = u8"android.settings.BLUETOOTH_SETTINGS";
    static constexpr auto ACTION_CAPTIONING_SETTINGS = u8"android.settings.CAPTIONING_SETTINGS";
    static constexpr auto ACTION_CAST_SETTINGS = u8"android.settings.CAST_SETTINGS";
    static constexpr auto ACTION_CHANNEL_NOTIFICATION_SETTINGS = u8"android.settings.CHANNEL_NOTIFICATION_SETTINGS";
    static constexpr auto ACTION_CONDITION_PROVIDER_SETTINGS = u8"android.settings.ACTION_CONDITION_PROVIDER_SETTINGS";
    static constexpr auto ACTION_CREDENTIAL_PROVIDER = u8"android.settings.CREDENTIAL_PROVIDER";
    static constexpr auto ACTION_DATA_ROAMING_SETTINGS = u8"android.settings.DATA_ROAMING_SETTINGS";
    static constexpr auto ACTION_DATA_USAGE_SETTINGS = u8"android.settings.DATA_USAGE_SETTINGS";
    static constexpr auto ACTION_DATE_SETTINGS = u8"android.settings.DATE_SETTINGS";
    static constexpr auto ACTION_DEVICE_INFO_SETTINGS = u8"android.settings.DEVICE_INFO_SETTINGS";
    static constexpr auto ACTION_DISPLAY_SETTINGS = u8"android.settings.DISPLAY_SETTINGS";
    static constexpr auto ACTION_DREAM_SETTINGS = u8"android.settings.DREAM_SETTINGS";
    static constexpr auto ACTION_FINGERPRINT_ENROLL = u8"android.settings.FINGERPRINT_ENROLL";
    static constexpr auto ACTION_HARD_KEYBOARD_SETTINGS = u8"android.settings.HARD_KEYBOARD_SETTINGS";
    static constexpr auto ACTION_HOME_SETTINGS = u8"android.settings.HOME_SETTINGS";
    static constexpr auto ACTION_IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS = u8"android.settings.IGNORE_BACKGROUND_DATA_RESTRICTIONS_SETTINGS";
    static constexpr auto ACTION_IGNORE_BATTERY_OPTIMIZATION_SETTINGS = u8"android.settings.IGNORE_BATTERY_OPTIMIZATION_SETTINGS";
    static constexpr auto ACTION_INPUT_METHOD_SETTINGS = u8"android.settings.INPUT_METHOD_SETTINGS";
    static constexpr auto ACTION_INPUT_METHOD_SUBTYPE_SETTINGS = u8"android.settings.INPUT_METHOD_SUBTYPE_SETTINGS";
    static constexpr auto ACTION_INTERNAL_STORAGE_SETTINGS = u8"android.settings.INTERNAL_STORAGE_SETTINGS";
    static constexpr auto ACTION_LOCALE_SETTINGS = u8"android.settings.LOCALE_SETTINGS";
    static constexpr auto ACTION_LOCATION_SOURCE_SETTINGS = u8"android.settings.LOCATION_SOURCE_SETTINGS";
    static constexpr auto ACTION_MANAGE_ALL_APPLICATIONS_SETTINGS = u8"android.settings.MANAGE_ALL_APPLICATIONS_SETTINGS";
    static constexpr auto ACTION_MANAGE_ALL_FILES_ACCESS_PERMISSION = u8"android.settings.MANAGE_ALL_FILES_ACCESS_PERMISSION";
    static constexpr auto ACTION_MANAGE_ALL_SIM_PROFILES_SETTINGS = u8"android.settings.MANAGE_ALL_SIM_PROFILES_SETTINGS";
    static constexpr auto ACTION_MANAGE_APPLICATIONS_SETTINGS = u8"android.settings.MANAGE_APPLICATIONS_SETTINGS";
    static constexpr auto ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION = u8"android.settings.MANAGE_APP_ALL_FILES_ACCESS_PERMISSION";
    static constexpr auto ACTION_MANAGE_APP_USE_FULL_SCREEN_INTENT = u8"android.settings.MANAGE_APP_USE_FULL_SCREEN_INTENT";
    static constexpr auto ACTION_MANAGE_DEFAULT_APPS_SETTINGS = u8"android.settings.MANAGE_DEFAULT_APPS_SETTINGS";
    static constexpr auto ACTION_MANAGE_OVERLAY_PERMISSION = u8"android.settings.action.MANAGE_OVERLAY_PERMISSION";
    static constexpr auto ACTION_MANAGE_SUPERVISOR_RESTRICTED_SETTING = u8"android.settings.MANAGE_SUPERVISOR_RESTRICTED_SETTING";
    static constexpr auto ACTION_MANAGE_UNKNOWN_APP_SOURCES = u8"android.settings.MANAGE_UNKNOWN_APP_SOURCES";
    static constexpr auto ACTION_MANAGE_WRITE_SETTINGS = u8"android.settings.action.MANAGE_WRITE_SETTINGS";
    static constexpr auto ACTION_MEMORY_CARD_SETTINGS = u8"android.settings.MEMORY_CARD_SETTINGS";
    static constexpr auto ACTION_NETWORK_OPERATOR_SETTINGS = u8"android.settings.NETWORK_OPERATOR_SETTINGS";
    static constexpr auto ACTION_NFCSHARING_SETTINGS = u8"android.settings.NFCSHARING_SETTINGS";
    static constexpr auto ACTION_NFC_PAYMENT_SETTINGS = u8"android.settings.NFC_PAYMENT_SETTINGS";
    static constexpr auto ACTION_NFC_SETTINGS = u8"android.settings.NFC_SETTINGS";
    static constexpr auto ACTION_NIGHT_DISPLAY_SETTINGS = u8"android.settings.NIGHT_DISPLAY_SETTINGS";
    static constexpr auto ACTION_NOTIFICATION_ASSISTANT_SETTINGS = u8"android.settings.NOTIFICATION_ASSISTANT_SETTINGS";
    static constexpr auto ACTION_NOTIFICATION_LISTENER_DETAIL_SETTINGS = u8"android.settings.NOTIFICATION_LISTENER_DETAIL_SETTINGS";
    static constexpr auto ACTION_NOTIFICATION_LISTENER_SETTINGS = u8"android.settings.ACTION_NOTIFICATION_LISTENER_SETTINGS";
    static constexpr auto ACTION_NOTIFICATION_POLICY_ACCESS_SETTINGS = u8"android.settings.NOTIFICATION_POLICY_ACCESS_SETTINGS";
    static constexpr auto ACTION_PRINT_SETTINGS = u8"android.settings.ACTION_PRINT_SETTINGS";
    static constexpr auto ACTION_PRIVACY_SETTINGS = u8"android.settings.PRIVACY_SETTINGS";
    static constexpr auto ACTION_PROCESS_WIFI_EASY_CONNECT_URI = u8"android.settings.PROCESS_WIFI_EASY_CONNECT_URI";
    static constexpr auto ACTION_QUICK_ACCESS_WALLET_SETTINGS = u8"android.settings.QUICK_ACCESS_WALLET_SETTINGS";
    static constexpr auto ACTION_QUICK_LAUNCH_SETTINGS = u8"android.settings.QUICK_LAUNCH_SETTINGS";
    static constexpr auto ACTION_REGIONAL_PREFERENCES_SETTINGS = u8"android.settings.REGIONAL_PREFERENCES_SETTINGS";
    static constexpr auto ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS = u8"android.settings.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS";
    static constexpr auto ACTION_REQUEST_MANAGE_MEDIA = u8"android.settings.REQUEST_MANAGE_MEDIA";
    static constexpr auto ACTION_REQUEST_MEDIA_ROUTING_CONTROL = u8"android.settings.REQUEST_MEDIA_ROUTING_CONTROL";
    static constexpr auto ACTION_REQUEST_SCHEDULE_EXACT_ALARM = u8"android.settings.REQUEST_SCHEDULE_EXACT_ALARM";
    static constexpr auto ACTION_REQUEST_SET_AUTOFILL_SERVICE = u8"android.settings.REQUEST_SET_AUTOFILL_SERVICE";
    static constexpr auto ACTION_SATELLITE_SETTING = u8"android.settings.SATELLITE_SETTING";
    static constexpr auto ACTION_SEARCH_SETTINGS = u8"android.search.action.SEARCH_SETTINGS";
    static constexpr auto ACTION_SECURITY_SETTINGS = u8"android.settings.SECURITY_SETTINGS";
    static constexpr auto ACTION_SETTINGS = u8"android.settings.SETTINGS";
    static constexpr auto ACTION_SETTINGS_EMBED_DEEP_LINK_ACTIVITY = u8"android.settings.SETTINGS_EMBED_DEEP_LINK_ACTIVITY";
    static constexpr auto ACTION_SHOW_REGULATORY_INFO = u8"android.settings.SHOW_REGULATORY_INFO";
    static constexpr auto ACTION_SHOW_WORK_POLICY_INFO = u8"android.settings.SHOW_WORK_POLICY_INFO";
    static constexpr auto ACTION_SOUND_SETTINGS = u8"android.settings.SOUND_SETTINGS";
    static constexpr auto ACTION_STORAGE_VOLUME_ACCESS_SETTINGS = u8"android.settings.STORAGE_VOLUME_ACCESS_SETTINGS";
    static constexpr auto ACTION_SYNC_SETTINGS = u8"android.settings.SYNC_SETTINGS";
    static constexpr auto ACTION_USAGE_ACCESS_SETTINGS = u8"android.settings.USAGE_ACCESS_SETTINGS";
    static constexpr auto ACTION_USER_DICTIONARY_SETTINGS = u8"android.settings.USER_DICTIONARY_SETTINGS";
    static constexpr auto ACTION_VOICE_CONTROL_AIRPLANE_MODE = u8"android.settings.VOICE_CONTROL_AIRPLANE_MODE";
    static constexpr auto ACTION_VOICE_CONTROL_BATTERY_SAVER_MODE = u8"android.settings.VOICE_CONTROL_BATTERY_SAVER_MODE";
    static constexpr auto ACTION_VOICE_CONTROL_DO_NOT_DISTURB_MODE = u8"android.settings.VOICE_CONTROL_DO_NOT_DISTURB_MODE";
    static constexpr auto ACTION_VOICE_INPUT_SETTINGS = u8"android.settings.VOICE_INPUT_SETTINGS";
    static constexpr auto ACTION_VPN_SETTINGS = u8"android.settings.VPN_SETTINGS";
    static constexpr auto ACTION_VR_LISTENER_SETTINGS = u8"android.settings.VR_LISTENER_SETTINGS";
    static constexpr auto ACTION_WEBVIEW_SETTINGS = u8"android.settings.WEBVIEW_SETTINGS";
    static constexpr auto ACTION_WIFI_ADD_NETWORKS = u8"android.settings.WIFI_ADD_NETWORKS";
    static constexpr auto ACTION_WIFI_IP_SETTINGS = u8"android.settings.WIFI_IP_SETTINGS";
    static constexpr auto ACTION_WIFI_SETTINGS = u8"android.settings.WIFI_SETTINGS";
    static constexpr auto ACTION_WIRELESS_SETTINGS = u8"android.settings.WIRELESS_SETTINGS";
    static constexpr auto ACTION_ZEN_MODE_PRIORITY_SETTINGS = u8"android.settings.ZEN_MODE_PRIORITY_SETTINGS";
    static constexpr jint ADD_WIFI_RESULT_ADD_OR_UPDATE_FAILED = 1;
    static constexpr jint ADD_WIFI_RESULT_ALREADY_EXISTS = 2;
    static constexpr jint ADD_WIFI_RESULT_SUCCESS = 0;
    static constexpr auto AUTHORITY = u8"settings";
    static constexpr auto EXTRA_ACCOUNT_TYPES = u8"account_types";
    static constexpr auto EXTRA_AIRPLANE_MODE_ENABLED = u8"airplane_mode_enabled";
    static constexpr auto EXTRA_APP_PACKAGE = u8"android.provider.extra.APP_PACKAGE";
    static constexpr auto EXTRA_AUTHORITIES = u8"authorities";
    static constexpr auto EXTRA_AUTOMATIC_ZEN_RULE_ID = u8"android.provider.extra.AUTOMATIC_ZEN_RULE_ID";
    static constexpr auto EXTRA_BATTERY_SAVER_MODE_ENABLED = u8"android.settings.extra.battery_saver_mode_enabled";
    static constexpr auto EXTRA_BIOMETRIC_AUTHENTICATORS_ALLOWED = u8"android.provider.extra.BIOMETRIC_AUTHENTICATORS_ALLOWED";
    static constexpr auto EXTRA_CHANNEL_FILTER_LIST = u8"android.provider.extra.CHANNEL_FILTER_LIST";
    static constexpr auto EXTRA_CHANNEL_ID = u8"android.provider.extra.CHANNEL_ID";
    static constexpr auto EXTRA_CONVERSATION_ID = u8"android.provider.extra.CONVERSATION_ID";
    static constexpr auto EXTRA_DO_NOT_DISTURB_MODE_ENABLED = u8"android.settings.extra.do_not_disturb_mode_enabled";
    static constexpr auto EXTRA_DO_NOT_DISTURB_MODE_MINUTES = u8"android.settings.extra.do_not_disturb_mode_minutes";
    static constexpr auto EXTRA_EASY_CONNECT_ATTEMPTED_SSID = u8"android.provider.extra.EASY_CONNECT_ATTEMPTED_SSID";
    static constexpr auto EXTRA_EASY_CONNECT_BAND_LIST = u8"android.provider.extra.EASY_CONNECT_BAND_LIST";
    static constexpr auto EXTRA_EASY_CONNECT_CHANNEL_LIST = u8"android.provider.extra.EASY_CONNECT_CHANNEL_LIST";
    static constexpr auto EXTRA_EASY_CONNECT_ERROR_CODE = u8"android.provider.extra.EASY_CONNECT_ERROR_CODE";
    static constexpr auto EXTRA_INPUT_METHOD_ID = u8"input_method_id";
    static constexpr auto EXTRA_NOTIFICATION_LISTENER_COMPONENT_NAME = u8"android.provider.extra.NOTIFICATION_LISTENER_COMPONENT_NAME";
    static constexpr auto EXTRA_SETTINGS_EMBEDDED_DEEP_LINK_HIGHLIGHT_MENU_KEY = u8"android.provider.extra.SETTINGS_EMBEDDED_DEEP_LINK_HIGHLIGHT_MENU_KEY";
    static constexpr auto EXTRA_SETTINGS_EMBEDDED_DEEP_LINK_INTENT_URI = u8"android.provider.extra.SETTINGS_EMBEDDED_DEEP_LINK_INTENT_URI";
    static constexpr auto EXTRA_SUB_ID = u8"android.provider.extra.SUB_ID";
    static constexpr auto EXTRA_SUPERVISOR_RESTRICTED_SETTING_KEY = u8"android.provider.extra.SUPERVISOR_RESTRICTED_SETTING_KEY";
    static constexpr auto EXTRA_WIFI_NETWORK_LIST = u8"android.provider.extra.WIFI_NETWORK_LIST";
    static constexpr auto EXTRA_WIFI_NETWORK_RESULT_LIST = u8"android.provider.extra.WIFI_NETWORK_RESULT_LIST";
    static constexpr auto INTENT_CATEGORY_USAGE_ACCESS_CONFIG = u8"android.intent.category.USAGE_ACCESS_CONFIG";
    static constexpr auto METADATA_USAGE_ACCESS_REASON = u8"android.settings.metadata.USAGE_ACCESS_REASON";
    static constexpr jint SUPERVISOR_VERIFICATION_SETTING_BIOMETRICS = 1;
    static constexpr jint SUPERVISOR_VERIFICATION_SETTING_UNKNOWN = 0;


    // construct: public Settings()
    static SettingsProxy newInstance() {
        SettingsProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "()V");
        return ret;
    }

    // method: public static boolean canDrawOverlays(android.content.Context context)
    static auto canDrawOverlays(jobject context) {
        return QJniObject::callStaticMethod<jboolean>(FULL_CLASS_NAME,
                        "canDrawOverlays",
                        "(Landroid/content/Context;)Z", context);
    }


};
} } // endof namespace android::provider


namespace android { namespace provider {


} } // endof namespace android::provider

#endif // android_provider_SettingsProxy_H

