
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_app_NotificationChannelProxy_H
#define android_app_NotificationChannelProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace app {
class NotificationChannelProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/app/NotificationChannel";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    NotificationChannelProxy() {}
    NotificationChannelProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    NotificationChannelProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static NotificationChannelProxy fromLocalRef(jobject localRef) {
        NotificationChannelProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr auto DEFAULT_CHANNEL_ID = u8"miscellaneous";
    static constexpr auto EDIT_CONVERSATION = u8"conversation";
    static constexpr auto EDIT_IMPORTANCE = u8"importance";
    static constexpr auto EDIT_LAUNCHER = u8"launcher";
    static constexpr auto EDIT_LOCKED_DEVICE = u8"locked";
    static constexpr auto EDIT_SOUND = u8"sound";
    static constexpr auto EDIT_VIBRATION = u8"vibration";
    static constexpr auto EDIT_ZEN = u8"zen";


    // construct: public NotificationChannel(java.lang.String id, java.lang.CharSequence name, int importance)
    static NotificationChannelProxy newInstance(jstring id, jobject name, jint importance) {
        NotificationChannelProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Ljava/lang/String;Ljava/lang/CharSequence;I)V", id, name, importance);
        return ret;
    }

    // method: public void writeToParcel(android.os.Parcel dest, int flags)
    auto writeToParcel(jobject dest, jint flags) const {
        m_jniObject.callMethod<void>(
                        "writeToParcel",
                        "(Landroid/os/Parcel;I)V", dest, flags);
    }


    // method: public void setBlockable(boolean blockable)
    auto setBlockable(jboolean blockable) const {
        m_jniObject.callMethod<void>(
                        "setBlockable",
                        "(Z)V", blockable);
    }


    // method: public void setName(java.lang.CharSequence name)
    auto setName(jobject name) const {
        m_jniObject.callMethod<void>(
                        "setName",
                        "(Ljava/lang/CharSequence;)V", name);
    }


    // method: public void setDescription(java.lang.String description)
    auto setDescription(jstring description) const {
        m_jniObject.callMethod<void>(
                        "setDescription",
                        "(Ljava/lang/String;)V", description);
    }


    // method: public void setGroup(java.lang.String groupId)
    auto setGroup(jstring groupId) const {
        m_jniObject.callMethod<void>(
                        "setGroup",
                        "(Ljava/lang/String;)V", groupId);
    }


    // method: public void setShowBadge(boolean showBadge)
    auto setShowBadge(jboolean showBadge) const {
        m_jniObject.callMethod<void>(
                        "setShowBadge",
                        "(Z)V", showBadge);
    }


    // method: public void setSound(android.net.Uri sound, android.media.AudioAttributes audioAttributes)
    auto setSound(jobject sound, jobject audioAttributes) const {
        m_jniObject.callMethod<void>(
                        "setSound",
                        "(Landroid/net/Uri;Landroid/media/AudioAttributes;)V", sound, audioAttributes);
    }


    // method: public void enableLights(boolean lights)
    auto enableLights(jboolean lights) const {
        m_jniObject.callMethod<void>(
                        "enableLights",
                        "(Z)V", lights);
    }


    // method: public void setLightColor(int argb)
    auto setLightColor(jint argb) const {
        m_jniObject.callMethod<void>(
                        "setLightColor",
                        "(I)V", argb);
    }


    // method: public void enableVibration(boolean vibration)
    auto enableVibration(jboolean vibration) const {
        m_jniObject.callMethod<void>(
                        "enableVibration",
                        "(Z)V", vibration);
    }


    // method: public void setVibrationPattern(long[] vibrationPattern)
    auto setVibrationPattern(jlongArray vibrationPattern) const {
        m_jniObject.callMethod<void>(
                        "setVibrationPattern",
                        "([J)V", vibrationPattern);
    }


    // method: public void setVibrationEffect(android.os.VibrationEffect effect)
    auto setVibrationEffect(jobject effect) const {
        m_jniObject.callMethod<void>(
                        "setVibrationEffect",
                        "(Landroid/os/VibrationEffect;)V", effect);
    }


    // method: public void setImportance(int importance)
    auto setImportance(jint importance) const {
        m_jniObject.callMethod<void>(
                        "setImportance",
                        "(I)V", importance);
    }


    // method: public void setBypassDnd(boolean bypassDnd)
    auto setBypassDnd(jboolean bypassDnd) const {
        m_jniObject.callMethod<void>(
                        "setBypassDnd",
                        "(Z)V", bypassDnd);
    }


    // method: public void setLockscreenVisibility(int lockscreenVisibility)
    auto setLockscreenVisibility(jint lockscreenVisibility) const {
        m_jniObject.callMethod<void>(
                        "setLockscreenVisibility",
                        "(I)V", lockscreenVisibility);
    }


    // method: public void setAllowBubbles(boolean allowBubbles)
    auto setAllowBubbles(jboolean allowBubbles) const {
        m_jniObject.callMethod<void>(
                        "setAllowBubbles",
                        "(Z)V", allowBubbles);
    }


    // method: public void setConversationId(java.lang.String parentChannelId, java.lang.String conversationId)
    auto setConversationId(jstring parentChannelId, jstring conversationId) const {
        m_jniObject.callMethod<void>(
                        "setConversationId",
                        "(Ljava/lang/String;Ljava/lang/String;)V", parentChannelId, conversationId);
    }


    // method: public java.lang.String getId()
    auto getId() const {
        return m_jniObject.callMethod<jstring>(
                        "getId",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.CharSequence getName()
    auto getName() const {
        return m_jniObject.callMethod<jobject>(
                        "getName",
                        "()Ljava/lang/CharSequence;");
    }


    // method: public java.lang.String getDescription()
    auto getDescription() const {
        return m_jniObject.callMethod<jstring>(
                        "getDescription",
                        "()Ljava/lang/String;");
    }


    // method: public int getImportance()
    auto getImportance() const {
        return m_jniObject.callMethod<jint>(
                        "getImportance",
                        "()I");
    }


    // method: public boolean canBypassDnd()
    auto canBypassDnd() const {
        return m_jniObject.callMethod<jboolean>(
                        "canBypassDnd",
                        "()Z");
    }


    // method: public boolean isConversation()
    auto isConversation() const {
        return m_jniObject.callMethod<jboolean>(
                        "isConversation",
                        "()Z");
    }


    // method: public boolean isImportantConversation()
    auto isImportantConversation() const {
        return m_jniObject.callMethod<jboolean>(
                        "isImportantConversation",
                        "()Z");
    }


    // method: public android.net.Uri getSound()
    auto getSound() const {
        return m_jniObject.callMethod<jobject>(
                        "getSound",
                        "()Landroid/net/Uri;");
    }


    // method: public android.media.AudioAttributes getAudioAttributes()
    auto getAudioAttributes() const {
        return m_jniObject.callMethod<jobject>(
                        "getAudioAttributes",
                        "()Landroid/media/AudioAttributes;");
    }


    // method: public boolean shouldShowLights()
    auto shouldShowLights() const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldShowLights",
                        "()Z");
    }


    // method: public int getLightColor()
    auto getLightColor() const {
        return m_jniObject.callMethod<jint>(
                        "getLightColor",
                        "()I");
    }


    // method: public boolean shouldVibrate()
    auto shouldVibrate() const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldVibrate",
                        "()Z");
    }


    // method: public long[] getVibrationPattern()
    auto getVibrationPattern() const {
        return m_jniObject.callMethod<jlongArray>(
                        "getVibrationPattern",
                        "()[J");
    }


    // method: public android.os.VibrationEffect getVibrationEffect()
    auto getVibrationEffect() const {
        return m_jniObject.callMethod<jobject>(
                        "getVibrationEffect",
                        "()Landroid/os/VibrationEffect;");
    }


    // method: public int getLockscreenVisibility()
    auto getLockscreenVisibility() const {
        return m_jniObject.callMethod<jint>(
                        "getLockscreenVisibility",
                        "()I");
    }


    // method: public boolean canShowBadge()
    auto canShowBadge() const {
        return m_jniObject.callMethod<jboolean>(
                        "canShowBadge",
                        "()Z");
    }


    // method: public java.lang.String getGroup()
    auto getGroup() const {
        return m_jniObject.callMethod<jstring>(
                        "getGroup",
                        "()Ljava/lang/String;");
    }


    // method: public boolean canBubble()
    auto canBubble() const {
        return m_jniObject.callMethod<jboolean>(
                        "canBubble",
                        "()Z");
    }


    // method: public java.lang.String getParentChannelId()
    auto getParentChannelId() const {
        return m_jniObject.callMethod<jstring>(
                        "getParentChannelId",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String getConversationId()
    auto getConversationId() const {
        return m_jniObject.callMethod<jstring>(
                        "getConversationId",
                        "()Ljava/lang/String;");
    }


    // method: public boolean isBlockable()
    auto isBlockable() const {
        return m_jniObject.callMethod<jboolean>(
                        "isBlockable",
                        "()Z");
    }


    // method: public boolean isDemoted()
    auto isDemoted() const {
        return m_jniObject.callMethod<jboolean>(
                        "isDemoted",
                        "()Z");
    }


    // method: public boolean hasUserSetImportance()
    auto hasUserSetImportance() const {
        return m_jniObject.callMethod<jboolean>(
                        "hasUserSetImportance",
                        "()Z");
    }


    // method: public boolean hasUserSetSound()
    auto hasUserSetSound() const {
        return m_jniObject.callMethod<jboolean>(
                        "hasUserSetSound",
                        "()Z");
    }


    // method: public int describeContents()
    auto describeContents() const {
        return m_jniObject.callMethod<jint>(
                        "describeContents",
                        "()I");
    }


    // method: public boolean equals(java.lang.Object o)
    auto equals(jobject o) const {
        return m_jniObject.callMethod<jboolean>(
                        "equals",
                        "(Ljava/lang/Object;)Z", o);
    }


    // method: public int hashCode()
    auto hashCode() const {
        return m_jniObject.callMethod<jint>(
                        "hashCode",
                        "()I");
    }


    // method: public java.lang.String toString()
    auto toString() const {
        return m_jniObject.callMethod<jstring>(
                        "toString",
                        "()Ljava/lang/String;");
    }


    // field: public static final android.os.Parcelable.Creator<android.app.NotificationChannel> CREATOR
    static auto getCREATOR() {
       return QJniObject::getStaticField<jobject>(FULL_CLASS_NAME,"CREATOR");

    }

    // field: public static final android.os.Parcelable.Creator<android.app.NotificationChannel> CREATOR
    static void setCREATOR(jobject CREATOR) {
        QJniObject::setStaticField(FULL_CLASS_NAME,"CREATOR", CREATOR);
    }


};
} } // endof namespace android::app


namespace android { namespace app {


} } // endof namespace android::app

#endif // android_app_NotificationChannelProxy_H

