
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_content_IntentProxy_H
#define android_content_IntentProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace content {
class IntentProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/content/Intent";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    IntentProxy() {}
    IntentProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    IntentProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static IntentProxy fromLocalRef(jobject localRef) {
        IntentProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr auto ACTION_AIRPLANE_MODE_CHANGED = u8"android.intent.action.AIRPLANE_MODE";
    static constexpr auto ACTION_ALL_APPS = u8"android.intent.action.ALL_APPS";
    static constexpr auto ACTION_ANSWER = u8"android.intent.action.ANSWER";
    static constexpr auto ACTION_APPLICATION_LOCALE_CHANGED = u8"android.intent.action.APPLICATION_LOCALE_CHANGED";
    static constexpr auto ACTION_APPLICATION_PREFERENCES = u8"android.intent.action.APPLICATION_PREFERENCES";
    static constexpr auto ACTION_APPLICATION_RESTRICTIONS_CHANGED = u8"android.intent.action.APPLICATION_RESTRICTIONS_CHANGED";
    static constexpr auto ACTION_APP_ERROR = u8"android.intent.action.APP_ERROR";
    static constexpr auto ACTION_ASSIST = u8"android.intent.action.ASSIST";
    static constexpr auto ACTION_ATTACH_DATA = u8"android.intent.action.ATTACH_DATA";
    static constexpr auto ACTION_AUTO_REVOKE_PERMISSIONS = u8"android.intent.action.AUTO_REVOKE_PERMISSIONS";
    static constexpr auto ACTION_BATTERY_CHANGED = u8"android.intent.action.BATTERY_CHANGED";
    static constexpr auto ACTION_BATTERY_LOW = u8"android.intent.action.BATTERY_LOW";
    static constexpr auto ACTION_BATTERY_OKAY = u8"android.intent.action.BATTERY_OKAY";
    static constexpr auto ACTION_BOOT_COMPLETED = u8"android.intent.action.BOOT_COMPLETED";
    static constexpr auto ACTION_BUG_REPORT = u8"android.intent.action.BUG_REPORT";
    static constexpr auto ACTION_CALL = u8"android.intent.action.CALL";
    static constexpr auto ACTION_CALL_BUTTON = u8"android.intent.action.CALL_BUTTON";
    static constexpr auto ACTION_CAMERA_BUTTON = u8"android.intent.action.CAMERA_BUTTON";
    static constexpr auto ACTION_CARRIER_SETUP = u8"android.intent.action.CARRIER_SETUP";
    static constexpr auto ACTION_CHOOSER = u8"android.intent.action.CHOOSER";
    static constexpr auto ACTION_CLOSE_SYSTEM_DIALOGS = u8"android.intent.action.CLOSE_SYSTEM_DIALOGS";
    static constexpr auto ACTION_CONFIGURATION_CHANGED = u8"android.intent.action.CONFIGURATION_CHANGED";
    static constexpr auto ACTION_CREATE_DOCUMENT = u8"android.intent.action.CREATE_DOCUMENT";
    static constexpr auto ACTION_CREATE_NOTE = u8"android.intent.action.CREATE_NOTE";
    static constexpr auto ACTION_CREATE_REMINDER = u8"android.intent.action.CREATE_REMINDER";
    static constexpr auto ACTION_CREATE_SHORTCUT = u8"android.intent.action.CREATE_SHORTCUT";
    static constexpr auto ACTION_DATE_CHANGED = u8"android.intent.action.DATE_CHANGED";
    static constexpr auto ACTION_DEFAULT = u8"android.intent.action.VIEW";
    static constexpr auto ACTION_DEFINE = u8"android.intent.action.DEFINE";
    static constexpr auto ACTION_DELETE = u8"android.intent.action.DELETE";
    static constexpr auto ACTION_DEVICE_STORAGE_LOW = u8"android.intent.action.DEVICE_STORAGE_LOW";
    static constexpr auto ACTION_DEVICE_STORAGE_OK = u8"android.intent.action.DEVICE_STORAGE_OK";
    static constexpr auto ACTION_DIAL = u8"android.intent.action.DIAL";
    static constexpr auto ACTION_DOCK_EVENT = u8"android.intent.action.DOCK_EVENT";
    static constexpr auto ACTION_DREAMING_STARTED = u8"android.intent.action.DREAMING_STARTED";
    static constexpr auto ACTION_DREAMING_STOPPED = u8"android.intent.action.DREAMING_STOPPED";
    static constexpr auto ACTION_EDIT = u8"android.intent.action.EDIT";
    static constexpr auto ACTION_EXTERNAL_APPLICATIONS_AVAILABLE = u8"android.intent.action.EXTERNAL_APPLICATIONS_AVAILABLE";
    static constexpr auto ACTION_EXTERNAL_APPLICATIONS_UNAVAILABLE = u8"android.intent.action.EXTERNAL_APPLICATIONS_UNAVAILABLE";
    static constexpr auto ACTION_FACTORY_TEST = u8"android.intent.action.FACTORY_TEST";
    static constexpr auto ACTION_GET_CONTENT = u8"android.intent.action.GET_CONTENT";
    static constexpr auto ACTION_GET_RESTRICTION_ENTRIES = u8"android.intent.action.GET_RESTRICTION_ENTRIES";
    static constexpr auto ACTION_GTALK_SERVICE_CONNECTED = u8"android.intent.action.GTALK_CONNECTED";
    static constexpr auto ACTION_GTALK_SERVICE_DISCONNECTED = u8"android.intent.action.GTALK_DISCONNECTED";
    static constexpr auto ACTION_HEADSET_PLUG = u8"android.intent.action.HEADSET_PLUG";
    static constexpr auto ACTION_INPUT_METHOD_CHANGED = u8"android.intent.action.INPUT_METHOD_CHANGED";
    static constexpr auto ACTION_INSERT = u8"android.intent.action.INSERT";
    static constexpr auto ACTION_INSERT_OR_EDIT = u8"android.intent.action.INSERT_OR_EDIT";
    static constexpr auto ACTION_INSTALL_FAILURE = u8"android.intent.action.INSTALL_FAILURE";
    static constexpr auto ACTION_INSTALL_PACKAGE = u8"android.intent.action.INSTALL_PACKAGE";
    static constexpr auto ACTION_LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE = u8"android.intent.action.LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE";
    static constexpr auto ACTION_LOCALE_CHANGED = u8"android.intent.action.LOCALE_CHANGED";
    static constexpr auto ACTION_LOCKED_BOOT_COMPLETED = u8"android.intent.action.LOCKED_BOOT_COMPLETED";
    static constexpr auto ACTION_MAIN = u8"android.intent.action.MAIN";
    static constexpr auto ACTION_MANAGED_PROFILE_ADDED = u8"android.intent.action.MANAGED_PROFILE_ADDED";
    static constexpr auto ACTION_MANAGED_PROFILE_AVAILABLE = u8"android.intent.action.MANAGED_PROFILE_AVAILABLE";
    static constexpr auto ACTION_MANAGED_PROFILE_REMOVED = u8"android.intent.action.MANAGED_PROFILE_REMOVED";
    static constexpr auto ACTION_MANAGED_PROFILE_UNAVAILABLE = u8"android.intent.action.MANAGED_PROFILE_UNAVAILABLE";
    static constexpr auto ACTION_MANAGED_PROFILE_UNLOCKED = u8"android.intent.action.MANAGED_PROFILE_UNLOCKED";
    static constexpr auto ACTION_MANAGE_NETWORK_USAGE = u8"android.intent.action.MANAGE_NETWORK_USAGE";
    static constexpr auto ACTION_MANAGE_PACKAGE_STORAGE = u8"android.intent.action.MANAGE_PACKAGE_STORAGE";
    static constexpr auto ACTION_MANAGE_UNUSED_APPS = u8"android.intent.action.MANAGE_UNUSED_APPS";
    static constexpr auto ACTION_MEDIA_BAD_REMOVAL = u8"android.intent.action.MEDIA_BAD_REMOVAL";
    static constexpr auto ACTION_MEDIA_BUTTON = u8"android.intent.action.MEDIA_BUTTON";
    static constexpr auto ACTION_MEDIA_CHECKING = u8"android.intent.action.MEDIA_CHECKING";
    static constexpr auto ACTION_MEDIA_EJECT = u8"android.intent.action.MEDIA_EJECT";
    static constexpr auto ACTION_MEDIA_MOUNTED = u8"android.intent.action.MEDIA_MOUNTED";
    static constexpr auto ACTION_MEDIA_NOFS = u8"android.intent.action.MEDIA_NOFS";
    static constexpr auto ACTION_MEDIA_REMOVED = u8"android.intent.action.MEDIA_REMOVED";
    static constexpr auto ACTION_MEDIA_SCANNER_FINISHED = u8"android.intent.action.MEDIA_SCANNER_FINISHED";
    static constexpr auto ACTION_MEDIA_SCANNER_SCAN_FILE = u8"android.intent.action.MEDIA_SCANNER_SCAN_FILE";
    static constexpr auto ACTION_MEDIA_SCANNER_STARTED = u8"android.intent.action.MEDIA_SCANNER_STARTED";
    static constexpr auto ACTION_MEDIA_SHARED = u8"android.intent.action.MEDIA_SHARED";
    static constexpr auto ACTION_MEDIA_UNMOUNTABLE = u8"android.intent.action.MEDIA_UNMOUNTABLE";
    static constexpr auto ACTION_MEDIA_UNMOUNTED = u8"android.intent.action.MEDIA_UNMOUNTED";
    static constexpr auto ACTION_MY_PACKAGE_REPLACED = u8"android.intent.action.MY_PACKAGE_REPLACED";
    static constexpr auto ACTION_MY_PACKAGE_SUSPENDED = u8"android.intent.action.MY_PACKAGE_SUSPENDED";
    static constexpr auto ACTION_MY_PACKAGE_UNSUSPENDED = u8"android.intent.action.MY_PACKAGE_UNSUSPENDED";
    static constexpr auto ACTION_NEW_OUTGOING_CALL = u8"android.intent.action.NEW_OUTGOING_CALL";
    static constexpr auto ACTION_OPEN_DOCUMENT = u8"android.intent.action.OPEN_DOCUMENT";
    static constexpr auto ACTION_OPEN_DOCUMENT_TREE = u8"android.intent.action.OPEN_DOCUMENT_TREE";
    static constexpr auto ACTION_PACKAGES_SUSPENDED = u8"android.intent.action.PACKAGES_SUSPENDED";
    static constexpr auto ACTION_PACKAGES_UNSUSPENDED = u8"android.intent.action.PACKAGES_UNSUSPENDED";
    static constexpr auto ACTION_PACKAGE_ADDED = u8"android.intent.action.PACKAGE_ADDED";
    static constexpr auto ACTION_PACKAGE_CHANGED = u8"android.intent.action.PACKAGE_CHANGED";
    static constexpr auto ACTION_PACKAGE_DATA_CLEARED = u8"android.intent.action.PACKAGE_DATA_CLEARED";
    static constexpr auto ACTION_PACKAGE_FIRST_LAUNCH = u8"android.intent.action.PACKAGE_FIRST_LAUNCH";
    static constexpr auto ACTION_PACKAGE_FULLY_REMOVED = u8"android.intent.action.PACKAGE_FULLY_REMOVED";
    static constexpr auto ACTION_PACKAGE_INSTALL = u8"android.intent.action.PACKAGE_INSTALL";
    static constexpr auto ACTION_PACKAGE_NEEDS_VERIFICATION = u8"android.intent.action.PACKAGE_NEEDS_VERIFICATION";
    static constexpr auto ACTION_PACKAGE_REMOVED = u8"android.intent.action.PACKAGE_REMOVED";
    static constexpr auto ACTION_PACKAGE_REPLACED = u8"android.intent.action.PACKAGE_REPLACED";
    static constexpr auto ACTION_PACKAGE_RESTARTED = u8"android.intent.action.PACKAGE_RESTARTED";
    static constexpr auto ACTION_PACKAGE_UNSTOPPED = u8"android.intent.action.PACKAGE_UNSTOPPED";
    static constexpr auto ACTION_PACKAGE_VERIFIED = u8"android.intent.action.PACKAGE_VERIFIED";
    static constexpr auto ACTION_PASTE = u8"android.intent.action.PASTE";
    static constexpr auto ACTION_PICK = u8"android.intent.action.PICK";
    static constexpr auto ACTION_PICK_ACTIVITY = u8"android.intent.action.PICK_ACTIVITY";
    static constexpr auto ACTION_POWER_CONNECTED = u8"android.intent.action.ACTION_POWER_CONNECTED";
    static constexpr auto ACTION_POWER_DISCONNECTED = u8"android.intent.action.ACTION_POWER_DISCONNECTED";
    static constexpr auto ACTION_POWER_USAGE_SUMMARY = u8"android.intent.action.POWER_USAGE_SUMMARY";
    static constexpr auto ACTION_PROCESS_TEXT = u8"android.intent.action.PROCESS_TEXT";
    static constexpr auto ACTION_PROFILE_ACCESSIBLE = u8"android.intent.action.PROFILE_ACCESSIBLE";
    static constexpr auto ACTION_PROFILE_ADDED = u8"android.intent.action.PROFILE_ADDED";
    static constexpr auto ACTION_PROFILE_AVAILABLE = u8"android.intent.action.PROFILE_AVAILABLE";
    static constexpr auto ACTION_PROFILE_INACCESSIBLE = u8"android.intent.action.PROFILE_INACCESSIBLE";
    static constexpr auto ACTION_PROFILE_REMOVED = u8"android.intent.action.PROFILE_REMOVED";
    static constexpr auto ACTION_PROFILE_UNAVAILABLE = u8"android.intent.action.PROFILE_UNAVAILABLE";
    static constexpr auto ACTION_PROVIDER_CHANGED = u8"android.intent.action.PROVIDER_CHANGED";
    static constexpr auto ACTION_QUICK_CLOCK = u8"android.intent.action.QUICK_CLOCK";
    static constexpr auto ACTION_QUICK_VIEW = u8"android.intent.action.QUICK_VIEW";
    static constexpr auto ACTION_REBOOT = u8"android.intent.action.REBOOT";
    static constexpr auto ACTION_RUN = u8"android.intent.action.RUN";
    static constexpr auto ACTION_SAFETY_CENTER = u8"android.intent.action.SAFETY_CENTER";
    static constexpr auto ACTION_SCREEN_OFF = u8"android.intent.action.SCREEN_OFF";
    static constexpr auto ACTION_SCREEN_ON = u8"android.intent.action.SCREEN_ON";
    static constexpr auto ACTION_SEARCH = u8"android.intent.action.SEARCH";
    static constexpr auto ACTION_SEARCH_LONG_PRESS = u8"android.intent.action.SEARCH_LONG_PRESS";
    static constexpr auto ACTION_SEND = u8"android.intent.action.SEND";
    static constexpr auto ACTION_SENDTO = u8"android.intent.action.SENDTO";
    static constexpr auto ACTION_SEND_MULTIPLE = u8"android.intent.action.SEND_MULTIPLE";
    static constexpr auto ACTION_SET_WALLPAPER = u8"android.intent.action.SET_WALLPAPER";
    static constexpr auto ACTION_SHOW_APP_INFO = u8"android.intent.action.SHOW_APP_INFO";
    static constexpr auto ACTION_SHOW_WORK_APPS = u8"android.intent.action.SHOW_WORK_APPS";
    static constexpr auto ACTION_SHUTDOWN = u8"android.intent.action.ACTION_SHUTDOWN";
    static constexpr auto ACTION_SYNC = u8"android.intent.action.SYNC";
    static constexpr auto ACTION_SYSTEM_TUTORIAL = u8"android.intent.action.SYSTEM_TUTORIAL";
    static constexpr auto ACTION_TIMEZONE_CHANGED = u8"android.intent.action.TIMEZONE_CHANGED";
    static constexpr auto ACTION_TIME_CHANGED = u8"android.intent.action.TIME_SET";
    static constexpr auto ACTION_TIME_TICK = u8"android.intent.action.TIME_TICK";
    static constexpr auto ACTION_TRANSLATE = u8"android.intent.action.TRANSLATE";
    static constexpr auto ACTION_UID_REMOVED = u8"android.intent.action.UID_REMOVED";
    static constexpr auto ACTION_UMS_CONNECTED = u8"android.intent.action.UMS_CONNECTED";
    static constexpr auto ACTION_UMS_DISCONNECTED = u8"android.intent.action.UMS_DISCONNECTED";
    static constexpr auto ACTION_UNARCHIVE_PACKAGE = u8"android.intent.action.UNARCHIVE_PACKAGE";
    static constexpr auto ACTION_UNINSTALL_PACKAGE = u8"android.intent.action.UNINSTALL_PACKAGE";
    static constexpr auto ACTION_USER_BACKGROUND = u8"android.intent.action.USER_BACKGROUND";
    static constexpr auto ACTION_USER_FOREGROUND = u8"android.intent.action.USER_FOREGROUND";
    static constexpr auto ACTION_USER_INITIALIZE = u8"android.intent.action.USER_INITIALIZE";
    static constexpr auto ACTION_USER_PRESENT = u8"android.intent.action.USER_PRESENT";
    static constexpr auto ACTION_USER_UNLOCKED = u8"android.intent.action.USER_UNLOCKED";
    static constexpr auto ACTION_VIEW = u8"android.intent.action.VIEW";
    static constexpr auto ACTION_VIEW_LOCUS = u8"android.intent.action.VIEW_LOCUS";
    static constexpr auto ACTION_VIEW_PERMISSION_USAGE = u8"android.intent.action.VIEW_PERMISSION_USAGE";
    static constexpr auto ACTION_VIEW_PERMISSION_USAGE_FOR_PERIOD = u8"android.intent.action.VIEW_PERMISSION_USAGE_FOR_PERIOD";
    static constexpr auto ACTION_VOICE_COMMAND = u8"android.intent.action.VOICE_COMMAND";
    static constexpr auto ACTION_WALLPAPER_CHANGED = u8"android.intent.action.WALLPAPER_CHANGED";
    static constexpr auto ACTION_WEB_SEARCH = u8"android.intent.action.WEB_SEARCH";
    static constexpr jint CAPTURE_CONTENT_FOR_NOTE_BLOCKED_BY_ADMIN = 4;
    static constexpr jint CAPTURE_CONTENT_FOR_NOTE_FAILED = 1;
    static constexpr jint CAPTURE_CONTENT_FOR_NOTE_SUCCESS = 0;
    static constexpr jint CAPTURE_CONTENT_FOR_NOTE_USER_CANCELED = 2;
    static constexpr jint CAPTURE_CONTENT_FOR_NOTE_WINDOW_MODE_UNSUPPORTED = 3;
    static constexpr auto CATEGORY_ACCESSIBILITY_SHORTCUT_TARGET = u8"android.intent.category.ACCESSIBILITY_SHORTCUT_TARGET";
    static constexpr auto CATEGORY_ALTERNATIVE = u8"android.intent.category.ALTERNATIVE";
    static constexpr auto CATEGORY_APP_BROWSER = u8"android.intent.category.APP_BROWSER";
    static constexpr auto CATEGORY_APP_CALCULATOR = u8"android.intent.category.APP_CALCULATOR";
    static constexpr auto CATEGORY_APP_CALENDAR = u8"android.intent.category.APP_CALENDAR";
    static constexpr auto CATEGORY_APP_CONTACTS = u8"android.intent.category.APP_CONTACTS";
    static constexpr auto CATEGORY_APP_EMAIL = u8"android.intent.category.APP_EMAIL";
    static constexpr auto CATEGORY_APP_FILES = u8"android.intent.category.APP_FILES";
    static constexpr auto CATEGORY_APP_FITNESS = u8"android.intent.category.APP_FITNESS";
    static constexpr auto CATEGORY_APP_GALLERY = u8"android.intent.category.APP_GALLERY";
    static constexpr auto CATEGORY_APP_MAPS = u8"android.intent.category.APP_MAPS";
    static constexpr auto CATEGORY_APP_MARKET = u8"android.intent.category.APP_MARKET";
    static constexpr auto CATEGORY_APP_MESSAGING = u8"android.intent.category.APP_MESSAGING";
    static constexpr auto CATEGORY_APP_MUSIC = u8"android.intent.category.APP_MUSIC";
    static constexpr auto CATEGORY_APP_WEATHER = u8"android.intent.category.APP_WEATHER";
    static constexpr auto CATEGORY_BROWSABLE = u8"android.intent.category.BROWSABLE";
    static constexpr auto CATEGORY_CAR_DOCK = u8"android.intent.category.CAR_DOCK";
    static constexpr auto CATEGORY_CAR_MODE = u8"android.intent.category.CAR_MODE";
    static constexpr auto CATEGORY_DEFAULT = u8"android.intent.category.DEFAULT";
    static constexpr auto CATEGORY_DESK_DOCK = u8"android.intent.category.DESK_DOCK";
    static constexpr auto CATEGORY_DEVELOPMENT_PREFERENCE = u8"android.intent.category.DEVELOPMENT_PREFERENCE";
    static constexpr auto CATEGORY_EMBED = u8"android.intent.category.EMBED";
    static constexpr auto CATEGORY_FRAMEWORK_INSTRUMENTATION_TEST = u8"android.intent.category.FRAMEWORK_INSTRUMENTATION_TEST";
    static constexpr auto CATEGORY_HE_DESK_DOCK = u8"android.intent.category.HE_DESK_DOCK";
    static constexpr auto CATEGORY_HOME = u8"android.intent.category.HOME";
    static constexpr auto CATEGORY_INFO = u8"android.intent.category.INFO";
    static constexpr auto CATEGORY_LAUNCHER = u8"android.intent.category.LAUNCHER";
    static constexpr auto CATEGORY_LEANBACK_LAUNCHER = u8"android.intent.category.LEANBACK_LAUNCHER";
    static constexpr auto CATEGORY_LE_DESK_DOCK = u8"android.intent.category.LE_DESK_DOCK";
    static constexpr auto CATEGORY_MONKEY = u8"android.intent.category.MONKEY";
    static constexpr auto CATEGORY_OPENABLE = u8"android.intent.category.OPENABLE";
    static constexpr auto CATEGORY_PREFERENCE = u8"android.intent.category.PREFERENCE";
    static constexpr auto CATEGORY_SAMPLE_CODE = u8"android.intent.category.SAMPLE_CODE";
    static constexpr auto CATEGORY_SECONDARY_HOME = u8"android.intent.category.SECONDARY_HOME";
    static constexpr auto CATEGORY_SELECTED_ALTERNATIVE = u8"android.intent.category.SELECTED_ALTERNATIVE";
    static constexpr auto CATEGORY_TAB = u8"android.intent.category.TAB";
    static constexpr auto CATEGORY_TEST = u8"android.intent.category.TEST";
    static constexpr auto CATEGORY_TYPED_OPENABLE = u8"android.intent.category.TYPED_OPENABLE";
    static constexpr auto CATEGORY_UNIT_TEST = u8"android.intent.category.UNIT_TEST";
    static constexpr auto CATEGORY_VOICE = u8"android.intent.category.VOICE";
    static constexpr auto CATEGORY_VR_HOME = u8"android.intent.category.VR_HOME";
    static constexpr jint CHOOSER_CONTENT_TYPE_ALBUM = 1;
    static constexpr auto EXTRA_ALARM_COUNT = u8"android.intent.extra.ALARM_COUNT";
    static constexpr auto EXTRA_ALLOW_MULTIPLE = u8"android.intent.extra.ALLOW_MULTIPLE";
    static constexpr auto EXTRA_ALLOW_REPLACE = u8"android.intent.extra.ALLOW_REPLACE";
    static constexpr auto EXTRA_ALTERNATE_INTENTS = u8"android.intent.extra.ALTERNATE_INTENTS";
    static constexpr auto EXTRA_ARCHIVAL = u8"android.intent.extra.ARCHIVAL";
    static constexpr auto EXTRA_ASSIST_CONTEXT = u8"android.intent.extra.ASSIST_CONTEXT";
    static constexpr auto EXTRA_ASSIST_INPUT_DEVICE_ID = u8"android.intent.extra.ASSIST_INPUT_DEVICE_ID";
    static constexpr auto EXTRA_ASSIST_INPUT_HINT_KEYBOARD = u8"android.intent.extra.ASSIST_INPUT_HINT_KEYBOARD";
    static constexpr auto EXTRA_ASSIST_PACKAGE = u8"android.intent.extra.ASSIST_PACKAGE";
    static constexpr auto EXTRA_ASSIST_UID = u8"android.intent.extra.ASSIST_UID";
    static constexpr auto EXTRA_ATTRIBUTION_TAGS = u8"android.intent.extra.ATTRIBUTION_TAGS";
    static constexpr auto EXTRA_AUTO_LAUNCH_SINGLE_CHOICE = u8"android.intent.extra.AUTO_LAUNCH_SINGLE_CHOICE";
    static constexpr auto EXTRA_BCC = u8"android.intent.extra.BCC";
    static constexpr auto EXTRA_BUG_REPORT = u8"android.intent.extra.BUG_REPORT";
    static constexpr auto EXTRA_CAPTURE_CONTENT_FOR_NOTE_STATUS_CODE = u8"android.intent.extra.CAPTURE_CONTENT_FOR_NOTE_STATUS_CODE";
    static constexpr auto EXTRA_CC = u8"android.intent.extra.CC";
    static constexpr auto EXTRA_CHANGED_COMPONENT_NAME = u8"android.intent.extra.changed_component_name";
    static constexpr auto EXTRA_CHANGED_COMPONENT_NAME_LIST = u8"android.intent.extra.changed_component_name_list";
    static constexpr auto EXTRA_CHANGED_PACKAGE_LIST = u8"android.intent.extra.changed_package_list";
    static constexpr auto EXTRA_CHANGED_UID_LIST = u8"android.intent.extra.changed_uid_list";
    static constexpr auto EXTRA_CHOOSER_ADDITIONAL_CONTENT_URI = u8"android.intent.extra.CHOOSER_ADDITIONAL_CONTENT_URI";
    static constexpr auto EXTRA_CHOOSER_CONTENT_TYPE_HINT = u8"android.intent.extra.CHOOSER_CONTENT_TYPE_HINT";
    static constexpr auto EXTRA_CHOOSER_CUSTOM_ACTIONS = u8"android.intent.extra.CHOOSER_CUSTOM_ACTIONS";
    static constexpr auto EXTRA_CHOOSER_FOCUSED_ITEM_POSITION = u8"android.intent.extra.CHOOSER_FOCUSED_ITEM_POSITION";
    static constexpr auto EXTRA_CHOOSER_MODIFY_SHARE_ACTION = u8"android.intent.extra.CHOOSER_MODIFY_SHARE_ACTION";
    static constexpr auto EXTRA_CHOOSER_REFINEMENT_INTENT_SENDER = u8"android.intent.extra.CHOOSER_REFINEMENT_INTENT_SENDER";
    static constexpr auto EXTRA_CHOOSER_RESULT = u8"android.intent.extra.CHOOSER_RESULT";
    static constexpr auto EXTRA_CHOOSER_RESULT_INTENT_SENDER = u8"android.intent.extra.CHOOSER_RESULT_INTENT_SENDER";
    static constexpr auto EXTRA_CHOOSER_TARGETS = u8"android.intent.extra.CHOOSER_TARGETS";
    static constexpr auto EXTRA_CHOSEN_COMPONENT = u8"android.intent.extra.CHOSEN_COMPONENT";
    static constexpr auto EXTRA_CHOSEN_COMPONENT_INTENT_SENDER = u8"android.intent.extra.CHOSEN_COMPONENT_INTENT_SENDER";
    static constexpr auto EXTRA_COMPONENT_NAME = u8"android.intent.extra.COMPONENT_NAME";
    static constexpr auto EXTRA_CONTENT_ANNOTATIONS = u8"android.intent.extra.CONTENT_ANNOTATIONS";
    static constexpr auto EXTRA_CONTENT_QUERY = u8"android.intent.extra.CONTENT_QUERY";
    static constexpr auto EXTRA_DATA_REMOVED = u8"android.intent.extra.DATA_REMOVED";
    static constexpr auto EXTRA_DOCK_STATE = u8"android.intent.extra.DOCK_STATE";
    static constexpr jint EXTRA_DOCK_STATE_CAR = 2;
    static constexpr jint EXTRA_DOCK_STATE_DESK = 1;
    static constexpr jint EXTRA_DOCK_STATE_HE_DESK = 4;
    static constexpr jint EXTRA_DOCK_STATE_LE_DESK = 3;
    static constexpr jint EXTRA_DOCK_STATE_UNDOCKED = 0;
    static constexpr auto EXTRA_DONT_KILL_APP = u8"android.intent.extra.DONT_KILL_APP";
    static constexpr auto EXTRA_DURATION_MILLIS = u8"android.intent.extra.DURATION_MILLIS";
    static constexpr auto EXTRA_EMAIL = u8"android.intent.extra.EMAIL";
    static constexpr auto EXTRA_END_TIME = u8"android.intent.extra.END_TIME";
    static constexpr auto EXTRA_EXCLUDE_COMPONENTS = u8"android.intent.extra.EXCLUDE_COMPONENTS";
    static constexpr auto EXTRA_FROM_STORAGE = u8"android.intent.extra.FROM_STORAGE";
    static constexpr auto EXTRA_HTML_TEXT = u8"android.intent.extra.HTML_TEXT";
    static constexpr auto EXTRA_INDEX = u8"android.intent.extra.INDEX";
    static constexpr auto EXTRA_INITIAL_INTENTS = u8"android.intent.extra.INITIAL_INTENTS";
    static constexpr auto EXTRA_INSTALLER_PACKAGE_NAME = u8"android.intent.extra.INSTALLER_PACKAGE_NAME";
    static constexpr auto EXTRA_INTENT = u8"android.intent.extra.INTENT";
    static constexpr auto EXTRA_KEY_EVENT = u8"android.intent.extra.KEY_EVENT";
    static constexpr auto EXTRA_LOCALE_LIST = u8"android.intent.extra.LOCALE_LIST";
    static constexpr auto EXTRA_LOCAL_ONLY = u8"android.intent.extra.LOCAL_ONLY";
    static constexpr auto EXTRA_LOCUS_ID = u8"android.intent.extra.LOCUS_ID";
    static constexpr auto EXTRA_METADATA_TEXT = u8"android.intent.extra.METADATA_TEXT";
    static constexpr auto EXTRA_MIME_TYPES = u8"android.intent.extra.MIME_TYPES";
    static constexpr auto EXTRA_NOT_UNKNOWN_SOURCE = u8"android.intent.extra.NOT_UNKNOWN_SOURCE";
    static constexpr auto EXTRA_ORIGINATING_URI = u8"android.intent.extra.ORIGINATING_URI";
    static constexpr auto EXTRA_PACKAGES = u8"android.intent.extra.PACKAGES";
    static constexpr auto EXTRA_PACKAGE_NAME = u8"android.intent.extra.PACKAGE_NAME";
    static constexpr auto EXTRA_PERMISSION_GROUP_NAME = u8"android.intent.extra.PERMISSION_GROUP_NAME";
    static constexpr auto EXTRA_PHONE_NUMBER = u8"android.intent.extra.PHONE_NUMBER";
    static constexpr auto EXTRA_PROCESS_TEXT = u8"android.intent.extra.PROCESS_TEXT";
    static constexpr auto EXTRA_PROCESS_TEXT_READONLY = u8"android.intent.extra.PROCESS_TEXT_READONLY";
    static constexpr auto EXTRA_QUICK_VIEW_FEATURES = u8"android.intent.extra.QUICK_VIEW_FEATURES";
    static constexpr auto EXTRA_QUIET_MODE = u8"android.intent.extra.QUIET_MODE";
    static constexpr auto EXTRA_REFERRER = u8"android.intent.extra.REFERRER";
    static constexpr auto EXTRA_REFERRER_NAME = u8"android.intent.extra.REFERRER_NAME";
    static constexpr auto EXTRA_REMOTE_INTENT_TOKEN = u8"android.intent.extra.remote_intent_token";
    static constexpr auto EXTRA_REPLACEMENT_EXTRAS = u8"android.intent.extra.REPLACEMENT_EXTRAS";
    static constexpr auto EXTRA_REPLACING = u8"android.intent.extra.REPLACING";
    static constexpr auto EXTRA_RESTRICTIONS_BUNDLE = u8"android.intent.extra.restrictions_bundle";
    static constexpr auto EXTRA_RESTRICTIONS_INTENT = u8"android.intent.extra.restrictions_intent";
    static constexpr auto EXTRA_RESTRICTIONS_LIST = u8"android.intent.extra.restrictions_list";
    static constexpr auto EXTRA_RESULT_RECEIVER = u8"android.intent.extra.RESULT_RECEIVER";
    static constexpr auto EXTRA_RETURN_RESULT = u8"android.intent.extra.RETURN_RESULT";
    static constexpr auto EXTRA_SHORTCUT_ICON = u8"android.intent.extra.shortcut.ICON";
    static constexpr auto EXTRA_SHORTCUT_ICON_RESOURCE = u8"android.intent.extra.shortcut.ICON_RESOURCE";
    static constexpr auto EXTRA_SHORTCUT_ID = u8"android.intent.extra.shortcut.ID";
    static constexpr auto EXTRA_SHORTCUT_INTENT = u8"android.intent.extra.shortcut.INTENT";
    static constexpr auto EXTRA_SHORTCUT_NAME = u8"android.intent.extra.shortcut.NAME";
    static constexpr auto EXTRA_SHUTDOWN_USERSPACE_ONLY = u8"android.intent.extra.SHUTDOWN_USERSPACE_ONLY";
    static constexpr auto EXTRA_SPLIT_NAME = u8"android.intent.extra.SPLIT_NAME";
    static constexpr auto EXTRA_START_TIME = u8"android.intent.extra.START_TIME";
    static constexpr auto EXTRA_STREAM = u8"android.intent.extra.STREAM";
    static constexpr auto EXTRA_SUBJECT = u8"android.intent.extra.SUBJECT";
    static constexpr auto EXTRA_SUSPENDED_PACKAGE_EXTRAS = u8"android.intent.extra.SUSPENDED_PACKAGE_EXTRAS";
    static constexpr auto EXTRA_TEMPLATE = u8"android.intent.extra.TEMPLATE";
    static constexpr auto EXTRA_TEXT = u8"android.intent.extra.TEXT";
    static constexpr auto EXTRA_TIME = u8"android.intent.extra.TIME";
    static constexpr auto EXTRA_TIMEZONE = u8"time-zone";
    static constexpr auto EXTRA_TITLE = u8"android.intent.extra.TITLE";
    static constexpr auto EXTRA_UID = u8"android.intent.extra.UID";
    static constexpr auto EXTRA_USER = u8"android.intent.extra.USER";
    static constexpr auto EXTRA_USER_INITIATED = u8"android.intent.extra.USER_INITIATED";
    static constexpr auto EXTRA_USE_STYLUS_MODE = u8"android.intent.extra.USE_STYLUS_MODE";
    static constexpr jint FILL_IN_ACTION = 1;
    static constexpr jint FILL_IN_CATEGORIES = 4;
    static constexpr jint FILL_IN_CLIP_DATA = 128;
    static constexpr jint FILL_IN_COMPONENT = 8;
    static constexpr jint FILL_IN_DATA = 2;
    static constexpr jint FILL_IN_IDENTIFIER = 256;
    static constexpr jint FILL_IN_PACKAGE = 16;
    static constexpr jint FILL_IN_SELECTOR = 64;
    static constexpr jint FILL_IN_SOURCE_BOUNDS = 32;
    static constexpr jint FLAG_ACTIVITY_BROUGHT_TO_FRONT = 4194304;
    static constexpr jint FLAG_ACTIVITY_CLEAR_TASK = 32768;
    static constexpr jint FLAG_ACTIVITY_CLEAR_TOP = 67108864;
    static constexpr jint FLAG_ACTIVITY_CLEAR_WHEN_TASK_RESET = 524288;
    static constexpr jint FLAG_ACTIVITY_EXCLUDE_FROM_RECENTS = 8388608;
    static constexpr jint FLAG_ACTIVITY_FORWARD_RESULT = 33554432;
    static constexpr jint FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY = 1048576;
    static constexpr jint FLAG_ACTIVITY_LAUNCH_ADJACENT = 4096;
    static constexpr jint FLAG_ACTIVITY_MATCH_EXTERNAL = 2048;
    static constexpr jint FLAG_ACTIVITY_MULTIPLE_TASK = 134217728;
    static constexpr jint FLAG_ACTIVITY_NEW_DOCUMENT = 524288;
    static constexpr jint FLAG_ACTIVITY_NEW_TASK = 268435456;
    static constexpr jint FLAG_ACTIVITY_NO_ANIMATION = 65536;
    static constexpr jint FLAG_ACTIVITY_NO_HISTORY = 1073741824;
    static constexpr jint FLAG_ACTIVITY_NO_USER_ACTION = 262144;
    static constexpr jint FLAG_ACTIVITY_PREVIOUS_IS_TOP = 16777216;
    static constexpr jint FLAG_ACTIVITY_REORDER_TO_FRONT = 131072;
    static constexpr jint FLAG_ACTIVITY_REQUIRE_DEFAULT = 512;
    static constexpr jint FLAG_ACTIVITY_REQUIRE_NON_BROWSER = 1024;
    static constexpr jint FLAG_ACTIVITY_RESET_TASK_IF_NEEDED = 2097152;
    static constexpr jint FLAG_ACTIVITY_RETAIN_IN_RECENTS = 8192;
    static constexpr jint FLAG_ACTIVITY_SINGLE_TOP = 536870912;
    static constexpr jint FLAG_ACTIVITY_TASK_ON_HOME = 16384;
    static constexpr jint FLAG_DEBUG_LOG_RESOLUTION = 8;
    static constexpr jint FLAG_DIRECT_BOOT_AUTO = 256;
    static constexpr jint FLAG_EXCLUDE_STOPPED_PACKAGES = 16;
    static constexpr jint FLAG_FROM_BACKGROUND = 4;
    static constexpr jint FLAG_GRANT_PERSISTABLE_URI_PERMISSION = 64;
    static constexpr jint FLAG_GRANT_PREFIX_URI_PERMISSION = 128;
    static constexpr jint FLAG_GRANT_READ_URI_PERMISSION = 1;
    static constexpr jint FLAG_GRANT_WRITE_URI_PERMISSION = 2;
    static constexpr jint FLAG_INCLUDE_STOPPED_PACKAGES = 32;
    static constexpr jint FLAG_RECEIVER_FOREGROUND = 268435456;
    static constexpr jint FLAG_RECEIVER_NO_ABORT = 134217728;
    static constexpr jint FLAG_RECEIVER_REGISTERED_ONLY = 1073741824;
    static constexpr jint FLAG_RECEIVER_REPLACE_PENDING = 536870912;
    static constexpr jint FLAG_RECEIVER_VISIBLE_TO_INSTANT_APPS = 2097152;
    static constexpr auto METADATA_DOCK_HOME = u8"android.dock_home";
    static constexpr jint URI_ALLOW_UNSAFE = 4;
    static constexpr jint URI_ANDROID_APP_SCHEME = 2;
    static constexpr jint URI_INTENT_SCHEME = 1;


    // construct: public Intent()
    static IntentProxy newInstance() {
        IntentProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "()V");
        return ret;
    }

    // construct: public Intent(android.content.Intent o)
    static IntentProxy newInstance(jobject o) {
        IntentProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Landroid/content/Intent;)V", o);
        return ret;
    }

    // construct: public Intent(java.lang.String action)
    static IntentProxy newInstance(jstring action) {
        IntentProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Ljava/lang/String;)V", action);
        return ret;
    }

    // construct: public Intent(java.lang.String action, android.net.Uri uri)
    static IntentProxy newInstance(jstring action, jobject uri) {
        IntentProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Ljava/lang/String;Landroid/net/Uri;)V", action, uri);
        return ret;
    }

    // construct: public Intent(android.content.Context packageContext, java.lang.Class<?> cls)
    static IntentProxy newInstance(jobject packageContext, jclass cls) {
        IntentProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Landroid/content/Context;Ljava/lang/Class;)V", packageContext, cls);
        return ret;
    }

    // construct: public Intent(java.lang.String action, android.net.Uri uri, android.content.Context packageContext, java.lang.Class<?> cls)
    static IntentProxy newInstance(jstring action, jobject uri, jobject packageContext, jclass cls) {
        IntentProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Ljava/lang/String;Landroid/net/Uri;Landroid/content/Context;Ljava/lang/Class;)V", action, uri, packageContext, cls);
        return ret;
    }

    // method: public static android.content.Intent createChooser(android.content.Intent target, java.lang.CharSequence title)
    static auto createChooser(jobject target, jobject title) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "createChooser",
                        "(Landroid/content/Intent;Ljava/lang/CharSequence;)Landroid/content/Intent;", target, title);
    }


    // method: public static android.content.Intent createChooser(android.content.Intent target, java.lang.CharSequence title, android.content.IntentSender sender)
    static auto createChooser(jobject target, jobject title, jobject sender) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "createChooser",
                        "(Landroid/content/Intent;Ljava/lang/CharSequence;Landroid/content/IntentSender;)Landroid/content/Intent;", target, title, sender);
    }


    // method: public java.lang.Object clone()
    auto clone() const {
        return m_jniObject.callMethod<jobject>(
                        "clone",
                        "()Ljava/lang/Object;");
    }


    // method: public android.content.Intent cloneFilter()
    auto cloneFilter() const {
        return m_jniObject.callMethod<jobject>(
                        "cloneFilter",
                        "()Landroid/content/Intent;");
    }


    // method: public static android.content.Intent makeMainActivity(android.content.ComponentName mainActivity)
    static auto makeMainActivity(jobject mainActivity) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "makeMainActivity",
                        "(Landroid/content/ComponentName;)Landroid/content/Intent;", mainActivity);
    }


    // method: public static android.content.Intent makeMainSelectorActivity(java.lang.String selectorAction, java.lang.String selectorCategory)
    static auto makeMainSelectorActivity(jstring selectorAction, jstring selectorCategory) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "makeMainSelectorActivity",
                        "(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;", selectorAction, selectorCategory);
    }


    // method: public static android.content.Intent makeRestartActivityTask(android.content.ComponentName mainActivity)
    static auto makeRestartActivityTask(jobject mainActivity) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "makeRestartActivityTask",
                        "(Landroid/content/ComponentName;)Landroid/content/Intent;", mainActivity);
    }


    // method: public static android.content.Intent getIntent(java.lang.String uri)
    static auto getIntent(jstring uri) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "getIntent",
                        "(Ljava/lang/String;)Landroid/content/Intent;", uri);
    }


    // method: public static android.content.Intent parseUri(java.lang.String uri, int flags)
    static auto parseUri(jstring uri, jint flags) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "parseUri",
                        "(Ljava/lang/String;I)Landroid/content/Intent;", uri, flags);
    }


    // method: public static android.content.Intent getIntentOld(java.lang.String uri)
    static auto getIntentOld(jstring uri) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "getIntentOld",
                        "(Ljava/lang/String;)Landroid/content/Intent;", uri);
    }


    // method: public java.lang.String getAction()
    auto getAction() const {
        return m_jniObject.callMethod<jstring>(
                        "getAction",
                        "()Ljava/lang/String;");
    }


    // method: public android.net.Uri getData()
    auto getData() const {
        return m_jniObject.callMethod<jobject>(
                        "getData",
                        "()Landroid/net/Uri;");
    }


    // method: public java.lang.String getDataString()
    auto getDataString() const {
        return m_jniObject.callMethod<jstring>(
                        "getDataString",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String getScheme()
    auto getScheme() const {
        return m_jniObject.callMethod<jstring>(
                        "getScheme",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String getType()
    auto getType() const {
        return m_jniObject.callMethod<jstring>(
                        "getType",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String resolveType(android.content.Context context)
    auto resolveType__Landroid_content_Context_2(jobject context) const {
        return m_jniObject.callMethod<jstring>(
                        "resolveType",
                        "(Landroid/content/Context;)Ljava/lang/String;", context);
    }


    // method: public java.lang.String resolveType(android.content.ContentResolver resolver)
    auto resolveType__Landroid_content_ContentResolver_2(jobject resolver) const {
        return m_jniObject.callMethod<jstring>(
                        "resolveType",
                        "(Landroid/content/ContentResolver;)Ljava/lang/String;", resolver);
    }


    // method: public java.lang.String resolveTypeIfNeeded(android.content.ContentResolver resolver)
    auto resolveTypeIfNeeded(jobject resolver) const {
        return m_jniObject.callMethod<jstring>(
                        "resolveTypeIfNeeded",
                        "(Landroid/content/ContentResolver;)Ljava/lang/String;", resolver);
    }


    // method: public java.lang.String getIdentifier()
    auto getIdentifier() const {
        return m_jniObject.callMethod<jstring>(
                        "getIdentifier",
                        "()Ljava/lang/String;");
    }


    // method: public boolean hasCategory(java.lang.String category)
    auto hasCategory(jstring category) const {
        return m_jniObject.callMethod<jboolean>(
                        "hasCategory",
                        "(Ljava/lang/String;)Z", category);
    }


    // method: public java.util.Set<java.lang.String> getCategories()
    auto getCategories() const {
        return m_jniObject.callMethod<jobject>(
                        "getCategories",
                        "()Ljava/util/Set;");
    }


    // method: public android.content.Intent getSelector()
    auto getSelector() const {
        return m_jniObject.callMethod<jobject>(
                        "getSelector",
                        "()Landroid/content/Intent;");
    }


    // method: public android.content.ClipData getClipData()
    auto getClipData() const {
        return m_jniObject.callMethod<jobject>(
                        "getClipData",
                        "()Landroid/content/ClipData;");
    }


    // method: public void setExtrasClassLoader(java.lang.ClassLoader loader)
    auto setExtrasClassLoader(jobject loader) const {
        m_jniObject.callMethod<void>(
                        "setExtrasClassLoader",
                        "(Ljava/lang/ClassLoader;)V", loader);
    }


    // method: public boolean hasExtra(java.lang.String name)
    auto hasExtra(jstring name) const {
        return m_jniObject.callMethod<jboolean>(
                        "hasExtra",
                        "(Ljava/lang/String;)Z", name);
    }


    // method: public boolean hasFileDescriptors()
    auto hasFileDescriptors() const {
        return m_jniObject.callMethod<jboolean>(
                        "hasFileDescriptors",
                        "()Z");
    }


    // method: public boolean getBooleanExtra(java.lang.String name, boolean defaultValue)
    auto getBooleanExtra(jstring name, jboolean defaultValue) const {
        return m_jniObject.callMethod<jboolean>(
                        "getBooleanExtra",
                        "(Ljava/lang/String;Z)Z", name, defaultValue);
    }


    // method: public byte getByteExtra(java.lang.String name, byte defaultValue)
    auto getByteExtra(jstring name, jbyte defaultValue) const {
        return m_jniObject.callMethod<jbyte>(
                        "getByteExtra",
                        "(Ljava/lang/String;B)B", name, defaultValue);
    }


    // method: public short getShortExtra(java.lang.String name, short defaultValue)
    auto getShortExtra(jstring name, jshort defaultValue) const {
        return m_jniObject.callMethod<jshort>(
                        "getShortExtra",
                        "(Ljava/lang/String;S)S", name, defaultValue);
    }


    // method: public char getCharExtra(java.lang.String name, char defaultValue)
    auto getCharExtra(jstring name, jchar defaultValue) const {
        return m_jniObject.callMethod<jchar>(
                        "getCharExtra",
                        "(Ljava/lang/String;C)C", name, defaultValue);
    }


    // method: public int getIntExtra(java.lang.String name, int defaultValue)
    auto getIntExtra(jstring name, jint defaultValue) const {
        return m_jniObject.callMethod<jint>(
                        "getIntExtra",
                        "(Ljava/lang/String;I)I", name, defaultValue);
    }


    // method: public long getLongExtra(java.lang.String name, long defaultValue)
    auto getLongExtra(jstring name, jlong defaultValue) const {
        return m_jniObject.callMethod<jlong>(
                        "getLongExtra",
                        "(Ljava/lang/String;J)J", name, defaultValue);
    }


    // method: public float getFloatExtra(java.lang.String name, float defaultValue)
    auto getFloatExtra(jstring name, jfloat defaultValue) const {
        return m_jniObject.callMethod<jfloat>(
                        "getFloatExtra",
                        "(Ljava/lang/String;F)F", name, defaultValue);
    }


    // method: public double getDoubleExtra(java.lang.String name, double defaultValue)
    auto getDoubleExtra(jstring name, jdouble defaultValue) const {
        return m_jniObject.callMethod<jdouble>(
                        "getDoubleExtra",
                        "(Ljava/lang/String;D)D", name, defaultValue);
    }


    // method: public java.lang.String getStringExtra(java.lang.String name)
    auto getStringExtra(jstring name) const {
        return m_jniObject.callMethod<jstring>(
                        "getStringExtra",
                        "(Ljava/lang/String;)Ljava/lang/String;", name);
    }


    // method: public java.lang.CharSequence getCharSequenceExtra(java.lang.String name)
    auto getCharSequenceExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getCharSequenceExtra",
                        "(Ljava/lang/String;)Ljava/lang/CharSequence;", name);
    }


    // method: public T getParcelableExtra(java.lang.String name)
    auto getParcelableExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getParcelableExtra",
                        "(Ljava/lang/String;)Landroid/os/Parcelable;", name);
    }


    // method: public T getParcelableExtra(java.lang.String name, java.lang.Class<T> clazz)
    auto getParcelableExtra(jstring name, jclass clazz) const {
        return m_jniObject.callMethod<jobject>(
                        "getParcelableExtra",
                        "(Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object;", name, clazz);
    }


    // method: public android.os.Parcelable[] getParcelableArrayExtra(java.lang.String name)
    auto getParcelableArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getParcelableArrayExtra",
                        "(Ljava/lang/String;)[Landroid/os/Parcelable;", name);
    }


    // method: public T[] getParcelableArrayExtra(java.lang.String name, java.lang.Class<T> clazz)
    auto getParcelableArrayExtra(jstring name, jclass clazz) const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getParcelableArrayExtra",
                        "(Ljava/lang/String;Ljava/lang/Class;)[Ljava/lang/Object;", name, clazz);
    }


    // method: public java.util.ArrayList<T> getParcelableArrayListExtra(java.lang.String name)
    auto getParcelableArrayListExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getParcelableArrayListExtra",
                        "(Ljava/lang/String;)Ljava/util/ArrayList;", name);
    }


    // method: public java.util.ArrayList<T> getParcelableArrayListExtra(java.lang.String name, java.lang.Class<? extends T> clazz)
    auto getParcelableArrayListExtra(jstring name, jclass clazz) const {
        return m_jniObject.callMethod<jobject>(
                        "getParcelableArrayListExtra",
                        "(Ljava/lang/String;Ljava/lang/Class;)Ljava/util/ArrayList;", name, clazz);
    }


    // method: public java.io.Serializable getSerializableExtra(java.lang.String name)
    auto getSerializableExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getSerializableExtra",
                        "(Ljava/lang/String;)Ljava/io/Serializable;", name);
    }


    // method: public T getSerializableExtra(java.lang.String name, java.lang.Class<T> clazz)
    auto getSerializableExtra(jstring name, jclass clazz) const {
        return m_jniObject.callMethod<jobject>(
                        "getSerializableExtra",
                        "(Ljava/lang/String;Ljava/lang/Class;)Ljava/io/Serializable;", name, clazz);
    }


    // method: public java.util.ArrayList<java.lang.Integer> getIntegerArrayListExtra(java.lang.String name)
    auto getIntegerArrayListExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getIntegerArrayListExtra",
                        "(Ljava/lang/String;)Ljava/util/ArrayList;", name);
    }


    // method: public java.util.ArrayList<java.lang.String> getStringArrayListExtra(java.lang.String name)
    auto getStringArrayListExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getStringArrayListExtra",
                        "(Ljava/lang/String;)Ljava/util/ArrayList;", name);
    }


    // method: public java.util.ArrayList<java.lang.CharSequence> getCharSequenceArrayListExtra(java.lang.String name)
    auto getCharSequenceArrayListExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getCharSequenceArrayListExtra",
                        "(Ljava/lang/String;)Ljava/util/ArrayList;", name);
    }


    // method: public boolean[] getBooleanArrayExtra(java.lang.String name)
    auto getBooleanArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jbooleanArray>(
                        "getBooleanArrayExtra",
                        "(Ljava/lang/String;)[Z", name);
    }


    // method: public byte[] getByteArrayExtra(java.lang.String name)
    auto getByteArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jbyteArray>(
                        "getByteArrayExtra",
                        "(Ljava/lang/String;)[B", name);
    }


    // method: public short[] getShortArrayExtra(java.lang.String name)
    auto getShortArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jshortArray>(
                        "getShortArrayExtra",
                        "(Ljava/lang/String;)[S", name);
    }


    // method: public char[] getCharArrayExtra(java.lang.String name)
    auto getCharArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jcharArray>(
                        "getCharArrayExtra",
                        "(Ljava/lang/String;)[C", name);
    }


    // method: public int[] getIntArrayExtra(java.lang.String name)
    auto getIntArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jintArray>(
                        "getIntArrayExtra",
                        "(Ljava/lang/String;)[I", name);
    }


    // method: public long[] getLongArrayExtra(java.lang.String name)
    auto getLongArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jlongArray>(
                        "getLongArrayExtra",
                        "(Ljava/lang/String;)[J", name);
    }


    // method: public float[] getFloatArrayExtra(java.lang.String name)
    auto getFloatArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jfloatArray>(
                        "getFloatArrayExtra",
                        "(Ljava/lang/String;)[F", name);
    }


    // method: public double[] getDoubleArrayExtra(java.lang.String name)
    auto getDoubleArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jdoubleArray>(
                        "getDoubleArrayExtra",
                        "(Ljava/lang/String;)[D", name);
    }


    // method: public java.lang.String[] getStringArrayExtra(java.lang.String name)
    auto getStringArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getStringArrayExtra",
                        "(Ljava/lang/String;)[Ljava/lang/String;", name);
    }


    // method: public java.lang.CharSequence[] getCharSequenceArrayExtra(java.lang.String name)
    auto getCharSequenceArrayExtra(jstring name) const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getCharSequenceArrayExtra",
                        "(Ljava/lang/String;)[Ljava/lang/CharSequence;", name);
    }


    // method: public android.os.Bundle getBundleExtra(java.lang.String name)
    auto getBundleExtra(jstring name) const {
        return m_jniObject.callMethod<jobject>(
                        "getBundleExtra",
                        "(Ljava/lang/String;)Landroid/os/Bundle;", name);
    }


    // method: public android.os.Bundle getExtras()
    auto getExtras() const {
        return m_jniObject.callMethod<jobject>(
                        "getExtras",
                        "()Landroid/os/Bundle;");
    }


    // method: public int getFlags()
    auto getFlags() const {
        return m_jniObject.callMethod<jint>(
                        "getFlags",
                        "()I");
    }


    // method: public java.lang.String getPackage()
    auto getPackage() const {
        return m_jniObject.callMethod<jstring>(
                        "getPackage",
                        "()Ljava/lang/String;");
    }


    // method: public android.content.ComponentName getComponent()
    auto getComponent() const {
        return m_jniObject.callMethod<jobject>(
                        "getComponent",
                        "()Landroid/content/ComponentName;");
    }


    // method: public android.graphics.Rect getSourceBounds()
    auto getSourceBounds() const {
        return m_jniObject.callMethod<jobject>(
                        "getSourceBounds",
                        "()Landroid/graphics/Rect;");
    }


    // method: public android.content.ComponentName resolveActivity(android.content.pm.PackageManager pm)
    auto resolveActivity(jobject pm) const {
        return m_jniObject.callMethod<jobject>(
                        "resolveActivity",
                        "(Landroid/content/pm/PackageManager;)Landroid/content/ComponentName;", pm);
    }


    // method: public android.content.pm.ActivityInfo resolveActivityInfo(android.content.pm.PackageManager pm, int flags)
    auto resolveActivityInfo(jobject pm, jint flags) const {
        return m_jniObject.callMethod<jobject>(
                        "resolveActivityInfo",
                        "(Landroid/content/pm/PackageManager;I)Landroid/content/pm/ActivityInfo;", pm, flags);
    }


    // method: public android.content.Intent setAction(java.lang.String action)
    auto setAction(jstring action) const {
        return m_jniObject.callMethod<jobject>(
                        "setAction",
                        "(Ljava/lang/String;)Landroid/content/Intent;", action);
    }


    // method: public android.content.Intent setData(android.net.Uri data)
    auto setData(jobject data) const {
        return m_jniObject.callMethod<jobject>(
                        "setData",
                        "(Landroid/net/Uri;)Landroid/content/Intent;", data);
    }


    // method: public android.content.Intent setDataAndNormalize(android.net.Uri data)
    auto setDataAndNormalize(jobject data) const {
        return m_jniObject.callMethod<jobject>(
                        "setDataAndNormalize",
                        "(Landroid/net/Uri;)Landroid/content/Intent;", data);
    }


    // method: public android.content.Intent setType(java.lang.String type)
    auto setType(jstring type) const {
        return m_jniObject.callMethod<jobject>(
                        "setType",
                        "(Ljava/lang/String;)Landroid/content/Intent;", type);
    }


    // method: public android.content.Intent setTypeAndNormalize(java.lang.String type)
    auto setTypeAndNormalize(jstring type) const {
        return m_jniObject.callMethod<jobject>(
                        "setTypeAndNormalize",
                        "(Ljava/lang/String;)Landroid/content/Intent;", type);
    }


    // method: public android.content.Intent setDataAndType(android.net.Uri data, java.lang.String type)
    auto setDataAndType(jobject data, jstring type) const {
        return m_jniObject.callMethod<jobject>(
                        "setDataAndType",
                        "(Landroid/net/Uri;Ljava/lang/String;)Landroid/content/Intent;", data, type);
    }


    // method: public android.content.Intent setDataAndTypeAndNormalize(android.net.Uri data, java.lang.String type)
    auto setDataAndTypeAndNormalize(jobject data, jstring type) const {
        return m_jniObject.callMethod<jobject>(
                        "setDataAndTypeAndNormalize",
                        "(Landroid/net/Uri;Ljava/lang/String;)Landroid/content/Intent;", data, type);
    }


    // method: public android.content.Intent setIdentifier(java.lang.String identifier)
    auto setIdentifier(jstring identifier) const {
        return m_jniObject.callMethod<jobject>(
                        "setIdentifier",
                        "(Ljava/lang/String;)Landroid/content/Intent;", identifier);
    }


    // method: public android.content.Intent addCategory(java.lang.String category)
    auto addCategory(jstring category) const {
        return m_jniObject.callMethod<jobject>(
                        "addCategory",
                        "(Ljava/lang/String;)Landroid/content/Intent;", category);
    }


    // method: public void removeCategory(java.lang.String category)
    auto removeCategory(jstring category) const {
        m_jniObject.callMethod<void>(
                        "removeCategory",
                        "(Ljava/lang/String;)V", category);
    }


    // method: public void setSelector(android.content.Intent selector)
    auto setSelector(jobject selector) const {
        m_jniObject.callMethod<void>(
                        "setSelector",
                        "(Landroid/content/Intent;)V", selector);
    }


    // method: public void setClipData(android.content.ClipData clip)
    auto setClipData(jobject clip) const {
        m_jniObject.callMethod<void>(
                        "setClipData",
                        "(Landroid/content/ClipData;)V", clip);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, boolean value)
    auto putExtra(jstring name, jboolean value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;Z)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, byte value)
    auto putExtra(jstring name, jbyte value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;B)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, char value)
    auto putExtra(jstring name, jchar value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;C)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, short value)
    auto putExtra(jstring name, jshort value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;S)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, int value)
    auto putExtra(jstring name, jint value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;I)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, long value)
    auto putExtra(jstring name, jlong value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;J)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, float value)
    auto putExtra(jstring name, jfloat value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;F)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, double value)
    auto putExtra(jstring name, jdouble value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;D)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, java.lang.String value)
    auto putExtra(jstring name, jstring value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, java.lang.CharSequence value)
    auto putExtra__Ljava_lang_String_2Ljava_lang_CharSequence_2(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;Ljava/lang/CharSequence;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, android.os.Parcelable value)
    auto putExtra__Ljava_lang_String_2Landroid_os_Parcelable_2(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;Landroid/os/Parcelable;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, android.os.Parcelable[] value)
    auto putExtra__Ljava_lang_String_2_0005bLandroid_os_Parcelable_2(jstring name, jobjectArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[Landroid/os/Parcelable;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, java.io.Serializable value)
    auto putExtra__Ljava_lang_String_2Ljava_io_Serializable_2(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;Ljava/io/Serializable;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, boolean[] value)
    auto putExtra(jstring name, jbooleanArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[Z)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, byte[] value)
    auto putExtra(jstring name, jbyteArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[B)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, short[] value)
    auto putExtra(jstring name, jshortArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[S)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, char[] value)
    auto putExtra(jstring name, jcharArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[C)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, int[] value)
    auto putExtra(jstring name, jintArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[I)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, long[] value)
    auto putExtra(jstring name, jlongArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[J)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, float[] value)
    auto putExtra(jstring name, jfloatArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[F)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, double[] value)
    auto putExtra(jstring name, jdoubleArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[D)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, java.lang.String[] value)
    auto putExtra__Ljava_lang_String_2_0005bLjava_lang_String_2(jstring name, jobjectArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[Ljava/lang/String;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, java.lang.CharSequence[] value)
    auto putExtra__Ljava_lang_String_2_0005bLjava_lang_CharSequence_2(jstring name, jobjectArray value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;[Ljava/lang/CharSequence;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtra(java.lang.String name, android.os.Bundle value)
    auto putExtra__Ljava_lang_String_2Landroid_os_Bundle_2(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtra",
                        "(Ljava/lang/String;Landroid/os/Bundle;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putParcelableArrayListExtra(java.lang.String name, java.util.ArrayList<? extends android.os.Parcelable> value)
    auto putParcelableArrayListExtra(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putParcelableArrayListExtra",
                        "(Ljava/lang/String;Ljava/util/ArrayList;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putIntegerArrayListExtra(java.lang.String name, java.util.ArrayList<java.lang.Integer> value)
    auto putIntegerArrayListExtra(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putIntegerArrayListExtra",
                        "(Ljava/lang/String;Ljava/util/ArrayList;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putStringArrayListExtra(java.lang.String name, java.util.ArrayList<java.lang.String> value)
    auto putStringArrayListExtra(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putStringArrayListExtra",
                        "(Ljava/lang/String;Ljava/util/ArrayList;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putCharSequenceArrayListExtra(java.lang.String name, java.util.ArrayList<java.lang.CharSequence> value)
    auto putCharSequenceArrayListExtra(jstring name, jobject value) const {
        return m_jniObject.callMethod<jobject>(
                        "putCharSequenceArrayListExtra",
                        "(Ljava/lang/String;Ljava/util/ArrayList;)Landroid/content/Intent;", name, value);
    }


    // method: public android.content.Intent putExtras(android.content.Intent src)
    auto putExtras__Landroid_content_Intent_2(jobject src) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtras",
                        "(Landroid/content/Intent;)Landroid/content/Intent;", src);
    }


    // method: public android.content.Intent putExtras(android.os.Bundle extras)
    auto putExtras__Landroid_os_Bundle_2(jobject extras) const {
        return m_jniObject.callMethod<jobject>(
                        "putExtras",
                        "(Landroid/os/Bundle;)Landroid/content/Intent;", extras);
    }


    // method: public android.content.Intent replaceExtras(android.content.Intent src)
    auto replaceExtras__Landroid_content_Intent_2(jobject src) const {
        return m_jniObject.callMethod<jobject>(
                        "replaceExtras",
                        "(Landroid/content/Intent;)Landroid/content/Intent;", src);
    }


    // method: public android.content.Intent replaceExtras(android.os.Bundle extras)
    auto replaceExtras__Landroid_os_Bundle_2(jobject extras) const {
        return m_jniObject.callMethod<jobject>(
                        "replaceExtras",
                        "(Landroid/os/Bundle;)Landroid/content/Intent;", extras);
    }


    // method: public void removeExtra(java.lang.String name)
    auto removeExtra(jstring name) const {
        m_jniObject.callMethod<void>(
                        "removeExtra",
                        "(Ljava/lang/String;)V", name);
    }


    // method: public android.content.Intent setFlags(int flags)
    auto setFlags(jint flags) const {
        return m_jniObject.callMethod<jobject>(
                        "setFlags",
                        "(I)Landroid/content/Intent;", flags);
    }


    // method: public android.content.Intent addFlags(int flags)
    auto addFlags(jint flags) const {
        return m_jniObject.callMethod<jobject>(
                        "addFlags",
                        "(I)Landroid/content/Intent;", flags);
    }


    // method: public void removeFlags(int flags)
    auto removeFlags(jint flags) const {
        m_jniObject.callMethod<void>(
                        "removeFlags",
                        "(I)V", flags);
    }


    // method: public android.content.Intent setPackage(java.lang.String packageName)
    auto setPackage(jstring packageName) const {
        return m_jniObject.callMethod<jobject>(
                        "setPackage",
                        "(Ljava/lang/String;)Landroid/content/Intent;", packageName);
    }


    // method: public android.content.Intent setComponent(android.content.ComponentName component)
    auto setComponent(jobject component) const {
        return m_jniObject.callMethod<jobject>(
                        "setComponent",
                        "(Landroid/content/ComponentName;)Landroid/content/Intent;", component);
    }


    // method: public android.content.Intent setClassName(android.content.Context packageContext, java.lang.String className)
    auto setClassName(jobject packageContext, jstring className) const {
        return m_jniObject.callMethod<jobject>(
                        "setClassName",
                        "(Landroid/content/Context;Ljava/lang/String;)Landroid/content/Intent;", packageContext, className);
    }


    // method: public android.content.Intent setClassName(java.lang.String packageName, java.lang.String className)
    auto setClassName(jstring packageName, jstring className) const {
        return m_jniObject.callMethod<jobject>(
                        "setClassName",
                        "(Ljava/lang/String;Ljava/lang/String;)Landroid/content/Intent;", packageName, className);
    }


    // method: public android.content.Intent setClass(android.content.Context packageContext, java.lang.Class<?> cls)
    auto setClass(jobject packageContext, jclass cls) const {
        return m_jniObject.callMethod<jobject>(
                        "setClass",
                        "(Landroid/content/Context;Ljava/lang/Class;)Landroid/content/Intent;", packageContext, cls);
    }


    // method: public void setSourceBounds(android.graphics.Rect r)
    auto setSourceBounds(jobject r) const {
        m_jniObject.callMethod<void>(
                        "setSourceBounds",
                        "(Landroid/graphics/Rect;)V", r);
    }


    // method: public int fillIn(android.content.Intent other, int flags)
    auto fillIn(jobject other, jint flags) const {
        return m_jniObject.callMethod<jint>(
                        "fillIn",
                        "(Landroid/content/Intent;I)I", other, flags);
    }


    // method: public boolean filterEquals(android.content.Intent other)
    auto filterEquals(jobject other) const {
        return m_jniObject.callMethod<jboolean>(
                        "filterEquals",
                        "(Landroid/content/Intent;)Z", other);
    }


    // method: public int filterHashCode()
    auto filterHashCode() const {
        return m_jniObject.callMethod<jint>(
                        "filterHashCode",
                        "()I");
    }


    // method: public java.lang.String toString()
    auto toString() const {
        return m_jniObject.callMethod<jstring>(
                        "toString",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String toURI()
    auto toURI() const {
        return m_jniObject.callMethod<jstring>(
                        "toURI",
                        "()Ljava/lang/String;");
    }


    // method: public java.lang.String toUri(int flags)
    auto toUri(jint flags) const {
        return m_jniObject.callMethod<jstring>(
                        "toUri",
                        "(I)Ljava/lang/String;", flags);
    }


    // method: public int describeContents()
    auto describeContents() const {
        return m_jniObject.callMethod<jint>(
                        "describeContents",
                        "()I");
    }


    // method: public void writeToParcel(android.os.Parcel out, int flags)
    auto writeToParcel(jobject out, jint flags) const {
        m_jniObject.callMethod<void>(
                        "writeToParcel",
                        "(Landroid/os/Parcel;I)V", out, flags);
    }


    // method: public void readFromParcel(android.os.Parcel in)
    auto readFromParcel(jobject in) const {
        m_jniObject.callMethod<void>(
                        "readFromParcel",
                        "(Landroid/os/Parcel;)V", in);
    }


    // method: public static android.content.Intent parseIntent(android.content.res.Resources resources, org.xmlpull.v1.XmlPullParser parser, android.util.AttributeSet attrs)
    static auto parseIntent(jobject resources, jobject parser, jobject attrs) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "parseIntent",
                        "(Landroid/content/res/Resources;Lorg/xmlpull/v1/XmlPullParser;Landroid/util/AttributeSet;)Landroid/content/Intent;", resources, parser, attrs);
    }


    // method: public static java.lang.String normalizeMimeType(java.lang.String type)
    static auto normalizeMimeType(jstring type) {
        return QJniObject::callStaticMethod<jstring>(FULL_CLASS_NAME,
                        "normalizeMimeType",
                        "(Ljava/lang/String;)Ljava/lang/String;", type);
    }


    // method: public boolean isMismatchingFilter()
    auto isMismatchingFilter() const {
        return m_jniObject.callMethod<jboolean>(
                        "isMismatchingFilter",
                        "()Z");
    }


    // field: public static final android.os.Parcelable.Creator<android.content.Intent> CREATOR
    static auto getCREATOR() {
       return QJniObject::getStaticField<jobject>(FULL_CLASS_NAME,"CREATOR");

    }

    // field: public static final android.os.Parcelable.Creator<android.content.Intent> CREATOR
    static void setCREATOR(jobject CREATOR) {
        QJniObject::setStaticField(FULL_CLASS_NAME,"CREATOR", CREATOR);
    }


};
} } // endof namespace android::content


namespace android { namespace content {


} } // endof namespace android::content

#endif // android_content_IntentProxy_H

