
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_media_AudioManagerProxy_H
#define android_media_AudioManagerProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace media {
class AudioManagerProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/media/AudioManager";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    AudioManagerProxy() {}
    AudioManagerProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    AudioManagerProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static AudioManagerProxy fromLocalRef(jobject localRef) {
        AudioManagerProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }

    static constexpr auto ACTION_AUDIO_BECOMING_NOISY = u8"android.media.AUDIO_BECOMING_NOISY";
    static constexpr auto ACTION_HDMI_AUDIO_PLUG = u8"android.media.action.HDMI_AUDIO_PLUG";
    static constexpr auto ACTION_HEADSET_PLUG = u8"android.intent.action.HEADSET_PLUG";
    static constexpr auto ACTION_MICROPHONE_MUTE_CHANGED = u8"android.media.action.MICROPHONE_MUTE_CHANGED";
    static constexpr auto ACTION_SCO_AUDIO_STATE_CHANGED = u8"android.media.SCO_AUDIO_STATE_CHANGED";
    static constexpr auto ACTION_SCO_AUDIO_STATE_UPDATED = u8"android.media.ACTION_SCO_AUDIO_STATE_UPDATED";
    static constexpr auto ACTION_SPEAKERPHONE_STATE_CHANGED = u8"android.media.action.SPEAKERPHONE_STATE_CHANGED";
    static constexpr jint ADJUST_LOWER = -1;
    static constexpr jint ADJUST_MUTE = -100;
    static constexpr jint ADJUST_RAISE = 1;
    static constexpr jint ADJUST_SAME = 0;
    static constexpr jint ADJUST_TOGGLE_MUTE = 101;
    static constexpr jint ADJUST_UNMUTE = 100;
    static constexpr jint AUDIOFOCUS_GAIN = 1;
    static constexpr jint AUDIOFOCUS_GAIN_TRANSIENT = 2;
    static constexpr jint AUDIOFOCUS_GAIN_TRANSIENT_EXCLUSIVE = 4;
    static constexpr jint AUDIOFOCUS_GAIN_TRANSIENT_MAY_DUCK = 3;
    static constexpr jint AUDIOFOCUS_LOSS = -1;
    static constexpr jint AUDIOFOCUS_LOSS_TRANSIENT = -2;
    static constexpr jint AUDIOFOCUS_LOSS_TRANSIENT_CAN_DUCK = -3;
    static constexpr jint AUDIOFOCUS_NONE = 0;
    static constexpr jint AUDIOFOCUS_REQUEST_DELAYED = 2;
    static constexpr jint AUDIOFOCUS_REQUEST_FAILED = 0;
    static constexpr jint AUDIOFOCUS_REQUEST_GRANTED = 1;
    static constexpr jint AUDIO_SESSION_ID_GENERATE = 0;
    static constexpr jint DIRECT_PLAYBACK_BITSTREAM_SUPPORTED = 4;
    static constexpr jint DIRECT_PLAYBACK_NOT_SUPPORTED = 0;
    static constexpr jint DIRECT_PLAYBACK_OFFLOAD_GAPLESS_SUPPORTED = 3;
    static constexpr jint DIRECT_PLAYBACK_OFFLOAD_SUPPORTED = 1;
    static constexpr jint ENCODED_SURROUND_OUTPUT_ALWAYS = 2;
    static constexpr jint ENCODED_SURROUND_OUTPUT_AUTO = 0;
    static constexpr jint ENCODED_SURROUND_OUTPUT_MANUAL = 3;
    static constexpr jint ENCODED_SURROUND_OUTPUT_NEVER = 1;
    static constexpr jint ENCODED_SURROUND_OUTPUT_UNKNOWN = -1;
    static constexpr jint ERROR = -1;
    static constexpr jint ERROR_DEAD_OBJECT = -6;
    static constexpr auto EXTRA_AUDIO_PLUG_STATE = u8"android.media.extra.AUDIO_PLUG_STATE";
    static constexpr auto EXTRA_ENCODINGS = u8"android.media.extra.ENCODINGS";
    static constexpr auto EXTRA_MAX_CHANNEL_COUNT = u8"android.media.extra.MAX_CHANNEL_COUNT";
    static constexpr auto EXTRA_RINGER_MODE = u8"android.media.EXTRA_RINGER_MODE";
    static constexpr auto EXTRA_SCO_AUDIO_PREVIOUS_STATE = u8"android.media.extra.SCO_AUDIO_PREVIOUS_STATE";
    static constexpr auto EXTRA_SCO_AUDIO_STATE = u8"android.media.extra.SCO_AUDIO_STATE";
    static constexpr auto EXTRA_VIBRATE_SETTING = u8"android.media.EXTRA_VIBRATE_SETTING";
    static constexpr auto EXTRA_VIBRATE_TYPE = u8"android.media.EXTRA_VIBRATE_TYPE";
    static constexpr jint FLAG_ALLOW_RINGER_MODES = 2;
    static constexpr jint FLAG_PLAY_SOUND = 4;
    static constexpr jint FLAG_REMOVE_SOUND_AND_VIBRATE = 8;
    static constexpr jint FLAG_SHOW_UI = 1;
    static constexpr jint FLAG_VIBRATE = 16;
    static constexpr jint FX_BACK = 10;
    static constexpr jint FX_FOCUS_NAVIGATION_DOWN = 2;
    static constexpr jint FX_FOCUS_NAVIGATION_LEFT = 3;
    static constexpr jint FX_FOCUS_NAVIGATION_RIGHT = 4;
    static constexpr jint FX_FOCUS_NAVIGATION_UP = 1;
    static constexpr jint FX_KEYPRESS_DELETE = 7;
    static constexpr jint FX_KEYPRESS_INVALID = 9;
    static constexpr jint FX_KEYPRESS_RETURN = 8;
    static constexpr jint FX_KEYPRESS_SPACEBAR = 6;
    static constexpr jint FX_KEYPRESS_STANDARD = 5;
    static constexpr jint FX_KEY_CLICK = 0;
    static constexpr jint GET_DEVICES_ALL = 3;
    static constexpr jint GET_DEVICES_INPUTS = 1;
    static constexpr jint GET_DEVICES_OUTPUTS = 2;
    static constexpr jint MODE_CALL_REDIRECT = 5;
    static constexpr jint MODE_CALL_SCREENING = 4;
    static constexpr jint MODE_COMMUNICATION_REDIRECT = 6;
    static constexpr jint MODE_CURRENT = -1;
    static constexpr jint MODE_INVALID = -2;
    static constexpr jint MODE_IN_CALL = 2;
    static constexpr jint MODE_IN_COMMUNICATION = 3;
    static constexpr jint MODE_NORMAL = 0;
    static constexpr jint MODE_RINGTONE = 1;
    static constexpr jint NUM_STREAMS = 5;
    static constexpr jint PLAYBACK_OFFLOAD_GAPLESS_SUPPORTED = 2;
    static constexpr jint PLAYBACK_OFFLOAD_NOT_SUPPORTED = 0;
    static constexpr jint PLAYBACK_OFFLOAD_SUPPORTED = 1;
    static constexpr auto PROPERTY_OUTPUT_FRAMES_PER_BUFFER = u8"android.media.property.OUTPUT_FRAMES_PER_BUFFER";
    static constexpr auto PROPERTY_OUTPUT_SAMPLE_RATE = u8"android.media.property.OUTPUT_SAMPLE_RATE";
    static constexpr auto PROPERTY_SUPPORT_AUDIO_SOURCE_UNPROCESSED = u8"android.media.property.SUPPORT_AUDIO_SOURCE_UNPROCESSED";
    static constexpr auto PROPERTY_SUPPORT_MIC_NEAR_ULTRASOUND = u8"android.media.property.SUPPORT_MIC_NEAR_ULTRASOUND";
    static constexpr auto PROPERTY_SUPPORT_SPEAKER_NEAR_ULTRASOUND = u8"android.media.property.SUPPORT_SPEAKER_NEAR_ULTRASOUND";
    static constexpr auto RINGER_MODE_CHANGED_ACTION = u8"android.media.RINGER_MODE_CHANGED";
    static constexpr jint RINGER_MODE_NORMAL = 2;
    static constexpr jint RINGER_MODE_SILENT = 0;
    static constexpr jint RINGER_MODE_VIBRATE = 1;
    static constexpr jint ROUTE_ALL = -1;
    static constexpr jint ROUTE_BLUETOOTH = 4;
    static constexpr jint ROUTE_BLUETOOTH_A2DP = 16;
    static constexpr jint ROUTE_BLUETOOTH_SCO = 4;
    static constexpr jint ROUTE_EARPIECE = 1;
    static constexpr jint ROUTE_HEADSET = 8;
    static constexpr jint ROUTE_SPEAKER = 2;
    static constexpr jint SCO_AUDIO_STATE_CONNECTED = 1;
    static constexpr jint SCO_AUDIO_STATE_CONNECTING = 2;
    static constexpr jint SCO_AUDIO_STATE_DISCONNECTED = 0;
    static constexpr jint SCO_AUDIO_STATE_ERROR = -1;
    static constexpr jint STREAM_ACCESSIBILITY = 10;
    static constexpr jint STREAM_ALARM = 4;
    static constexpr jint STREAM_DTMF = 8;
    static constexpr jint STREAM_MUSIC = 3;
    static constexpr jint STREAM_NOTIFICATION = 5;
    static constexpr jint STREAM_RING = 2;
    static constexpr jint STREAM_SYSTEM = 1;
    static constexpr jint STREAM_VOICE_CALL = 0;
    static constexpr jint USE_DEFAULT_STREAM_TYPE = -2147483648;
    static constexpr auto VIBRATE_SETTING_CHANGED_ACTION = u8"android.media.VIBRATE_SETTING_CHANGED";
    static constexpr jint VIBRATE_SETTING_OFF = 0;
    static constexpr jint VIBRATE_SETTING_ON = 1;
    static constexpr jint VIBRATE_SETTING_ONLY_SILENT = 2;
    static constexpr jint VIBRATE_TYPE_NOTIFICATION = 1;
    static constexpr jint VIBRATE_TYPE_RINGER = 0;


    // method: public void dispatchMediaKeyEvent(android.view.KeyEvent keyEvent)
    auto dispatchMediaKeyEvent(jobject keyEvent) const {
        m_jniObject.callMethod<void>(
                        "dispatchMediaKeyEvent",
                        "(Landroid/view/KeyEvent;)V", keyEvent);
    }


    // method: public boolean isVolumeFixed()
    auto isVolumeFixed() const {
        return m_jniObject.callMethod<jboolean>(
                        "isVolumeFixed",
                        "()Z");
    }


    // method: public void adjustStreamVolume(int streamType, int direction, int flags)
    auto adjustStreamVolume(jint streamType, jint direction, jint flags) const {
        m_jniObject.callMethod<void>(
                        "adjustStreamVolume",
                        "(III)V", streamType, direction, flags);
    }


    // method: public void adjustVolume(int direction, int flags)
    auto adjustVolume(jint direction, jint flags) const {
        m_jniObject.callMethod<void>(
                        "adjustVolume",
                        "(II)V", direction, flags);
    }


    // method: public void adjustSuggestedStreamVolume(int direction, int suggestedStreamType, int flags)
    auto adjustSuggestedStreamVolume(jint direction, jint suggestedStreamType, jint flags) const {
        m_jniObject.callMethod<void>(
                        "adjustSuggestedStreamVolume",
                        "(III)V", direction, suggestedStreamType, flags);
    }


    // method: public int getRingerMode()
    auto getRingerMode() const {
        return m_jniObject.callMethod<jint>(
                        "getRingerMode",
                        "()I");
    }


    // method: public boolean isRampingRingerEnabled()
    auto isRampingRingerEnabled() const {
        return m_jniObject.callMethod<jboolean>(
                        "isRampingRingerEnabled",
                        "()Z");
    }


    // method: public int getStreamMaxVolume(int streamType)
    auto getStreamMaxVolume(jint streamType) const {
        return m_jniObject.callMethod<jint>(
                        "getStreamMaxVolume",
                        "(I)I", streamType);
    }


    // method: public int getStreamMinVolume(int streamType)
    auto getStreamMinVolume(jint streamType) const {
        return m_jniObject.callMethod<jint>(
                        "getStreamMinVolume",
                        "(I)I", streamType);
    }


    // method: public int getStreamVolume(int streamType)
    auto getStreamVolume(jint streamType) const {
        return m_jniObject.callMethod<jint>(
                        "getStreamVolume",
                        "(I)I", streamType);
    }


    // method: public float getStreamVolumeDb(int streamType, int index, int deviceType)
    auto getStreamVolumeDb(jint streamType, jint index, jint deviceType) const {
        return m_jniObject.callMethod<jfloat>(
                        "getStreamVolumeDb",
                        "(III)F", streamType, index, deviceType);
    }


    // method: public void setRingerMode(int ringerMode)
    auto setRingerMode(jint ringerMode) const {
        m_jniObject.callMethod<void>(
                        "setRingerMode",
                        "(I)V", ringerMode);
    }


    // method: public void setStreamVolume(int streamType, int index, int flags)
    auto setStreamVolume(jint streamType, jint index, jint flags) const {
        m_jniObject.callMethod<void>(
                        "setStreamVolume",
                        "(III)V", streamType, index, flags);
    }


    // method: public int getVolumeGroupIdForAttributes(android.media.AudioAttributes attributes)
    auto getVolumeGroupIdForAttributes(jobject attributes) const {
        return m_jniObject.callMethod<jint>(
                        "getVolumeGroupIdForAttributes",
                        "(Landroid/media/AudioAttributes;)I", attributes);
    }


    // method: public void adjustVolumeGroupVolume(int groupId, int direction, int flags)
    auto adjustVolumeGroupVolume(jint groupId, jint direction, jint flags) const {
        m_jniObject.callMethod<void>(
                        "adjustVolumeGroupVolume",
                        "(III)V", groupId, direction, flags);
    }


    // method: public boolean isVolumeGroupMuted(int groupId)
    auto isVolumeGroupMuted(jint groupId) const {
        return m_jniObject.callMethod<jboolean>(
                        "isVolumeGroupMuted",
                        "(I)Z", groupId);
    }


    // method: public void setStreamSolo(int streamType, boolean state)
    auto setStreamSolo(jint streamType, jboolean state) const {
        m_jniObject.callMethod<void>(
                        "setStreamSolo",
                        "(IZ)V", streamType, state);
    }


    // method: public void setStreamMute(int streamType, boolean state)
    auto setStreamMute(jint streamType, jboolean state) const {
        m_jniObject.callMethod<void>(
                        "setStreamMute",
                        "(IZ)V", streamType, state);
    }


    // method: public boolean isStreamMute(int streamType)
    auto isStreamMute(jint streamType) const {
        return m_jniObject.callMethod<jboolean>(
                        "isStreamMute",
                        "(I)Z", streamType);
    }


    // method: public boolean shouldVibrate(int vibrateType)
    auto shouldVibrate(jint vibrateType) const {
        return m_jniObject.callMethod<jboolean>(
                        "shouldVibrate",
                        "(I)Z", vibrateType);
    }


    // method: public int getVibrateSetting(int vibrateType)
    auto getVibrateSetting(jint vibrateType) const {
        return m_jniObject.callMethod<jint>(
                        "getVibrateSetting",
                        "(I)I", vibrateType);
    }


    // method: public void setVibrateSetting(int vibrateType, int vibrateSetting)
    auto setVibrateSetting(jint vibrateType, jint vibrateSetting) const {
        m_jniObject.callMethod<void>(
                        "setVibrateSetting",
                        "(II)V", vibrateType, vibrateSetting);
    }


    // method: public void setSpeakerphoneOn(boolean on)
    auto setSpeakerphoneOn(jboolean on) const {
        m_jniObject.callMethod<void>(
                        "setSpeakerphoneOn",
                        "(Z)V", on);
    }


    // method: public boolean isSpeakerphoneOn()
    auto isSpeakerphoneOn() const {
        return m_jniObject.callMethod<jboolean>(
                        "isSpeakerphoneOn",
                        "()Z");
    }


    // method: public void setAllowedCapturePolicy(int capturePolicy)
    auto setAllowedCapturePolicy(jint capturePolicy) const {
        m_jniObject.callMethod<void>(
                        "setAllowedCapturePolicy",
                        "(I)V", capturePolicy);
    }


    // method: public int getAllowedCapturePolicy()
    auto getAllowedCapturePolicy() const {
        return m_jniObject.callMethod<jint>(
                        "getAllowedCapturePolicy",
                        "()I");
    }


    // method: public static int getDirectPlaybackSupport(android.media.AudioFormat format, android.media.AudioAttributes attributes)
    static auto getDirectPlaybackSupport(jobject format, jobject attributes) {
        return QJniObject::callStaticMethod<jint>(FULL_CLASS_NAME,
                        "getDirectPlaybackSupport",
                        "(Landroid/media/AudioFormat;Landroid/media/AudioAttributes;)I", format, attributes);
    }


    // method: public static boolean isOffloadedPlaybackSupported(android.media.AudioFormat format, android.media.AudioAttributes attributes)
    static auto isOffloadedPlaybackSupported(jobject format, jobject attributes) {
        return QJniObject::callStaticMethod<jboolean>(FULL_CLASS_NAME,
                        "isOffloadedPlaybackSupported",
                        "(Landroid/media/AudioFormat;Landroid/media/AudioAttributes;)Z", format, attributes);
    }


    // method: public static int getPlaybackOffloadSupport(android.media.AudioFormat format, android.media.AudioAttributes attributes)
    static auto getPlaybackOffloadSupport(jobject format, jobject attributes) {
        return QJniObject::callStaticMethod<jint>(FULL_CLASS_NAME,
                        "getPlaybackOffloadSupport",
                        "(Landroid/media/AudioFormat;Landroid/media/AudioAttributes;)I", format, attributes);
    }


    // method: public android.media.Spatializer getSpatializer()
    auto getSpatializer() const {
        return m_jniObject.callMethod<jobject>(
                        "getSpatializer",
                        "()Landroid/media/Spatializer;");
    }


    // method: public boolean isBluetoothScoAvailableOffCall()
    auto isBluetoothScoAvailableOffCall() const {
        return m_jniObject.callMethod<jboolean>(
                        "isBluetoothScoAvailableOffCall",
                        "()Z");
    }


    // method: public void startBluetoothSco()
    auto startBluetoothSco() const {
        m_jniObject.callMethod<void>(
                        "startBluetoothSco",
                        "()V");
    }


    // method: public void stopBluetoothSco()
    auto stopBluetoothSco() const {
        m_jniObject.callMethod<void>(
                        "stopBluetoothSco",
                        "()V");
    }


    // method: public void setBluetoothScoOn(boolean on)
    auto setBluetoothScoOn(jboolean on) const {
        m_jniObject.callMethod<void>(
                        "setBluetoothScoOn",
                        "(Z)V", on);
    }


    // method: public boolean isBluetoothScoOn()
    auto isBluetoothScoOn() const {
        return m_jniObject.callMethod<jboolean>(
                        "isBluetoothScoOn",
                        "()Z");
    }


    // method: public void setBluetoothA2dpOn(boolean on)
    auto setBluetoothA2dpOn(jboolean on) const {
        m_jniObject.callMethod<void>(
                        "setBluetoothA2dpOn",
                        "(Z)V", on);
    }


    // method: public boolean isBluetoothA2dpOn()
    auto isBluetoothA2dpOn() const {
        return m_jniObject.callMethod<jboolean>(
                        "isBluetoothA2dpOn",
                        "()Z");
    }


    // method: public void setWiredHeadsetOn(boolean on)
    auto setWiredHeadsetOn(jboolean on) const {
        m_jniObject.callMethod<void>(
                        "setWiredHeadsetOn",
                        "(Z)V", on);
    }


    // method: public boolean isWiredHeadsetOn()
    auto isWiredHeadsetOn() const {
        return m_jniObject.callMethod<jboolean>(
                        "isWiredHeadsetOn",
                        "()Z");
    }


    // method: public void setMicrophoneMute(boolean on)
    auto setMicrophoneMute(jboolean on) const {
        m_jniObject.callMethod<void>(
                        "setMicrophoneMute",
                        "(Z)V", on);
    }


    // method: public boolean isMicrophoneMute()
    auto isMicrophoneMute() const {
        return m_jniObject.callMethod<jboolean>(
                        "isMicrophoneMute",
                        "()Z");
    }


    // method: public void setMode(int mode)
    auto setMode(jint mode) const {
        m_jniObject.callMethod<void>(
                        "setMode",
                        "(I)V", mode);
    }


    // method: public int getMode()
    auto getMode() const {
        return m_jniObject.callMethod<jint>(
                        "getMode",
                        "()I");
    }


    // method: public void addOnModeChangedListener(java.util.concurrent.Executor executor, android.media.AudioManager.OnModeChangedListener listener)
    auto addOnModeChangedListener(jobject executor, jobject listener) const {
        m_jniObject.callMethod<void>(
                        "addOnModeChangedListener",
                        "(Ljava/util/concurrent/Executor;Landroid/media/AudioManager$OnModeChangedListener;)V", executor, listener);
    }


    // method: public void removeOnModeChangedListener(android.media.AudioManager.OnModeChangedListener listener)
    auto removeOnModeChangedListener(jobject listener) const {
        m_jniObject.callMethod<void>(
                        "removeOnModeChangedListener",
                        "(Landroid/media/AudioManager$OnModeChangedListener;)V", listener);
    }


    // method: public boolean isCallScreeningModeSupported()
    auto isCallScreeningModeSupported() const {
        return m_jniObject.callMethod<jboolean>(
                        "isCallScreeningModeSupported",
                        "()Z");
    }


    // method: public void setRouting(int mode, int routes, int mask)
    auto setRouting(jint mode, jint routes, jint mask) const {
        m_jniObject.callMethod<void>(
                        "setRouting",
                        "(III)V", mode, routes, mask);
    }


    // method: public int getRouting(int mode)
    auto getRouting(jint mode) const {
        return m_jniObject.callMethod<jint>(
                        "getRouting",
                        "(I)I", mode);
    }


    // method: public boolean isMusicActive()
    auto isMusicActive() const {
        return m_jniObject.callMethod<jboolean>(
                        "isMusicActive",
                        "()Z");
    }


    // method: public int generateAudioSessionId()
    auto generateAudioSessionId() const {
        return m_jniObject.callMethod<jint>(
                        "generateAudioSessionId",
                        "()I");
    }


    // method: public void setParameters(java.lang.String keyValuePairs)
    auto setParameters(jstring keyValuePairs) const {
        m_jniObject.callMethod<void>(
                        "setParameters",
                        "(Ljava/lang/String;)V", keyValuePairs);
    }


    // method: public java.lang.String getParameters(java.lang.String keys)
    auto getParameters(jstring keys) const {
        return m_jniObject.callMethod<jstring>(
                        "getParameters",
                        "(Ljava/lang/String;)Ljava/lang/String;", keys);
    }


    // method: public void playSoundEffect(int effectType)
    auto playSoundEffect(jint effectType) const {
        m_jniObject.callMethod<void>(
                        "playSoundEffect",
                        "(I)V", effectType);
    }


    // method: public void playSoundEffect(int effectType, float volume)
    auto playSoundEffect(jint effectType, jfloat volume) const {
        m_jniObject.callMethod<void>(
                        "playSoundEffect",
                        "(IF)V", effectType, volume);
    }


    // method: public void loadSoundEffects()
    auto loadSoundEffects() const {
        m_jniObject.callMethod<void>(
                        "loadSoundEffects",
                        "()V");
    }


    // method: public void unloadSoundEffects()
    auto unloadSoundEffects() const {
        m_jniObject.callMethod<void>(
                        "unloadSoundEffects",
                        "()V");
    }


    // method: public int requestAudioFocus(android.media.AudioManager.OnAudioFocusChangeListener l, int streamType, int durationHint)
    auto requestAudioFocus(jobject l, jint streamType, jint durationHint) const {
        return m_jniObject.callMethod<jint>(
                        "requestAudioFocus",
                        "(Landroid/media/AudioManager$OnAudioFocusChangeListener;II)I", l, streamType, durationHint);
    }


    // method: public int requestAudioFocus(android.media.AudioFocusRequest focusRequest)
    auto requestAudioFocus(jobject focusRequest) const {
        return m_jniObject.callMethod<jint>(
                        "requestAudioFocus",
                        "(Landroid/media/AudioFocusRequest;)I", focusRequest);
    }


    // method: public int abandonAudioFocusRequest(android.media.AudioFocusRequest focusRequest)
    auto abandonAudioFocusRequest(jobject focusRequest) const {
        return m_jniObject.callMethod<jint>(
                        "abandonAudioFocusRequest",
                        "(Landroid/media/AudioFocusRequest;)I", focusRequest);
    }


    // method: public int abandonAudioFocus(android.media.AudioManager.OnAudioFocusChangeListener l)
    auto abandonAudioFocus(jobject l) const {
        return m_jniObject.callMethod<jint>(
                        "abandonAudioFocus",
                        "(Landroid/media/AudioManager$OnAudioFocusChangeListener;)I", l);
    }


    // method: public void registerMediaButtonEventReceiver(android.content.ComponentName eventReceiver)
    auto registerMediaButtonEventReceiver__Landroid_content_ComponentName_2(jobject eventReceiver) const {
        m_jniObject.callMethod<void>(
                        "registerMediaButtonEventReceiver",
                        "(Landroid/content/ComponentName;)V", eventReceiver);
    }


    // method: public void registerMediaButtonEventReceiver(android.app.PendingIntent eventReceiver)
    auto registerMediaButtonEventReceiver__Landroid_app_PendingIntent_2(jobject eventReceiver) const {
        m_jniObject.callMethod<void>(
                        "registerMediaButtonEventReceiver",
                        "(Landroid/app/PendingIntent;)V", eventReceiver);
    }


    // method: public void unregisterMediaButtonEventReceiver(android.content.ComponentName eventReceiver)
    auto unregisterMediaButtonEventReceiver__Landroid_content_ComponentName_2(jobject eventReceiver) const {
        m_jniObject.callMethod<void>(
                        "unregisterMediaButtonEventReceiver",
                        "(Landroid/content/ComponentName;)V", eventReceiver);
    }


    // method: public void unregisterMediaButtonEventReceiver(android.app.PendingIntent eventReceiver)
    auto unregisterMediaButtonEventReceiver__Landroid_app_PendingIntent_2(jobject eventReceiver) const {
        m_jniObject.callMethod<void>(
                        "unregisterMediaButtonEventReceiver",
                        "(Landroid/app/PendingIntent;)V", eventReceiver);
    }


    // method: public void registerRemoteControlClient(android.media.RemoteControlClient rcClient)
    auto registerRemoteControlClient(jobject rcClient) const {
        m_jniObject.callMethod<void>(
                        "registerRemoteControlClient",
                        "(Landroid/media/RemoteControlClient;)V", rcClient);
    }


    // method: public void unregisterRemoteControlClient(android.media.RemoteControlClient rcClient)
    auto unregisterRemoteControlClient(jobject rcClient) const {
        m_jniObject.callMethod<void>(
                        "unregisterRemoteControlClient",
                        "(Landroid/media/RemoteControlClient;)V", rcClient);
    }


    // method: public boolean registerRemoteController(android.media.RemoteController rctlr)
    auto registerRemoteController(jobject rctlr) const {
        return m_jniObject.callMethod<jboolean>(
                        "registerRemoteController",
                        "(Landroid/media/RemoteController;)Z", rctlr);
    }


    // method: public void unregisterRemoteController(android.media.RemoteController rctlr)
    auto unregisterRemoteController(jobject rctlr) const {
        m_jniObject.callMethod<void>(
                        "unregisterRemoteController",
                        "(Landroid/media/RemoteController;)V", rctlr);
    }


    // method: public void registerAudioPlaybackCallback(android.media.AudioManager.AudioPlaybackCallback cb, android.os.Handler handler)
    auto registerAudioPlaybackCallback(jobject cb, jobject handler) const {
        m_jniObject.callMethod<void>(
                        "registerAudioPlaybackCallback",
                        "(Landroid/media/AudioManager$AudioPlaybackCallback;Landroid/os/Handler;)V", cb, handler);
    }


    // method: public void unregisterAudioPlaybackCallback(android.media.AudioManager.AudioPlaybackCallback cb)
    auto unregisterAudioPlaybackCallback(jobject cb) const {
        m_jniObject.callMethod<void>(
                        "unregisterAudioPlaybackCallback",
                        "(Landroid/media/AudioManager$AudioPlaybackCallback;)V", cb);
    }


    // method: public java.util.List<android.media.AudioPlaybackConfiguration> getActivePlaybackConfigurations()
    auto getActivePlaybackConfigurations() const {
        return m_jniObject.callMethod<jobject>(
                        "getActivePlaybackConfigurations",
                        "()Ljava/util/List;");
    }


    // method: public void registerAudioRecordingCallback(android.media.AudioManager.AudioRecordingCallback cb, android.os.Handler handler)
    auto registerAudioRecordingCallback(jobject cb, jobject handler) const {
        m_jniObject.callMethod<void>(
                        "registerAudioRecordingCallback",
                        "(Landroid/media/AudioManager$AudioRecordingCallback;Landroid/os/Handler;)V", cb, handler);
    }


    // method: public void unregisterAudioRecordingCallback(android.media.AudioManager.AudioRecordingCallback cb)
    auto unregisterAudioRecordingCallback(jobject cb) const {
        m_jniObject.callMethod<void>(
                        "unregisterAudioRecordingCallback",
                        "(Landroid/media/AudioManager$AudioRecordingCallback;)V", cb);
    }


    // method: public java.util.List<android.media.AudioRecordingConfiguration> getActiveRecordingConfigurations()
    auto getActiveRecordingConfigurations() const {
        return m_jniObject.callMethod<jobject>(
                        "getActiveRecordingConfigurations",
                        "()Ljava/util/List;");
    }


    // method: public java.util.List<android.media.AudioDeviceInfo> getAudioDevicesForAttributes(android.media.AudioAttributes attributes)
    auto getAudioDevicesForAttributes(jobject attributes) const {
        return m_jniObject.callMethod<jobject>(
                        "getAudioDevicesForAttributes",
                        "(Landroid/media/AudioAttributes;)Ljava/util/List;", attributes);
    }


    // method: public java.lang.String getProperty(java.lang.String key)
    auto getProperty(jstring key) const {
        return m_jniObject.callMethod<jstring>(
                        "getProperty",
                        "(Ljava/lang/String;)Ljava/lang/String;", key);
    }


    // method: public java.util.Set<java.lang.Integer> getSupportedDeviceTypes(int direction)
    auto getSupportedDeviceTypes(jint direction) const {
        return m_jniObject.callMethod<jobject>(
                        "getSupportedDeviceTypes",
                        "(I)Ljava/util/Set;", direction);
    }


    // method: public android.media.AudioDeviceInfo[] getDevices(int flags)
    auto getDevices(jint flags) const {
        return m_jniObject.callMethod<jobjectArray>(
                        "getDevices",
                        "(I)[Landroid/media/AudioDeviceInfo;", flags);
    }


    // method: public void registerAudioDeviceCallback(android.media.AudioDeviceCallback callback, android.os.Handler handler)
    auto registerAudioDeviceCallback(jobject callback, jobject handler) const {
        m_jniObject.callMethod<void>(
                        "registerAudioDeviceCallback",
                        "(Landroid/media/AudioDeviceCallback;Landroid/os/Handler;)V", callback, handler);
    }


    // method: public void unregisterAudioDeviceCallback(android.media.AudioDeviceCallback callback)
    auto unregisterAudioDeviceCallback(jobject callback) const {
        m_jniObject.callMethod<void>(
                        "unregisterAudioDeviceCallback",
                        "(Landroid/media/AudioDeviceCallback;)V", callback);
    }


    // method: public java.util.List<android.media.MicrophoneInfo> getMicrophones()
    auto getMicrophones() const {
        return m_jniObject.callMethod<jobject>(
                        "getMicrophones",
                        "()Ljava/util/List;");
    }


    // method: public boolean setEncodedSurroundMode(int mode)
    auto setEncodedSurroundMode(jint mode) const {
        return m_jniObject.callMethod<jboolean>(
                        "setEncodedSurroundMode",
                        "(I)Z", mode);
    }


    // method: public int getEncodedSurroundMode()
    auto getEncodedSurroundMode() const {
        return m_jniObject.callMethod<jint>(
                        "getEncodedSurroundMode",
                        "()I");
    }


    // method: public boolean setSurroundFormatEnabled(int audioFormat, boolean enabled)
    auto setSurroundFormatEnabled(jint audioFormat, jboolean enabled) const {
        return m_jniObject.callMethod<jboolean>(
                        "setSurroundFormatEnabled",
                        "(IZ)Z", audioFormat, enabled);
    }


    // method: public boolean isSurroundFormatEnabled(int audioFormat)
    auto isSurroundFormatEnabled(jint audioFormat) const {
        return m_jniObject.callMethod<jboolean>(
                        "isSurroundFormatEnabled",
                        "(I)Z", audioFormat);
    }


    // method: public static boolean isHapticPlaybackSupported()
    static auto isHapticPlaybackSupported() {
        return QJniObject::callStaticMethod<jboolean>(FULL_CLASS_NAME,
                        "isHapticPlaybackSupported",
                        "()Z");
    }


    // method: public int getAudioHwSyncForSession(int sessionId)
    auto getAudioHwSyncForSession(jint sessionId) const {
        return m_jniObject.callMethod<jint>(
                        "getAudioHwSyncForSession",
                        "(I)I", sessionId);
    }


    // method: public boolean setCommunicationDevice(android.media.AudioDeviceInfo device)
    auto setCommunicationDevice(jobject device) const {
        return m_jniObject.callMethod<jboolean>(
                        "setCommunicationDevice",
                        "(Landroid/media/AudioDeviceInfo;)Z", device);
    }


    // method: public void clearCommunicationDevice()
    auto clearCommunicationDevice() const {
        m_jniObject.callMethod<void>(
                        "clearCommunicationDevice",
                        "()V");
    }


    // method: public android.media.AudioDeviceInfo getCommunicationDevice()
    auto getCommunicationDevice() const {
        return m_jniObject.callMethod<jobject>(
                        "getCommunicationDevice",
                        "()Landroid/media/AudioDeviceInfo;");
    }


    // method: public java.util.List<android.media.AudioDeviceInfo> getAvailableCommunicationDevices()
    auto getAvailableCommunicationDevices() const {
        return m_jniObject.callMethod<jobject>(
                        "getAvailableCommunicationDevices",
                        "()Ljava/util/List;");
    }


    // method: public java.util.List<android.media.AudioProfile> getDirectProfilesForAttributes(android.media.AudioAttributes attributes)
    auto getDirectProfilesForAttributes(jobject attributes) const {
        return m_jniObject.callMethod<jobject>(
                        "getDirectProfilesForAttributes",
                        "(Landroid/media/AudioAttributes;)Ljava/util/List;", attributes);
    }


    // method: public void addOnCommunicationDeviceChangedListener(java.util.concurrent.Executor executor, android.media.AudioManager.OnCommunicationDeviceChangedListener listener)
    auto addOnCommunicationDeviceChangedListener(jobject executor, jobject listener) const {
        m_jniObject.callMethod<void>(
                        "addOnCommunicationDeviceChangedListener",
                        "(Ljava/util/concurrent/Executor;Landroid/media/AudioManager$OnCommunicationDeviceChangedListener;)V", executor, listener);
    }


    // method: public void removeOnCommunicationDeviceChangedListener(android.media.AudioManager.OnCommunicationDeviceChangedListener listener)
    auto removeOnCommunicationDeviceChangedListener(jobject listener) const {
        m_jniObject.callMethod<void>(
                        "removeOnCommunicationDeviceChangedListener",
                        "(Landroid/media/AudioManager$OnCommunicationDeviceChangedListener;)V", listener);
    }


    // method: public java.util.List<android.media.AudioMixerAttributes> getSupportedMixerAttributes(android.media.AudioDeviceInfo device)
    auto getSupportedMixerAttributes(jobject device) const {
        return m_jniObject.callMethod<jobject>(
                        "getSupportedMixerAttributes",
                        "(Landroid/media/AudioDeviceInfo;)Ljava/util/List;", device);
    }


    // method: public boolean setPreferredMixerAttributes(android.media.AudioAttributes attributes, android.media.AudioDeviceInfo device, android.media.AudioMixerAttributes mixerAttributes)
    auto setPreferredMixerAttributes(jobject attributes, jobject device, jobject mixerAttributes) const {
        return m_jniObject.callMethod<jboolean>(
                        "setPreferredMixerAttributes",
                        "(Landroid/media/AudioAttributes;Landroid/media/AudioDeviceInfo;Landroid/media/AudioMixerAttributes;)Z", attributes, device, mixerAttributes);
    }


    // method: public android.media.AudioMixerAttributes getPreferredMixerAttributes(android.media.AudioAttributes attributes, android.media.AudioDeviceInfo device)
    auto getPreferredMixerAttributes(jobject attributes, jobject device) const {
        return m_jniObject.callMethod<jobject>(
                        "getPreferredMixerAttributes",
                        "(Landroid/media/AudioAttributes;Landroid/media/AudioDeviceInfo;)Landroid/media/AudioMixerAttributes;", attributes, device);
    }


    // method: public boolean clearPreferredMixerAttributes(android.media.AudioAttributes attributes, android.media.AudioDeviceInfo device)
    auto clearPreferredMixerAttributes(jobject attributes, jobject device) const {
        return m_jniObject.callMethod<jboolean>(
                        "clearPreferredMixerAttributes",
                        "(Landroid/media/AudioAttributes;Landroid/media/AudioDeviceInfo;)Z", attributes, device);
    }


    // method: public void addOnPreferredMixerAttributesChangedListener(java.util.concurrent.Executor executor, android.media.AudioManager.OnPreferredMixerAttributesChangedListener listener)
    auto addOnPreferredMixerAttributesChangedListener(jobject executor, jobject listener) const {
        m_jniObject.callMethod<void>(
                        "addOnPreferredMixerAttributesChangedListener",
                        "(Ljava/util/concurrent/Executor;Landroid/media/AudioManager$OnPreferredMixerAttributesChangedListener;)V", executor, listener);
    }


    // method: public void removeOnPreferredMixerAttributesChangedListener(android.media.AudioManager.OnPreferredMixerAttributesChangedListener listener)
    auto removeOnPreferredMixerAttributesChangedListener(jobject listener) const {
        m_jniObject.callMethod<void>(
                        "removeOnPreferredMixerAttributesChangedListener",
                        "(Landroid/media/AudioManager$OnPreferredMixerAttributesChangedListener;)V", listener);
    }


};
} } // endof namespace android::media


namespace android { namespace media {


} } // endof namespace android::media

#endif // android_media_AudioManagerProxy_H

