
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef android_app_BuilderProxy_H
#define android_app_BuilderProxy_H

#include <QJniObject>
#include <cmath>

namespace android { namespace app {
class BuilderProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "android/app/Notification$Builder";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    BuilderProxy() {}
    BuilderProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    BuilderProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static BuilderProxy fromLocalRef(jobject localRef) {
        BuilderProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }



    // construct: public Builder(android.content.Context context, java.lang.String channelId)
    static BuilderProxy newInstance(jobject context, jstring channelId) {
        BuilderProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Landroid/content/Context;Ljava/lang/String;)V", context, channelId);
        return ret;
    }

    // construct: public Builder(android.content.Context context)
    static BuilderProxy newInstance(jobject context) {
        BuilderProxy ret;
        ret.m_jniObject = QJniObject(FULL_CLASS_NAME, "(Landroid/content/Context;)V", context);
        return ret;
    }

    // method: public android.app.Notification.Builder setShortcutId(java.lang.String shortcutId)
    auto setShortcutId(jstring shortcutId) const {
        return m_jniObject.callMethod<jobject>(
                        "setShortcutId",
                        "(Ljava/lang/String;)Landroid/app/Notification$Builder;", shortcutId);
    }


    // method: public android.app.Notification.Builder setLocusId(android.content.LocusId locusId)
    auto setLocusId(jobject locusId) const {
        return m_jniObject.callMethod<jobject>(
                        "setLocusId",
                        "(Landroid/content/LocusId;)Landroid/app/Notification$Builder;", locusId);
    }


    // method: public android.app.Notification.Builder setBadgeIconType(int icon)
    auto setBadgeIconType(jint icon) const {
        return m_jniObject.callMethod<jobject>(
                        "setBadgeIconType",
                        "(I)Landroid/app/Notification$Builder;", icon);
    }


    // method: public android.app.Notification.Builder setGroupAlertBehavior(int groupAlertBehavior)
    auto setGroupAlertBehavior(jint groupAlertBehavior) const {
        return m_jniObject.callMethod<jobject>(
                        "setGroupAlertBehavior",
                        "(I)Landroid/app/Notification$Builder;", groupAlertBehavior);
    }


    // method: public android.app.Notification.Builder setBubbleMetadata(android.app.Notification.BubbleMetadata data)
    auto setBubbleMetadata(jobject data) const {
        return m_jniObject.callMethod<jobject>(
                        "setBubbleMetadata",
                        "(Landroid/app/Notification$BubbleMetadata;)Landroid/app/Notification$Builder;", data);
    }


    // method: public android.app.Notification.Builder setChannelId(java.lang.String channelId)
    auto setChannelId(jstring channelId) const {
        return m_jniObject.callMethod<jobject>(
                        "setChannelId",
                        "(Ljava/lang/String;)Landroid/app/Notification$Builder;", channelId);
    }


    // method: public android.app.Notification.Builder setTimeoutAfter(long durationMs)
    auto setTimeoutAfter(jlong durationMs) const {
        return m_jniObject.callMethod<jobject>(
                        "setTimeoutAfter",
                        "(J)Landroid/app/Notification$Builder;", durationMs);
    }


    // method: public android.app.Notification.Builder setWhen(long when)
    auto setWhen(jlong when) const {
        return m_jniObject.callMethod<jobject>(
                        "setWhen",
                        "(J)Landroid/app/Notification$Builder;", when);
    }


    // method: public android.app.Notification.Builder setShowWhen(boolean show)
    auto setShowWhen(jboolean show) const {
        return m_jniObject.callMethod<jobject>(
                        "setShowWhen",
                        "(Z)Landroid/app/Notification$Builder;", show);
    }


    // method: public android.app.Notification.Builder setUsesChronometer(boolean b)
    auto setUsesChronometer(jboolean b) const {
        return m_jniObject.callMethod<jobject>(
                        "setUsesChronometer",
                        "(Z)Landroid/app/Notification$Builder;", b);
    }


    // method: public android.app.Notification.Builder setChronometerCountDown(boolean countDown)
    auto setChronometerCountDown(jboolean countDown) const {
        return m_jniObject.callMethod<jobject>(
                        "setChronometerCountDown",
                        "(Z)Landroid/app/Notification$Builder;", countDown);
    }


    // method: public android.app.Notification.Builder setSmallIcon(int icon)
    auto setSmallIcon(jint icon) const {
        return m_jniObject.callMethod<jobject>(
                        "setSmallIcon",
                        "(I)Landroid/app/Notification$Builder;", icon);
    }


    // method: public android.app.Notification.Builder setSmallIcon(int icon, int level)
    auto setSmallIcon(jint icon, jint level) const {
        return m_jniObject.callMethod<jobject>(
                        "setSmallIcon",
                        "(II)Landroid/app/Notification$Builder;", icon, level);
    }


    // method: public android.app.Notification.Builder setSmallIcon(android.graphics.drawable.Icon icon)
    auto setSmallIcon(jobject icon) const {
        return m_jniObject.callMethod<jobject>(
                        "setSmallIcon",
                        "(Landroid/graphics/drawable/Icon;)Landroid/app/Notification$Builder;", icon);
    }


    // method: public android.app.Notification.Builder setContentTitle(java.lang.CharSequence title)
    auto setContentTitle(jobject title) const {
        return m_jniObject.callMethod<jobject>(
                        "setContentTitle",
                        "(Ljava/lang/CharSequence;)Landroid/app/Notification$Builder;", title);
    }


    // method: public android.app.Notification.Builder setContentText(java.lang.CharSequence text)
    auto setContentText(jobject text) const {
        return m_jniObject.callMethod<jobject>(
                        "setContentText",
                        "(Ljava/lang/CharSequence;)Landroid/app/Notification$Builder;", text);
    }


    // method: public android.app.Notification.Builder setSubText(java.lang.CharSequence text)
    auto setSubText(jobject text) const {
        return m_jniObject.callMethod<jobject>(
                        "setSubText",
                        "(Ljava/lang/CharSequence;)Landroid/app/Notification$Builder;", text);
    }


    // method: public android.app.Notification.Builder setSettingsText(java.lang.CharSequence text)
    auto setSettingsText(jobject text) const {
        return m_jniObject.callMethod<jobject>(
                        "setSettingsText",
                        "(Ljava/lang/CharSequence;)Landroid/app/Notification$Builder;", text);
    }


    // method: public android.app.Notification.Builder setRemoteInputHistory(java.lang.CharSequence[] text)
    auto setRemoteInputHistory(jobjectArray text) const {
        return m_jniObject.callMethod<jobject>(
                        "setRemoteInputHistory",
                        "([Ljava/lang/CharSequence;)Landroid/app/Notification$Builder;", text);
    }


    // method: public android.app.Notification.Builder setNumber(int number)
    auto setNumber(jint number) const {
        return m_jniObject.callMethod<jobject>(
                        "setNumber",
                        "(I)Landroid/app/Notification$Builder;", number);
    }


    // method: public android.app.Notification.Builder setContentInfo(java.lang.CharSequence info)
    auto setContentInfo(jobject info) const {
        return m_jniObject.callMethod<jobject>(
                        "setContentInfo",
                        "(Ljava/lang/CharSequence;)Landroid/app/Notification$Builder;", info);
    }


    // method: public android.app.Notification.Builder setProgress(int max, int progress, boolean indeterminate)
    auto setProgress(jint max, jint progress, jboolean indeterminate) const {
        return m_jniObject.callMethod<jobject>(
                        "setProgress",
                        "(IIZ)Landroid/app/Notification$Builder;", max, progress, indeterminate);
    }


    // method: public android.app.Notification.Builder setContent(android.widget.RemoteViews views)
    auto setContent(jobject views) const {
        return m_jniObject.callMethod<jobject>(
                        "setContent",
                        "(Landroid/widget/RemoteViews;)Landroid/app/Notification$Builder;", views);
    }


    // method: public android.app.Notification.Builder setCustomContentView(android.widget.RemoteViews contentView)
    auto setCustomContentView(jobject contentView) const {
        return m_jniObject.callMethod<jobject>(
                        "setCustomContentView",
                        "(Landroid/widget/RemoteViews;)Landroid/app/Notification$Builder;", contentView);
    }


    // method: public android.app.Notification.Builder setCustomBigContentView(android.widget.RemoteViews contentView)
    auto setCustomBigContentView(jobject contentView) const {
        return m_jniObject.callMethod<jobject>(
                        "setCustomBigContentView",
                        "(Landroid/widget/RemoteViews;)Landroid/app/Notification$Builder;", contentView);
    }


    // method: public android.app.Notification.Builder setCustomHeadsUpContentView(android.widget.RemoteViews contentView)
    auto setCustomHeadsUpContentView(jobject contentView) const {
        return m_jniObject.callMethod<jobject>(
                        "setCustomHeadsUpContentView",
                        "(Landroid/widget/RemoteViews;)Landroid/app/Notification$Builder;", contentView);
    }


    // method: public android.app.Notification.Builder setContentIntent(android.app.PendingIntent intent)
    auto setContentIntent(jobject intent) const {
        return m_jniObject.callMethod<jobject>(
                        "setContentIntent",
                        "(Landroid/app/PendingIntent;)Landroid/app/Notification$Builder;", intent);
    }


    // method: public android.app.Notification.Builder setDeleteIntent(android.app.PendingIntent intent)
    auto setDeleteIntent(jobject intent) const {
        return m_jniObject.callMethod<jobject>(
                        "setDeleteIntent",
                        "(Landroid/app/PendingIntent;)Landroid/app/Notification$Builder;", intent);
    }


    // method: public android.app.Notification.Builder setFullScreenIntent(android.app.PendingIntent intent, boolean highPriority)
    auto setFullScreenIntent(jobject intent, jboolean highPriority) const {
        return m_jniObject.callMethod<jobject>(
                        "setFullScreenIntent",
                        "(Landroid/app/PendingIntent;Z)Landroid/app/Notification$Builder;", intent, highPriority);
    }


    // method: public android.app.Notification.Builder setTicker(java.lang.CharSequence tickerText)
    auto setTicker(jobject tickerText) const {
        return m_jniObject.callMethod<jobject>(
                        "setTicker",
                        "(Ljava/lang/CharSequence;)Landroid/app/Notification$Builder;", tickerText);
    }


    // method: public android.app.Notification.Builder setTicker(java.lang.CharSequence tickerText, android.widget.RemoteViews views)
    auto setTicker(jobject tickerText, jobject views) const {
        return m_jniObject.callMethod<jobject>(
                        "setTicker",
                        "(Ljava/lang/CharSequence;Landroid/widget/RemoteViews;)Landroid/app/Notification$Builder;", tickerText, views);
    }


    // method: public android.app.Notification.Builder setLargeIcon(android.graphics.Bitmap b)
    auto setLargeIcon__Landroid_graphics_Bitmap_2(jobject b) const {
        return m_jniObject.callMethod<jobject>(
                        "setLargeIcon",
                        "(Landroid/graphics/Bitmap;)Landroid/app/Notification$Builder;", b);
    }


    // method: public android.app.Notification.Builder setLargeIcon(android.graphics.drawable.Icon icon)
    auto setLargeIcon__Landroid_graphics_drawable_Icon_2(jobject icon) const {
        return m_jniObject.callMethod<jobject>(
                        "setLargeIcon",
                        "(Landroid/graphics/drawable/Icon;)Landroid/app/Notification$Builder;", icon);
    }


    // method: public android.app.Notification.Builder setSound(android.net.Uri sound)
    auto setSound(jobject sound) const {
        return m_jniObject.callMethod<jobject>(
                        "setSound",
                        "(Landroid/net/Uri;)Landroid/app/Notification$Builder;", sound);
    }


    // method: public android.app.Notification.Builder setSound(android.net.Uri sound, int streamType)
    auto setSound(jobject sound, jint streamType) const {
        return m_jniObject.callMethod<jobject>(
                        "setSound",
                        "(Landroid/net/Uri;I)Landroid/app/Notification$Builder;", sound, streamType);
    }


    // method: public android.app.Notification.Builder setSound(android.net.Uri sound, android.media.AudioAttributes audioAttributes)
    auto setSound(jobject sound, jobject audioAttributes) const {
        return m_jniObject.callMethod<jobject>(
                        "setSound",
                        "(Landroid/net/Uri;Landroid/media/AudioAttributes;)Landroid/app/Notification$Builder;", sound, audioAttributes);
    }


    // method: public android.app.Notification.Builder setVibrate(long[] pattern)
    auto setVibrate(jlongArray pattern) const {
        return m_jniObject.callMethod<jobject>(
                        "setVibrate",
                        "([J)Landroid/app/Notification$Builder;", pattern);
    }


    // method: public android.app.Notification.Builder setLights(int argb, int onMs, int offMs)
    auto setLights(jint argb, jint onMs, jint offMs) const {
        return m_jniObject.callMethod<jobject>(
                        "setLights",
                        "(III)Landroid/app/Notification$Builder;", argb, onMs, offMs);
    }


    // method: public android.app.Notification.Builder setOngoing(boolean ongoing)
    auto setOngoing(jboolean ongoing) const {
        return m_jniObject.callMethod<jobject>(
                        "setOngoing",
                        "(Z)Landroid/app/Notification$Builder;", ongoing);
    }


    // method: public android.app.Notification.Builder setColorized(boolean colorize)
    auto setColorized(jboolean colorize) const {
        return m_jniObject.callMethod<jobject>(
                        "setColorized",
                        "(Z)Landroid/app/Notification$Builder;", colorize);
    }


    // method: public android.app.Notification.Builder setOnlyAlertOnce(boolean onlyAlertOnce)
    auto setOnlyAlertOnce(jboolean onlyAlertOnce) const {
        return m_jniObject.callMethod<jobject>(
                        "setOnlyAlertOnce",
                        "(Z)Landroid/app/Notification$Builder;", onlyAlertOnce);
    }


    // method: public android.app.Notification.Builder setForegroundServiceBehavior(int behavior)
    auto setForegroundServiceBehavior(jint behavior) const {
        return m_jniObject.callMethod<jobject>(
                        "setForegroundServiceBehavior",
                        "(I)Landroid/app/Notification$Builder;", behavior);
    }


    // method: public android.app.Notification.Builder setAutoCancel(boolean autoCancel)
    auto setAutoCancel(jboolean autoCancel) const {
        return m_jniObject.callMethod<jobject>(
                        "setAutoCancel",
                        "(Z)Landroid/app/Notification$Builder;", autoCancel);
    }


    // method: public android.app.Notification.Builder setLocalOnly(boolean localOnly)
    auto setLocalOnly(jboolean localOnly) const {
        return m_jniObject.callMethod<jobject>(
                        "setLocalOnly",
                        "(Z)Landroid/app/Notification$Builder;", localOnly);
    }


    // method: public android.app.Notification.Builder setDefaults(int defaults)
    auto setDefaults(jint defaults) const {
        return m_jniObject.callMethod<jobject>(
                        "setDefaults",
                        "(I)Landroid/app/Notification$Builder;", defaults);
    }


    // method: public android.app.Notification.Builder setPriority(int pri)
    auto setPriority(jint pri) const {
        return m_jniObject.callMethod<jobject>(
                        "setPriority",
                        "(I)Landroid/app/Notification$Builder;", pri);
    }


    // method: public android.app.Notification.Builder setCategory(java.lang.String category)
    auto setCategory(jstring category) const {
        return m_jniObject.callMethod<jobject>(
                        "setCategory",
                        "(Ljava/lang/String;)Landroid/app/Notification$Builder;", category);
    }


    // method: public android.app.Notification.Builder addPerson(java.lang.String uri)
    auto addPerson(jstring uri) const {
        return m_jniObject.callMethod<jobject>(
                        "addPerson",
                        "(Ljava/lang/String;)Landroid/app/Notification$Builder;", uri);
    }


    // method: public android.app.Notification.Builder addPerson(android.app.Person person)
    auto addPerson(jobject person) const {
        return m_jniObject.callMethod<jobject>(
                        "addPerson",
                        "(Landroid/app/Person;)Landroid/app/Notification$Builder;", person);
    }


    // method: public android.app.Notification.Builder setGroup(java.lang.String groupKey)
    auto setGroup(jstring groupKey) const {
        return m_jniObject.callMethod<jobject>(
                        "setGroup",
                        "(Ljava/lang/String;)Landroid/app/Notification$Builder;", groupKey);
    }


    // method: public android.app.Notification.Builder setGroupSummary(boolean isGroupSummary)
    auto setGroupSummary(jboolean isGroupSummary) const {
        return m_jniObject.callMethod<jobject>(
                        "setGroupSummary",
                        "(Z)Landroid/app/Notification$Builder;", isGroupSummary);
    }


    // method: public android.app.Notification.Builder setSortKey(java.lang.String sortKey)
    auto setSortKey(jstring sortKey) const {
        return m_jniObject.callMethod<jobject>(
                        "setSortKey",
                        "(Ljava/lang/String;)Landroid/app/Notification$Builder;", sortKey);
    }


    // method: public android.app.Notification.Builder addExtras(android.os.Bundle extras)
    auto addExtras(jobject extras) const {
        return m_jniObject.callMethod<jobject>(
                        "addExtras",
                        "(Landroid/os/Bundle;)Landroid/app/Notification$Builder;", extras);
    }


    // method: public android.app.Notification.Builder setExtras(android.os.Bundle extras)
    auto setExtras(jobject extras) const {
        return m_jniObject.callMethod<jobject>(
                        "setExtras",
                        "(Landroid/os/Bundle;)Landroid/app/Notification$Builder;", extras);
    }


    // method: public android.os.Bundle getExtras()
    auto getExtras() const {
        return m_jniObject.callMethod<jobject>(
                        "getExtras",
                        "()Landroid/os/Bundle;");
    }


    // method: public android.app.Notification.Builder addAction(int icon, java.lang.CharSequence title, android.app.PendingIntent intent)
    auto addAction(jint icon, jobject title, jobject intent) const {
        return m_jniObject.callMethod<jobject>(
                        "addAction",
                        "(ILjava/lang/CharSequence;Landroid/app/PendingIntent;)Landroid/app/Notification$Builder;", icon, title, intent);
    }


    // method: public android.app.Notification.Builder addAction(android.app.Notification.Action action)
    auto addAction(jobject action) const {
        return m_jniObject.callMethod<jobject>(
                        "addAction",
                        "(Landroid/app/Notification$Action;)Landroid/app/Notification$Builder;", action);
    }


    // method: public android.app.Notification.Builder setActions(android.app.Notification.Action[] actions)
    auto setActions(jobjectArray actions) const {
        return m_jniObject.callMethod<jobject>(
                        "setActions",
                        "([Landroid/app/Notification$Action;)Landroid/app/Notification$Builder;", actions);
    }


    // method: public android.app.Notification.Builder setStyle(android.app.Notification.Style style)
    auto setStyle(jobject style) const {
        return m_jniObject.callMethod<jobject>(
                        "setStyle",
                        "(Landroid/app/Notification$Style;)Landroid/app/Notification$Builder;", style);
    }


    // method: public android.app.Notification.Style getStyle()
    auto getStyle() const {
        return m_jniObject.callMethod<jobject>(
                        "getStyle",
                        "()Landroid/app/Notification$Style;");
    }


    // method: public android.app.Notification.Builder setVisibility(int visibility)
    auto setVisibility(jint visibility) const {
        return m_jniObject.callMethod<jobject>(
                        "setVisibility",
                        "(I)Landroid/app/Notification$Builder;", visibility);
    }


    // method: public android.app.Notification.Builder setPublicVersion(android.app.Notification n)
    auto setPublicVersion(jobject n) const {
        return m_jniObject.callMethod<jobject>(
                        "setPublicVersion",
                        "(Landroid/app/Notification;)Landroid/app/Notification$Builder;", n);
    }


    // method: public android.app.Notification.Builder extend(android.app.Notification.Extender extender)
    auto extend(jobject extender) const {
        return m_jniObject.callMethod<jobject>(
                        "extend",
                        "(Landroid/app/Notification$Extender;)Landroid/app/Notification$Builder;", extender);
    }


    // method: public android.app.Notification.Builder setFlag(int mask, boolean value)
    auto setFlag(jint mask, jboolean value) const {
        return m_jniObject.callMethod<jobject>(
                        "setFlag",
                        "(IZ)Landroid/app/Notification$Builder;", mask, value);
    }


    // method: public android.app.Notification.Builder setColor(int argb)
    auto setColor(jint argb) const {
        return m_jniObject.callMethod<jobject>(
                        "setColor",
                        "(I)Landroid/app/Notification$Builder;", argb);
    }


    // method: public android.widget.RemoteViews createContentView()
    auto createContentView() const {
        return m_jniObject.callMethod<jobject>(
                        "createContentView",
                        "()Landroid/widget/RemoteViews;");
    }


    // method: public android.widget.RemoteViews createBigContentView()
    auto createBigContentView() const {
        return m_jniObject.callMethod<jobject>(
                        "createBigContentView",
                        "()Landroid/widget/RemoteViews;");
    }


    // method: public android.widget.RemoteViews createHeadsUpContentView()
    auto createHeadsUpContentView() const {
        return m_jniObject.callMethod<jobject>(
                        "createHeadsUpContentView",
                        "()Landroid/widget/RemoteViews;");
    }


    // method: public static android.app.Notification.Builder recoverBuilder(android.content.Context context, android.app.Notification n)
    static auto recoverBuilder(jobject context, jobject n) {
        return QJniObject::callStaticMethod<jobject>(FULL_CLASS_NAME,
                        "recoverBuilder",
                        "(Landroid/content/Context;Landroid/app/Notification;)Landroid/app/Notification$Builder;", context, n);
    }


    // method: public android.app.Notification.Builder setAllowSystemGeneratedContextualActions(boolean allowed)
    auto setAllowSystemGeneratedContextualActions(jboolean allowed) const {
        return m_jniObject.callMethod<jobject>(
                        "setAllowSystemGeneratedContextualActions",
                        "(Z)Landroid/app/Notification$Builder;", allowed);
    }


    // method: public android.app.Notification getNotification()
    auto getNotification() const {
        return m_jniObject.callMethod<jobject>(
                        "getNotification",
                        "()Landroid/app/Notification;");
    }


    // method: public android.app.Notification build()
    auto build() const {
        return m_jniObject.callMethod<jobject>(
                        "build",
                        "()Landroid/app/Notification;");
    }


};
} } // endof namespace android::app


namespace android { namespace app {


} } // endof namespace android::app

#endif // android_app_BuilderProxy_H

