
/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */

#ifndef GenerateCppCodeProxy_H
#define GenerateCppCodeProxy_H

#include <QJniObject>
#include <cmath>


class GenerateCppCodeProxy {
private:
    QJniObject m_jniObject;
    static constexpr double NaN = NAN;
public:
    static constexpr auto FULL_CLASS_NAME = "org/qtproject/qt/qtjenny_generator/GenerateCppCode";
    QJniObject getJniObject() const {return m_jniObject;}
    const QJniObject* operator->() const {return &m_jniObject;}
    template <class T> operator T() {return m_jniObject.object<T>();}
    GenerateCppCodeProxy() {}
    GenerateCppCodeProxy(const QJniObject& jniObject) {
        m_jniObject = jniObject;
    }
    GenerateCppCodeProxy(jobject globalRef) {
        m_jniObject = QJniObject(globalRef);
    }
    static GenerateCppCodeProxy fromLocalRef(jobject localRef) {
        GenerateCppCodeProxy res;
    res.m_jniObject = QJniObject::fromLocalRef(localRef);
    return res;
    }



};








#endif // GenerateCppCodeProxy_H

