/**
 * File generated by Jenny -- https://github.com/LanderlYoung/Jenny
 *
 * DO NOT EDIT THIS FILE.
 *
 * For bug report, please refer to github issue tracker https://github.com/LanderlYoung/Jenny/issues.
 */
#pragma once

#include <jni.h>

#include "GenerateCppCodeProxy.h"
#include "android_app_ActivityProxy.h"
#include "android_app_BuilderProxy.h"
#include "android_app_NotificationChannelProxy.h"
#include "android_app_NotificationManagerProxy.h"
#include "android_app_NotificationProxy.h"
#include "android_content_IntentProxy.h"
#include "android_drawable_drawableProxy.h"
#include "android_media_AudioManagerProxy.h"
#include "android_os_BatteryManagerProxy.h"
#include "android_os_ContextProxy.h"
#include "android_os_PowerManagerProxy.h"
#include "android_os_VibrationEffectProxy.h"
#include "android_os_VibratorManagerProxy.h"
#include "android_os_VibratorProxy.h"
#include "android_os_WakeLockProxy.h"
#include "android_provider_GlobalProxy.h"
#include "android_provider_SettingsProxy.h"
#include "android_provider_SystemProxy.h"
#include "android_view_LayoutParamsProxy.h"
#include "android_view_WindowProxy.h"

namespace jenny {

inline bool initAllProxies(JNIEnv* env) {

   bool success = 
        ::GenerateCppCodeProxy::initClazz(env) &&
        android::app::ActivityProxy::initClazz(env) &&
        android::app::BuilderProxy::initClazz(env) &&
        android::app::NotificationChannelProxy::initClazz(env) &&
        android::app::NotificationManagerProxy::initClazz(env) &&
        android::app::NotificationProxy::initClazz(env) &&
        android::content::IntentProxy::initClazz(env) &&
        android::drawable::drawableProxy::initClazz(env) &&
        android::media::AudioManagerProxy::initClazz(env) &&
        android::os::BatteryManagerProxy::initClazz(env) &&
        android::os::ContextProxy::initClazz(env) &&
        android::os::PowerManagerProxy::initClazz(env) &&
        android::os::VibrationEffectProxy::initClazz(env) &&
        android::os::VibratorManagerProxy::initClazz(env) &&
        android::os::VibratorProxy::initClazz(env) &&
        android::os::WakeLockProxy::initClazz(env) &&
        android::provider::GlobalProxy::initClazz(env) &&
        android::provider::SettingsProxy::initClazz(env) &&
        android::provider::SystemProxy::initClazz(env) &&
        android::view::LayoutParamsProxy::initClazz(env) &&
        android::view::WindowProxy::initClazz(env);
   return success;
}

} // end of namespace jenny
